#define no_command 0
#define load_dialogue_cmd 1
#define save_dialogue_cmd 2
#define unload_dialogue_cmd 3
#define quit_dialogue_cmd 4
#define insert_vc_cmd 5
#define copy_vc_cmd 6
#define move_vc_cmd 7
#define delete_vc_cmd 8
#define get_subvcs_cmd 9	
#define get_objects_cmd 10
#define insert_object_cmd 11
#define copy_object_cmd 12
#define move_object_cmd 13
#define delete_object_cmd 14
#define get_attributes_cmd 15
#define get_methods_cmd 16
#define insert_attribute_cmd 17
#define delete_attribute_cmd 18
#define object_instance_insert_cmd 19
#define object_instance_copy_cmd 20
#define object_instance_move_cmd 21
#define object_instance_delete_cmd 22
#define attribute_instance_insert_cmd 23
#define attribute_instance_delete_cmd 24
#define get_topmost_vcs_cmd 25
#define file_cmd 26

#define no_parameter 0
#define parent_vc_parm 1
#define vc_parm 3
#define to_vc_parm 4
