#define undefined_object_type -1
#define arc_object_type 0
#define box_widget_type 1
#define canvas_widget_type 2
#define command_widget_type 3
#define dialog_widget_type 4
#define form_widget_type 5
#define group_object_type 6
#define label_widget_type 7
#define line_object_type 8
#define pixmap_object_type 9
#define point_type 10
#define polygon_object_type 11
#define rectangle_object_type 12
#define scrollbar_widget_type 13
#define shell_widget_type 14
#define text_object_type 15
#define viewport_widget_type 16
#define vpane_widget_type 17
