#  Copyright International Business Machines, 1989
#
#
#
#  IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
#  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR ANY
#  PARTICULAR USE.  IN NO EVENT SHALL
#  IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
#  ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
#  WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
#  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
#  SOFTWARE
#
#
#
#
#!/bin/sh
MKFLAGS=-k
RMFLAGS=-f
X11=x11
SERVER=unix:0.0
#ARGS="-mintime 30 -timeout 360"
ARGS="-mintime 1 -timeout 360"
DATE="`date +"%d-%h-%y"`"
#                edit this !
MACHINE=
MONITOR=
MONITORNAME=
RELEASE=
BUILD=
#

#start test setup
#./Tools/clean.sh $RMFLAGS $MKFLAGS
#./Tools/compile.sh $MKFLAGS
make clean
make Makefile
make Makefiles
make depend
make

./Tools/config.sh $MACHINE $BUILD

MONITOR=8c
MONITORNAME=advcol

#generic stanza
HEADER0=$MACHINE
HEADER1=$BUILD
HEADER2=$DATE
./Tools/display.sh $MACHINE $MONITOR $MONITORNAME
./Tools/bench.sh $MACHINE $SERVER $MONITOR $BUILD $ARGS
./Tools/report.sh $HEADER0 $HEADER1 $HEADER2 $MACHINE $MONITOR $BUILD
