#!/bin/csh -f
## ###################################################################### ##
##         Copyright IBM Corporation 1988,1989 - All Rights Reserved      ##
##        For full copyright information see:'andrew/config/COPYRITE'     ##
## ###################################################################### ##
#
# This script may be used for generating a spiffy demo folder/bboard for the Andrew Message system.
#
# It assumes you have run an AMS appliation at least once, to create the .MESSAGES 
# tree in your home directory or wherever it is you're creating the demo folder.
#
# See the imkfile in this directory for further explanations.

set force=0
if ($#argv > 1 && "$1" == "-force") then
    set force=1
    shift
endif
if ( $?ANDREWDIR ) then
    set AndrewDir = "$ANDREWDIR"
else
    set AndrewDir = "/usr/andrew"
endif
if ($#argv > 2 && "$1" == "-DESTDIR" ) then
    set AndrewDir=$2
    shift
    shift
endif
if ($#argv < 1) then
    echo Usage:  gendemo creatable-folder-name
    echo Example use: gendemo \~/.MESSAGES/amsdemo
    exit 1
endif
if ($force == 0) then
    echo -n "Do you want to create a messages demo folder in the directory $1, erasing any previous contents AND ALL SUBDIRECTORIES recursively [no] ? "
    set ans=$<
    if ($ans !~ y*) then
       echo No demo created.
       exit
    endif
endif
set targetdir=$1
if (-e $targetdir) then
	rm -rf $targetdir
	if ($status != 0) then
		echo rm failed, aborting.
		exit
	endif
endif
$AndrewDir/bin/cui set level wizard \; set script on \; set term 0 \; create $targetdir:t \; quit <<!
$targetdir:h

!
# sanity check next
if (! -d $targetdir) then
	echo $targetdir is not a directory--aborting.
	exit 1
endif
set Me=`whoami`
@ i = 1
while (1)
	if (! -e d$i.heads) break
	echo Processing post number $i
	echo "Date: `$AndrewDir/etc/arpadate`" > /tmp/demotemp
	echo From: ${Me} >> /tmp/demotemp
	echo To: AMS Demo Part $i >> /tmp/demotemp
	echo Content-Type: X-BE2\; 12 >> /tmp/demotemp
	echo If-Type-Unsupported: send >> /tmp/demotemp
	cat d$i.heads >> /tmp/demotemp
	echo "" >> /tmp/demotemp
	cat d$i >> /tmp/demotemp
	mv /tmp/demotemp $targetdir/$i.post
	@ i ++
end
$AndrewDir/bin/cui set level wizard \; set script on \; set term 0 \; recon $targetdir\; quit <<!


!
