.TH pgmtofits 1 "20 September 1989"
.SH NAME
pgmtofits - convert a portable graymap into FITS format
.SH SYNOPSIS
pgmtofits [<pgmfile>]
.SH DESCRIPTION
Reads a portable graymap as input.
Produces a FITS file as output.
.PP
FITS stands for Flexible Image Transport System.  A full description
can be found in Astronomy & Astrophysics Supplement Series 44 (1981),
page 363.
.SH "SEE ALSO"
fitstopgm(1), pgm(5)
.SH AUTHOR
Wilson H. Bent
