/**********************************************
(c) Copyright 1988 Carnegie Mellon University
See andrew/oda/doc/COPYRITE
***********************************************/

/*
		(c) Copyright 1988 Carnegie Mellon University

 See "The CMU ODA Tool Kit" (available as CMU/ITC tech report
 CMU-ITC-071) for full text & permitted uses.


    ATK .c file generated by a script
*/

#include <class.h>
#include <odatk.h>
#include <odaiso.h>

#ifndef USE_BCOPY
INT_type LOCAL_Bcopy(from, to, length)
    POINTER_type from, to;
    INT_type length;
{
    return 0;
}
#endif

#ifndef SWAPPING
typedef int SWAP_INFO_type;

SWAP_INFO_type *LOCAL_SwapOut(address, length)
    POINTER_type address;
    INT_type length;
{
    return((SWAP_INFO_type *) 0);
}

INT_type LOCAL_SwapIn(swapinfo, address, available)
    SWAP_INFO_type *swapinfo;
    POINTER_type address;
    INT_type available;
{
    return 0;
}
#endif

#include <odalib.eh>

SEQUENCE_type odalib__ERROR_SEQUENCE(classID)
    struct classheader *classID;
{
    return ERROR_SEQUENCE;
}

SEQUENCE_type odalib__NULL_SEQUENCE(classID)
    struct classheader *classID;
{
    return NULL_SEQUENCE;
}

CONSTITUENT odalib__ERROR_CONSTITUENT(classID)
    struct classheader *classID;
{
    return ERROR_CONSTITUENT;
}

CONSTITUENT odalib__NULL_CONSTITUENT(classID)
    struct classheader *classID;
{
    return NULL_CONSTITUENT;
}

DOCUMENT_type odalib__ERROR_DOCUMENT(classID)
    struct classheader *classID;
{
    return ERROR_DOCUMENT;
}

STRING_type odalib__ERROR_STRING(classID)
    struct classheader *classID;
{
    return ERROR_STRING;
}

STRING_type odalib__NULL_STRING(classID)
    struct classheader *classID;
{
    return NULL_STRING;
}

ITERATOR_type odalib__ERROR_ITERATOR(classID)
    struct classheader *classID;
{
    return ERROR_ITERATOR;
}

ASN1_OBJECT_ID_type odalib__at_CONTENT_ARCH_CLASS_form_cc(classID)
    struct classheader *classID;
{
    return at_CONTENT_ARCH_CLASS_form_cc;
}

ASN1_OBJECT_ID_type odalib__at_CONTENT_ARCH_CLASS_proc_cc(classID)
    struct classheader *classID;
{
    return at_CONTENT_ARCH_CLASS_proc_cc;
}

ASN1_OBJECT_ID_type odalib__at_CONTENT_ARCH_CLASS_fp_cc(classID)
    struct classheader *classID;
{
    return at_CONTENT_ARCH_CLASS_fp_cc;
}

ASN1_OBJECT_ID_type odalib__at_CONTENT_ARCH_CLASS_form_rg(classID)
    struct classheader *classID;
{
    return at_CONTENT_ARCH_CLASS_form_rg;
}

ASN1_OBJECT_ID_type odalib__at_CONTENT_ARCH_CLASS_fp_rg(classID)
    struct classheader *classID;
{
    return at_CONTENT_ARCH_CLASS_fp_rg;
}

ASN1_OBJECT_ID_type odalib__at_CONTENT_ARCH_CLASS_form_gg(classID)
    struct classheader *classID;
{
    return at_CONTENT_ARCH_CLASS_form_gg;
}

ASN1_OBJECT_ID_type odalib__at_TYPE_OF_CODING_cc(classID)
    struct classheader *classID;
{
    return at_TYPE_OF_CODING_cc;
}

ASN1_OBJECT_ID_type odalib__at_TYPE_OF_CODING_T6(classID)
    struct classheader *classID;
{
    return at_TYPE_OF_CODING_T6;
}

ASN1_OBJECT_ID_type odalib__at_TYPE_OF_CODING_T4_1(classID)
    struct classheader *classID;
{
    return at_TYPE_OF_CODING_T4_1;
}

ASN1_OBJECT_ID_type odalib__at_TYPE_OF_CODING_T4_2(classID)
    struct classheader *classID;
{
    return at_TYPE_OF_CODING_T4_2;
}

ASN1_OBJECT_ID_type odalib__at_TYPE_OF_CODING_bitmap(classID)
    struct classheader *classID;
{
    return at_TYPE_OF_CODING_bitmap;
}

ASN1_OBJECT_ID_type odalib__at_TYPE_OF_CODING_gg(classID)
    struct classheader *classID;
{
    return at_TYPE_OF_CODING_gg;
}

INT_type odalib__TKError(classID)
    struct classheader *classID;
{
    return TKError;
}

CHAR_type *odalib__TKErrorMesg(classID)
    struct classheader *classID;
{
    return TKErrorMesg;
}

INT_type odalib__SetAttr(classID, constituent, attribute, value, mask)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    POINTER_type value;
    PARM_MASK_type mask;
{
    return SetAttr(constituent, attribute, value, mask);
}

INT_type odalib__GetAttr(classID, constituent, attribute, value, inherited, mask)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    POINTER_type value;
    BOOL_type inherited;
    PARM_MASK_type *mask;
{
    return GetAttr(constituent, attribute, value, inherited, mask);
}

INT_type odalib__SetIntAttr(classID, constituent, attribute, value)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    INT_type value;
{
    return SetIntAttr(constituent, attribute, value);
}

INT_type odalib__GetIntAttr(classID, constituent, attribute, value, inherited)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    INT_type *value;
    BOOL_type inherited;
{
    return GetIntAttr(constituent, attribute, value, inherited);
}

INT_type odalib__SetValueAttr(classID, constituent, attribute, value)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    VALUE_type value;
{
    return SetValueAttr(constituent, attribute, value);
}

INT_type odalib__GetValueAttr(classID, constituent, attribute, value, inherited)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    VALUE_type *value;
    BOOL_type inherited;
{
    return GetValueAttr(constituent, attribute, value, inherited);
}

INT_type odalib__SetLayoutAttr(classID, constituent, attribute, value, mask)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    POINTER_type value;
    PARM_MASK_type mask;
{
    return SetLayoutAttr(constituent, attribute, value, mask);
}

INT_type odalib__SetPresAttr(classID, constituent, attribute, value, mask)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    POINTER_type value;
    PARM_MASK_type mask;
{
    return SetPresAttr(constituent, attribute, value, mask);
}

INT_type odalib__SetStringAttr(classID, constituent, attribute, value, chars)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    CHAR_type * value;
    BOOL_type chars;
{
    return SetStringAttr(constituent, attribute, value, chars);
}

INT_type odalib__AppendSubordinate(classID, parent,child)
    struct classheader *classID;
    CONSTITUENT parent;
    CONSTITUENT child;
{
    return AppendSubordinate(parent, child);
}

VALUE_type odalib__GetContentKind(classID, constituent)
    struct classheader *classID;
    CONSTITUENT constituent;
{
    return GetContentKind(constituent);
}

SEQUENCE_BYTE_type odalib__GetContent(classID, constituent)
    struct classheader *classID;
    CONSTITUENT constituent;
{
    return GetContent(constituent);
}

INT_type odalib__HasAttr(classID, constituent, attribute)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
{
    return HasAttr(constituent, attribute);
}

INT_type odalib__RemAttr(classID, constituent, attribute)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
{
    return RemAttr(constituent, attribute);
}

INT_type odalib__UnspecParms(classID, constituent, attribute, unspec)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    PARM_MASK_type unspec;
{
    return UnspecParms(constituent, attribute, unspec);
}

INT_type odalib__GetParmMask(classID, constituent, attribute, mask)
    struct classheader *classID;
    CONSTITUENT constituent;
    INT_type attribute;
    PARM_MASK_type *mask;
{
    return GetParmMask(constituent, attribute, mask);
}

CHAR_type *odalib__GetAttrName(classID, attribute)
    struct classheader *classID;
    INT_type attribute;
{
    return GetAttrName(attribute);
}

CHAR_type *odalib__GetValueName(classID, value)
    struct classheader *classID;
    VALUE_type value;
{
    return GetValueName(value);
}

INT_type odalib__WriteDocumentState(classID, od, document)
    struct classheader *classID;
    INT_type od;
    DOCUMENT_type document;
{
    return WriteDocumentState(od, document);
}

INT_type odalib__WriteSubgraphState(classID, od, constituent)
    struct classheader *classID;
    INT_type od;
    CONSTITUENT constituent;
{
    return WriteSubgraphState(od, constituent);
}

INT_type odalib__WriteStylesState(classID, od, document, islayout)
    struct classheader *classID;
    INT_type od;
    DOCUMENT_type document;
    BOOL_type islayout;
{
    return WriteStylesState(od, document, islayout);
}

INT_type odalib__WriteConstituentState(classID, od, constituent)
    struct classheader *classID;
    INT_type od;
    CONSTITUENT constituent;
{
    return WriteConstituentState(od, constituent);
}

INT_type odalib__isode_PrintODIF(classID, infile)
    struct classheader *classID;
    FILE * infile;
{
    return isode_PrintODIF(infile);
}

STRING_type odalib__EvalStringExpr(classID, expr)
    struct classheader *classID;
    STRING_EXPR_type *expr;
{
    return EvalStringExpr(expr);
}

INT_type odalib__EvalNumExpr(classID, expr, value)
    struct classheader *classID;
    NUMERIC_EXPR_type *expr;
    INT_type *value;
{
    return EvalNumExpr(expr, value);
}

CONSTITUENT odalib__EvalObjIdExpr(classID, expr)
    struct classheader *classID;
    OBJECT_ID_EXPR_type *expr;
{
    return EvalObjIdExpr(expr);
}

INT_type odalib__DeleteConstExpr(classID, construction_expression)
    struct classheader *classID;
    
    CONSTRUCTION_EXPR_type *construction_expression;
{
    return DeleteConstExpr(construction_expression);
}

INT_type odalib__EvalRefBind(classID, refbind, string, integer)
    struct classheader *classID;
    REF_BINDING_VALUE_type *refbind;
    STRING_type *string;
    INT_type *integer;
{
    return EvalRefBind(refbind, string, integer);
}

INT_type odalib__InitToolKit(classID, parms)
    struct classheader *classID;
    INIT_PARMS_type *parms;
{
    return InitToolKit(parms);
}

INT_type odalib__FinalToolKit(classID)
    struct classheader *classID;
{
    return FinalToolKit();
}




DOCUMENT_type odalib__ReadODIF(classID, id)
    struct classheader *classID;
    INT_type id;
{
    return ReadODIF(id);
}

INT_type odalib__WriteODIF(classID, od, document, format)
    struct classheader *classID;
    INT_type od;
    DOCUMENT_type document;
    VALUE_type format;
{
    return WriteODIF(od, document, format);
}

DOCUMENT_type odalib__isode_ReadODIF(classID, infile)
    struct classheader *classID;
    FILE * infile;
{
    return isode_ReadODIF(infile);
}

INT_type odalib__isode_WriteODIF(classID, outfile, document, format)
    struct classheader *classID;
    FILE * outfile;
    DOCUMENT_type document;
    VALUE_type format;
{
    return isode_WriteODIF(outfile, document, format);
}

INT_type odalib__LabelDocument(classID, document)
    struct classheader *classID;
    DOCUMENT_type document;
{
    return LabelDocument(document);
}

INT_type odalib__LabelStructure(classID, root)
    struct classheader *classID;
    CONSTITUENT root;
{
    return LabelStructure(root);
}

INT_type odalib__LabelStyles(classID, document, islayout)
    struct classheader *classID;
    DOCUMENT_type document;
    BOOL_type islayout;
{
    return LabelStyles(document, islayout);
}

DOCUMENT_type odalib__MakeDocument(classID)
    struct classheader *classID;
{
    return MakeDocument();
}

DOCUMENT_type odalib__GetDocument(classID, constituent)
    struct classheader *classID;
    CONSTITUENT constituent;
{
    return GetDocument(constituent);
}

INT_type odalib__DeleteDocument(classID, document, delete)
    struct classheader *classID;
    DOCUMENT_type document;
    BOOL_type delete;
{
    return DeleteDocument(document, delete);
}

CONSTITUENT odalib__MakeComponent(classID, document, type, kind)
    struct classheader *classID;
    DOCUMENT_type document;
    VALUE_type type;
    VALUE_type kind;
{
    return MakeComponent(document, type, kind);
}

CONSTITUENT odalib__MakeStyle(classID, document, kind)
    struct classheader *classID;
    DOCUMENT_type document;
    VALUE_type kind;
{
    return MakeStyle(document, kind);
}

CONSTITUENT odalib__MakeContent(classID, document, type)
    struct classheader *classID;
    DOCUMENT_type document;
    VALUE_type type;
{
    return MakeContent(document, type);
}

CONSTITUENT odalib__MakeDocumentProfile(classID, document)
    struct classheader *classID;
    DOCUMENT_type document;
{
    return MakeDocumentProfile(document);
}

CONSTITUENT odalib__CopyConstituent(classID, document, constituent)
    struct classheader *classID;
    DOCUMENT_type document;
    CONSTITUENT constituent;
{
    return CopyConstituent(document, constituent);
}

INT_type odalib__DeleteConstituent(classID, constituent)
    struct classheader *classID;
    CONSTITUENT constituent;
{
    return DeleteConstituent(constituent);
}

INT_type odalib__HoldConstituent(classID, constituent)
    struct classheader *classID;
    CONSTITUENT constituent;
{
    return HoldConstituent(constituent);
}

INT_type odalib__ReleaseConstituent(classID, constituent)
    struct classheader *classID;
    CONSTITUENT constituent;
{
    return ReleaseConstituent(constituent);
}

INT_type odalib__HoldAttr(classID, attribute)
    struct classheader *classID;
    INT_type attribute;
{
    return HoldAttr(attribute);
}

INT_type odalib__ReleaseAttr(classID, attribute)
    struct classheader *classID;
    INT_type attribute;
{
    return ReleaseAttr(attribute);
}

INT_type odalib__HoldString(classID, string)
    struct classheader *classID;
    STRING_type string;
{
    return HoldString(string);
}

INT_type odalib__ReleaseString(classID, string)
    struct classheader *classID;
    STRING_type string;
{
    return ReleaseString(string);
}

INT_type odalib__ComponentAttrPriority(classID, set, type, class, attr, priority)
    struct classheader *classID;
    BOOL_type set;
    VALUE_type type;
    BOOL_type class;
    INT_type attr;
    INT_type *priority;
{
    return ComponentAttrPriority(set, type, class, attr, priority);
}

INT_type odalib__StyleAttrPriority(classID, set, type, attribute, priority)
    struct classheader *classID;
    BOOL_type set;
    VALUE_type type;
    INT_type attribute;
    INT_type *priority;
{
    return StyleAttrPriority(set, type, attribute, priority);
}

INT_type odalib__ContentAttrPriority(classID, set, type, attribute, priority)
    struct classheader *classID;
    BOOL_type set;
    INT_type type;
    INT_type attribute;
    INT_type *priority;
{
    return ContentAttrPriority(set, type, attribute, priority);
}

INT_type odalib__AttrDocProfPriority(classID, set, attribute, priority)
    struct classheader *classID;
    BOOL_type set;
    INT_type attribute;
    INT_type *priority;
{
    return AttrDocProfPriority(set, attribute, priority);
}

INT_type odalib__LOCAL_Init(classID)
    struct classheader *classID;
{
    return LOCAL_Init();
}

INT_type odalib__LOCAL_Final(classID)
    struct classheader *classID;
{
    return LOCAL_Final();
}

INT_type odalib__LOCAL_ReadBytes(classID, id, buffer, length)
    struct classheader *classID;
    INT_type id;
    BYTE_type buffer[];
    INT_type length;
{
    return LOCAL_ReadBytes(id, buffer, length);
}

INT_type odalib__LOCAL_WriteBytes(classID, od, buffer, length)
    struct classheader *classID;
    INT_type od;
    BYTE_type buffer[];
    INT_type length;
{
    return LOCAL_WriteBytes(od, buffer, length);
}

INT_type odalib__LOCAL_ReadChars(classID, id, buffer, length)
    struct classheader *classID;
    INT_type id;
    CHAR_type buffer[];
    INT_type length;
{
    return LOCAL_ReadChars(id, buffer, length);
}

INT_type odalib__LOCAL_WriteChars(classID, od, buffer, length)
    struct classheader *classID;
    INT_type od;
    CHAR_type buffer[];
    INT_type length;
{
    return LOCAL_WriteChars(od, buffer, length);
}

POINTER_type odalib__LOCAL_Malloc(classID, nbytes)
    struct classheader *classID;
    INT_type nbytes;
{
    return LOCAL_Malloc(nbytes);
}

POINTER_type odalib__LOCAL_Realloc(classID, old, newsize)
    struct classheader *classID;
    POINTER_type old;
    INT_type newsize;
{
    return LOCAL_Realloc(old, newsize);
}

INT_type odalib__LOCAL_Free(classID, block)
    struct classheader *classID;
    POINTER_type block;
{
    return LOCAL_Free(block);
}

INT_type odalib__LOCAL_Bcopy(classID, from, to, length)
    struct classheader *classID;
    POINTER_type from;
    POINTER_type to;
    INT_type length;
{
    return LOCAL_Bcopy(from, to, length);
}

SWAP_INFO_type *odalib__LOCAL_SwapOut(classID, address, length)
    struct classheader *classID;
    POINTER_type address;
    INT_type length;
{
    return LOCAL_SwapOut(address, length);
}

INT_type odalib__LOCAL_SwapIn(classID, swapinfo, address, available)
    struct classheader *classID;
    SWAP_INFO_type *swapinfo;
    POINTER_type address;
    INT_type available;
{
    return LOCAL_SwapIn(swapinfo, address, available);
}

INT_type odalib__UnspecifyFont(classID, font)
    struct classheader *classID;
    FONT_REFERENCE_type *font;
{
    return UnspecifyFont(font);
}

SEQUENCE_INT_type odalib__Dsclass2Ints(classID, value)
    struct classheader *classID;
    VALUE_type value;
{
    return Dsclass2Ints(value);
}

VALUE_type odalib__Ints2Dsclass(classID, ints)
    struct classheader *classID;
    SEQUENCE_INT_type ints;
{
    return Ints2Dsclass(ints);
}

INT_type odalib__Array2StrctName(classID, NameArray, NumName, StructuredName)
    struct classheader *classID;
    CHAR_type **NameArray;
    INT_type NumName;
    STRUCTURED_NAME_type * StructuredName;
{
    return Array2StrctName(NameArray, NumName, StructuredName);
}

INT_type odalib__String2StrctName(classID, NameString, StructuredName)
    struct classheader *classID;
    CHAR_type *NameString;
    STRUCTURED_NAME_type * StructuredName;
{
    return String2StrctName(NameString, StructuredName);
}

INT_type odalib__SetFontFamilyArray(classID, FontReference, FamilyArray, NumNames)
    struct classheader *classID;
    FONT_REFERENCE_type * FontReference;
    CHAR_type ** FamilyArray;
    INT_type NumNames;
{
    return SetFontFamilyArray(FontReference, FamilyArray, NumNames);
}

INT_type odalib__SetFontFamily(classID, FontReference, NameString)
    struct classheader *classID;
    FONT_REFERENCE_type * FontReference;
    CHAR_type *NameString;
{
    return SetFontFamily(FontReference, NameString);
}

VALUE_type odalib__LookUpObjectId(classID, id)
    struct classheader *classID;
    ASN1_OBJECT_ID_type id;
{
    return LookUpObjectId(id);
}

INT_type odalib__UnspecifyDefaultValueLists(classID, default_value_lists)
    struct classheader *classID;
    at_DEFAULT_VALUE_LISTS_type *default_value_lists;
{
    return UnspecifyDefaultValueLists(default_value_lists);
}

INT_type odalib__InitializeDefaultValueLists(classID, doc,default_value_lists,constituent_mask)
    struct classheader *classID;
    DOCUMENT_type doc;
    at_DEFAULT_VALUE_LISTS_type *default_value_lists;
    PARM_MASK_type constituent_mask;
{
    return InitializeDefaultValueLists(doc, default_value_lists, constituent_mask);
}

SEQUENCE_type odalib__MakeSequence(classID, type, length)
    struct classheader *classID;
    TAG_type type;
    INT_type length;
{
    return MakeSequence(type, length);
}

INT_type odalib__DeleteSequence(classID, sequence)
    struct classheader *classID;
    SEQUENCE_type sequence;
{
    return DeleteSequence(sequence);
}

INT_type odalib__DeleteSequenceDeeply(classID, sequence)
    struct classheader *classID;
    SEQUENCE_type sequence;
{
    return DeleteSequenceDeeply(sequence);
}

INT_type odalib__ExpandSequence(classID, sequence, amount)
    struct classheader *classID;
    SEQUENCE_type sequence;
    INT_type amount;
{
    return ExpandSequence(sequence, amount);
}

INT_type odalib__ContractSequence(classID, sequence, amount)
    struct classheader *classID;
    SEQUENCE_type sequence;
    INT_type amount;
{
    return ContractSequence(sequence, amount);
}

INT_type odalib__AppendSequence(classID, s1, s2)
    struct classheader *classID;
    SEQUENCE_type s1;
    SEQUENCE_type s2;
{
    return AppendSequence(s1, s2);
}

SEQUENCE_type odalib__CopySequence(classID, sequence)
    struct classheader *classID;
    SEQUENCE_type sequence;
{
    return CopySequence(sequence);
}

STRING_type odalib__MakeString(classID, len)
    struct classheader *classID;
    INT_type len;
{
    return MakeString(len);
}

STRING_type odalib__Chars2String(classID, str)
    struct classheader *classID;
    CHAR_type *str;
{
    return Chars2String(str);
}

INT_type odalib__DeleteString(classID, string)
    struct classheader *classID;
    STRING_type string;
{
    return DeleteString(string);
}

STRING_type odalib__ConcatString(classID, s1, s2)
    struct classheader *classID;
    STRING_type s1;
    STRING_type s2;
{
    return ConcatString(s1, s2);
}

CONSTITUENT odalib__FindDocumentRoot(classID, document, kind)
    struct classheader *classID;
    DOCUMENT_type document;
    VALUE_type kind;
{
    return FindDocumentRoot(document, kind);
}

CONSTITUENT odalib__FindDocumentProfile(classID, document)
    struct classheader *classID;
    DOCUMENT_type document;
{
    return FindDocumentProfile(document);
}

ITERATOR_type odalib__MakeSubgraphIterator(classID, root, parent_order, walk_order)
    struct classheader *classID;
    CONSTITUENT root;
    VALUE_type parent_order;
    VALUE_type walk_order;
{
    return MakeSubgraphIterator(root, parent_order, walk_order);
}

ITERATOR_type odalib__MakeStylesIterator(classID, document, kind)
    struct classheader *classID;
    DOCUMENT_type document;
    VALUE_type kind;
{
    return MakeStylesIterator(document, kind);
}

CONSTITUENT odalib__NextConstituent(classID, iterator)
    struct classheader *classID;
    ITERATOR_type iterator;
{
    return NextConstituent(iterator);
}

INT_type odalib__DeleteIterator(classID, iterator)
    struct classheader *classID;
    ITERATOR_type iterator;
{
    return DeleteIterator(iterator);
}
