#define	CRED		(1 << 9)
#define	CGREEN		(1 << 8)
#define	CBLUE		(1 << 7)
#define	CCYAN		(1 << 6)
#define	CMAGENTA	(1 << 5)
#define	CYELLOW		(1 << 4)
#define	CHUE		(1 << 3)
#define	CSATURATION	(1 << 2)
#define	CVALUE		(1 << 1)
#define	CLIGHTNESS	1
