/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISPR12 */
# line 5 "ispr12.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	print_ISPR12_Raster__Graphics__Attributes (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p0_count = 0;
    register PE p0;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Raster-Graphics-Attributes bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Raster-Graphics-Attributes bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p0 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Raster-Graphics-Attributes bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p0;

    vpush ();
    if (p0 = set_find (pe, PE_CLASS_CONT, 0)) {
        vname ("pel-path");
        if (print_ISPR12_One__Of__Four__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 1)) {
        vname ("line-progression");
        if (print_ISPR12_One__Of__Two__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 2)) {
        vname ("pel-transmission-density");
        if (print_ISPR12_Pel__Transmission__Density (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 3)) {
        vname ("initial-offset");
        if (print_ISPR4_Measure__Pair (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 4)) {
        vname ("clipping");
        if (print_ISPR12_Clipping (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 5)) {
        register PE p1 = p0;

        {	/* pel-spacing TAG PULLUP */
            register PE p2;

            if ((p2 = prim2set (p1)) == NULLPE) {
                advise (NULLCP, "pel-spacing bad pel-spacing: %s",
                        pe_error (p1 -> pe_errno));
                return NOTOK;
            }
            if (p2 -> pe_cardinal != 1) {
                advise (NULLCP, "pel-spacing too many elements for tagged pel-spacing: %d",
                        p2 -> pe_cardinal);
                return NOTOK;
            }
            p1 = first_member (p2);
        }
        {
            vname ("pel-spacing");
            if (print_ISPR12_Pel__Spacing (p1, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 6)) {
        vname ("spacing-ratio");
        if (print_ISPR12_Spacing__Ratio (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 7)) {
        register PE p3 = p0;

        {	/* image-dimensions TAG PULLUP */
            register PE p4;

            if ((p4 = prim2set (p3)) == NULLPE) {
                advise (NULLCP, "image-dimensions bad image-dimensions: %s",
                        pe_error (p3 -> pe_errno));
                return NOTOK;
            }
            if (p4 -> pe_cardinal != 1) {
                advise (NULLCP, "image-dimensions too many elements for tagged image-dimensions: %d",
                        p4 -> pe_cardinal);
                return NOTOK;
            }
            p3 = first_member (p4);
        }
        {
            vname ("image-dimensions");
            if (print_ISPR12_Image__Dimensions (p3, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p0_count ++;
    }
    if (p0_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_One__Of__Four__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p5;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Four-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Four-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p5 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Four-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p5;
    switch (p5) {
        case 0:	/* d0 */
            vprint ("d0");
            break;
        case 1:	/* d90 */
            vprint ("d90");
            break;
        case 2:	/* d180 */
            vprint ("d180");
            break;
        case 3:	/* d270 */
            vprint ("d270");
            break;
        default:
            advise (NULLCP, "One-Of-Four-Angles has unknown component: %d", p5);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_One__Of__Two__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p6;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Two-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Two-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p6 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Two-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p6;
    switch (p6) {
        case 1:	/* d90 */
            vprint ("d90");
            break;
        case 3:	/* d270 */
            vprint ("d270");
            break;
        default:
            advise (NULLCP, "One-Of-Two-Angles has unknown component: %d", p6);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_Pel__Transmission__Density (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p7;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Pel-Transmission-Density bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Pel-Transmission-Density bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p7 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Pel-Transmission-Density bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p7;
    switch (p7) {
        case 1:	/* p6 */
            vprint ("p6");
            break;
        case 2:	/* p5 */
            vprint ("p5");
            break;
        case 3:	/* p4 */
            vprint ("p4");
            break;
        case 4:	/* p3 */
            vprint ("p3");
            break;
        case 5:	/* p2 */
            vprint ("p2");
            break;
        case 6:	/* p1 */
            vprint ("p1");
            break;
        default:
            advise (NULLCP, "Pel-Transmission-Density has unknown component: %d", p7);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_Clipping (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p8;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Clipping bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Clipping bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p8 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Clipping bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p8;

    vpush ();
    {
        register PE p9;

        if ((p9 = first_member (pe)) != NULLPE
                && PE_ID (p9 -> pe_class, p9 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p9 = NULLPE;
        if (p9 != NULLPE) {
            p8 = p9;

            {	/* first-coordinate-pair */
                vname ("first-coordinate-pair");
                if (print_ISPR12_Coordinate__Pair (p9, 0, NULLIP, NULLVP, NullParm) == NOTOK)
                    return NOTOK;
            }
        }
    }

    {
        register PE p10;

        if ((p10 = (pe != p8 ? next_member (pe, p8) : first_member (pe))) != NULLPE) {
            p8 = p10;

            {	/* second-coordinate-pair */
                vname ("second-coordinate-pair");
                if (print_ISPR12_Coordinate__Pair (p10, 0, NULLIP, NULLVP, NullParm) == NOTOK)
                    return NOTOK;
            }
        }
        else {
            advise (NULLCP, "Clipping missing second-coordinate-pair element");
            return NOTOK;
        }

    }

    vpop ();

    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Clipping has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_Coordinate__Pair (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p11;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Coordinate-Pair bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Coordinate-Pair bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p11 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Coordinate-Pair bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p11;

    vpush ();
    {
        register PE p12;

        if ((p12 = first_member (pe)) != NULLPE) {
            p11 = p12;

            {	/* x-coordinate */
                register int p13;

                if (p12 -> pe_class != PE_CLASS_UNIV
                        || p12 -> pe_form != PE_FORM_PRIM
                        || p12 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "x-coordinate bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p12 -> pe_class], p12 -> pe_form, p12 -> pe_id);
                    return NOTOK;
                }

                vname ("x-coordinate");
                if ((p13 = prim2num (p12)) == NOTOK
                        && p12 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "x-coordinate bad integer: %s",
                            pe_error (p12 -> pe_errno));
                    return NOTOK;
                }
                vprint ("%d", p13);
            }
        }
        else {
            advise (NULLCP, "Coordinate-Pair missing x-coordinate element");
            return NOTOK;
        }

    }

    {
        register PE p14;

        if ((p14 = (pe != p11 ? next_member (pe, p11) : first_member (pe))) != NULLPE) {
            p11 = p14;

            {	/* y-coordinate */
                register int p15;

                if (p14 -> pe_class != PE_CLASS_UNIV
                        || p14 -> pe_form != PE_FORM_PRIM
                        || p14 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "y-coordinate bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p14 -> pe_class], p14 -> pe_form, p14 -> pe_id);
                    return NOTOK;
                }

                vname ("y-coordinate");
                if ((p15 = prim2num (p14)) == NOTOK
                        && p14 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "y-coordinate bad integer: %s",
                            pe_error (p14 -> pe_errno));
                    return NOTOK;
                }
                vprint ("%d", p15);
            }
        }
        else {
            advise (NULLCP, "Coordinate-Pair missing y-coordinate element");
            return NOTOK;
        }

    }

    vpop ();

    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Coordinate-Pair has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_Pel__Spacing (pe, explicit, len, buffer, parm)
PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    vpush ();
    switch (PE_ID (pe -> pe_class, pe -> pe_id)) {
        case PE_ID (PE_CLASS_CONT, 0):	/* spacing */
            {
                register PE p16;

                vname ("spacing");
                if ((p16 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "spacing bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p16;

                vpush ();
                {
                    register PE p17;

                    if ((p17 = first_member (pe)) != NULLPE) {
                        p16 = p17;

                        {	/* length */
                            register int p18;

                            if (p17 -> pe_class != PE_CLASS_UNIV
                                    || p17 -> pe_form != PE_FORM_PRIM
                                    || p17 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "length bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p17 -> pe_class], p17 -> pe_form, p17 -> pe_id);
                                return NOTOK;
                            }

                            vname ("length");
                            if ((p18 = prim2num (p17)) == NOTOK
                                    && p17 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "length bad integer: %s",
                                        pe_error (p17 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p18);
                        }
                    }
                    else {
                        advise (NULLCP, "spacing missing length element");
                        return NOTOK;
                    }

                }

                {
                    register PE p19;

                    if ((p19 = (pe != p16 ? next_member (pe, p16) : first_member (pe))) != NULLPE) {
                        p16 = p19;

                        {	/* pel-spaces */
                            register int p20;

                            if (p19 -> pe_class != PE_CLASS_UNIV
                                    || p19 -> pe_form != PE_FORM_PRIM
                                    || p19 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "pel-spaces bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p19 -> pe_class], p19 -> pe_form, p19 -> pe_id);
                                return NOTOK;
                            }

                            vname ("pel-spaces");
                            if ((p20 = prim2num (p19)) == NOTOK
                                    && p19 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "pel-spaces bad integer: %s",
                                        pe_error (p19 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p20);
                        }
                    }
                    else {
                        advise (NULLCP, "spacing missing pel-spaces element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "spacing has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 1):	/* null */
            {
                vname ("null");
                vprint ("NULL");
            }
            break;

        default:
            advise (NULLCP, "Pel-Spacing has unknown choice: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
    }
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_Spacing__Ratio (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p21;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Spacing-Ratio bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Spacing-Ratio bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p21 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Spacing-Ratio bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p21;

    vpush ();
    {
        register PE p22;

        if ((p22 = first_member (pe)) != NULLPE) {
            p21 = p22;

            {	/* line-spacing-value */
                register int p23;

                if (p22 -> pe_class != PE_CLASS_UNIV
                        || p22 -> pe_form != PE_FORM_PRIM
                        || p22 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "line-spacing-value bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p22 -> pe_class], p22 -> pe_form, p22 -> pe_id);
                    return NOTOK;
                }

                vname ("line-spacing-value");
                if ((p23 = prim2num (p22)) == NOTOK
                        && p22 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "line-spacing-value bad integer: %s",
                            pe_error (p22 -> pe_errno));
                    return NOTOK;
                }
                vprint ("%d", p23);
            }
        }
        else {
            advise (NULLCP, "Spacing-Ratio missing line-spacing-value element");
            return NOTOK;
        }

    }

    {
        register PE p24;

        if ((p24 = (pe != p21 ? next_member (pe, p21) : first_member (pe))) != NULLPE) {
            p21 = p24;

            {	/* pel-spacing-value */
                register int p25;

                if (p24 -> pe_class != PE_CLASS_UNIV
                        || p24 -> pe_form != PE_FORM_PRIM
                        || p24 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "pel-spacing-value bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p24 -> pe_class], p24 -> pe_form, p24 -> pe_id);
                    return NOTOK;
                }

                vname ("pel-spacing-value");
                if ((p25 = prim2num (p24)) == NOTOK
                        && p24 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "pel-spacing-value bad integer: %s",
                            pe_error (p24 -> pe_errno));
                    return NOTOK;
                }
                vprint ("%d", p25);
            }
        }
        else {
            advise (NULLCP, "Spacing-Ratio missing pel-spacing-value element");
            return NOTOK;
        }

    }

    vpop ();

    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Spacing-Ratio has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR12_Image__Dimensions (pe, explicit, len, buffer, parm)
PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    vpush ();
    switch (PE_ID (pe -> pe_class, pe -> pe_id)) {
        case PE_ID (PE_CLASS_CONT, 0):	/* width-controlled */
            {
                register PE p26;

                vname ("width-controlled");
                if ((p26 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "width-controlled bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p26;

                vpush ();
                {
                    register PE p27;

                    if ((p27 = first_member (pe)) != NULLPE) {
                        p26 = p27;

                        {	/* minimum-width */
                            register int p28;

                            if (p27 -> pe_class != PE_CLASS_UNIV
                                    || p27 -> pe_form != PE_FORM_PRIM
                                    || p27 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "minimum-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p27 -> pe_class], p27 -> pe_form, p27 -> pe_id);
                                return NOTOK;
                            }

                            vname ("minimum-width");
                            if ((p28 = prim2num (p27)) == NOTOK
                                    && p27 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "minimum-width bad integer: %s",
                                        pe_error (p27 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p28);
                        }
                    }
                    else {
                        advise (NULLCP, "width-controlled missing minimum-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p29;

                    if ((p29 = (pe != p26 ? next_member (pe, p26) : first_member (pe))) != NULLPE) {
                        p26 = p29;

                        {	/* preferred-width */
                            register int p30;

                            if (p29 -> pe_class != PE_CLASS_UNIV
                                    || p29 -> pe_form != PE_FORM_PRIM
                                    || p29 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "preferred-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p29 -> pe_class], p29 -> pe_form, p29 -> pe_id);
                                return NOTOK;
                            }

                            vname ("preferred-width");
                            if ((p30 = prim2num (p29)) == NOTOK
                                    && p29 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "preferred-width bad integer: %s",
                                        pe_error (p29 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p30);
                        }
                    }
                    else {
                        advise (NULLCP, "width-controlled missing preferred-width element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "width-controlled has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 1):	/* height-controlled */
            {
                register PE p31;

                vname ("height-controlled");
                if ((p31 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "height-controlled bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p31;

                vpush ();
                {
                    register PE p32;

                    if ((p32 = first_member (pe)) != NULLPE) {
                        p31 = p32;

                        {	/* minimum-height */
                            register int p33;

                            if (p32 -> pe_class != PE_CLASS_UNIV
                                    || p32 -> pe_form != PE_FORM_PRIM
                                    || p32 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "minimum-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p32 -> pe_class], p32 -> pe_form, p32 -> pe_id);
                                return NOTOK;
                            }

                            vname ("minimum-height");
                            if ((p33 = prim2num (p32)) == NOTOK
                                    && p32 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "minimum-height bad integer: %s",
                                        pe_error (p32 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p33);
                        }
                    }
                    else {
                        advise (NULLCP, "height-controlled missing minimum-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p34;

                    if ((p34 = (pe != p31 ? next_member (pe, p31) : first_member (pe))) != NULLPE) {
                        p31 = p34;

                        {	/* preferred-height */
                            register int p35;

                            if (p34 -> pe_class != PE_CLASS_UNIV
                                    || p34 -> pe_form != PE_FORM_PRIM
                                    || p34 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "preferred-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p34 -> pe_class], p34 -> pe_form, p34 -> pe_id);
                                return NOTOK;
                            }

                            vname ("preferred-height");
                            if ((p35 = prim2num (p34)) == NOTOK
                                    && p34 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "preferred-height bad integer: %s",
                                        pe_error (p34 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p35);
                        }
                    }
                    else {
                        advise (NULLCP, "height-controlled missing preferred-height element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "height-controlled has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 2):	/* area-controlled */
            {
                register PE p36;

                vname ("area-controlled");
                if ((p36 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "area-controlled bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p36;

                vpush ();
                {
                    register PE p37;

                    if ((p37 = first_member (pe)) != NULLPE) {
                        p36 = p37;

                        {	/* a-minimum-width */
                            register int p38;

                            if (p37 -> pe_class != PE_CLASS_UNIV
                                    || p37 -> pe_form != PE_FORM_PRIM
                                    || p37 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-minimum-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p37 -> pe_class], p37 -> pe_form, p37 -> pe_id);
                                return NOTOK;
                            }

                            vname ("a-minimum-width");
                            if ((p38 = prim2num (p37)) == NOTOK
                                    && p37 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-minimum-width bad integer: %s",
                                        pe_error (p37 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p38);
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-minimum-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p39;

                    if ((p39 = (pe != p36 ? next_member (pe, p36) : first_member (pe))) != NULLPE) {
                        p36 = p39;

                        {	/* a-preferred-width */
                            register int p40;

                            if (p39 -> pe_class != PE_CLASS_UNIV
                                    || p39 -> pe_form != PE_FORM_PRIM
                                    || p39 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-preferred-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p39 -> pe_class], p39 -> pe_form, p39 -> pe_id);
                                return NOTOK;
                            }

                            vname ("a-preferred-width");
                            if ((p40 = prim2num (p39)) == NOTOK
                                    && p39 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-preferred-width bad integer: %s",
                                        pe_error (p39 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p40);
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-preferred-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p41;

                    if ((p41 = (pe != p36 ? next_member (pe, p36) : first_member (pe))) != NULLPE) {
                        p36 = p41;

                        {	/* a-minimum-height */
                            register int p42;

                            if (p41 -> pe_class != PE_CLASS_UNIV
                                    || p41 -> pe_form != PE_FORM_PRIM
                                    || p41 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-minimum-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p41 -> pe_class], p41 -> pe_form, p41 -> pe_id);
                                return NOTOK;
                            }

                            vname ("a-minimum-height");
                            if ((p42 = prim2num (p41)) == NOTOK
                                    && p41 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-minimum-height bad integer: %s",
                                        pe_error (p41 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p42);
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-minimum-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p43;

                    if ((p43 = (pe != p36 ? next_member (pe, p36) : first_member (pe))) != NULLPE) {
                        p36 = p43;

                        {	/* a-preferred-height */
                            register int p44;

                            if (p43 -> pe_class != PE_CLASS_UNIV
                                    || p43 -> pe_form != PE_FORM_PRIM
                                    || p43 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-preferred-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p43 -> pe_class], p43 -> pe_form, p43 -> pe_id);
                                return NOTOK;
                            }

                            vname ("a-preferred-height");
                            if ((p44 = prim2num (p43)) == NOTOK
                                    && p43 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-preferred-height bad integer: %s",
                                        pe_error (p43 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p44);
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-preferred-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p45;

                    if ((p45 = (pe != p36 ? next_member (pe, p36) : first_member (pe))) != NULLPE) {
                        p36 = p45;

                        {	/* aspect-ratio-flag */
                            register int p46;

                            if (p45 -> pe_class != PE_CLASS_UNIV
                                    || p45 -> pe_form != PE_FORM_PRIM
                                    || p45 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "aspect-ratio-flag bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p45 -> pe_class], p45 -> pe_form, p45 -> pe_id);
                                return NOTOK;
                            }

                            vname ("aspect-ratio-flag");
                            if ((p46 = prim2num (p45)) == NOTOK
                                    && p45 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "aspect-ratio-flag bad integer: %s",
                                        pe_error (p45 -> pe_errno));
                                return NOTOK;
                            }
                            switch (p46) {
                                case 0:	/* fixed */
                                    vprint ("fixed");
                                    break;
                                case 1:	/* variable */
                                    vprint ("variable");
                                    break;
                                default:
                                    advise (NULLCP, "aspect-ratio-flag has unknown component: %d", p46);
                                    return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing aspect-ratio-flag element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 5) {
                    advise (NULLCP, "area-controlled has too many elements(5): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 3):	/* automatic */
            {
                vname ("automatic");
                vprint ("NULL");
            }
            break;

        default:
            advise (NULLCP, "Image-Dimensions has unknown choice: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
    }
    vpop ();

    return OK;
}
