/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISPR15 */
# line 5 "ispr15.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	print_ISPR15_Geometric__Graphics__Attributes (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p0_count = 0;
    register PE p0;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p0 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p0;

    vpush ();
    if (p0 = set_find (pe, PE_CLASS_CONT, 0)) {
        vname ("encoding-announcer");
        if (print_ISPR15_Encoding__Announcer (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 1)) {
        vname ("line-rendition");
        if (print_ISPR15_Line__Rendition (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 2)) {
        vname ("marker-rendition");
        if (print_ISPR15_Marker__Rendition (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 3)) {
        vname ("text-rendition");
        if (print_ISPR15_Text__Rendition (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 4)) {
        vname ("filled-area-rendition");
        if (print_ISPR15_Filled__Area__Rendition (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 5)) {
        vname ("edge-rendition");
        if (print_ISPR15_Edge__Rendition (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 6)) {
        vname ("colour-representations");
        if (print_ISPR15_Colour__Representations (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 7)) {
        vname ("transparency-specification");
        if (print_ISPR15_Transparency__Specification (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 8)) {
        vname ("transformation-specification");
        if (print_ISPR15_Transformation__Specification (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 9)) {
        register PE p1 = p0;

        {	/* region-of-interest TAG PULLUP */
            register PE p2;

            if ((p2 = prim2set (p1)) == NULLPE) {
                advise (NULLCP, "region-of-interest bad region-of-interest: %s",
                        pe_error (p1 -> pe_errno));
                return NOTOK;
            }
            if (p2 -> pe_cardinal != 1) {
                advise (NULLCP, "region-of-interest too many elements for tagged region-of-interest: %d",
                        p2 -> pe_cardinal);
                return NOTOK;
            }
            p1 = first_member (p2);
        }
        {
            vname ("region-of-interest");
            if (print_ISPR15_Region__Of__Interest (p1, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 10)) {
        vname ("picture-orientation");
        if (print_ISPR15_Picture__Orientation (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 11)) {
        register PE p3 = p0;

        {	/* picture-dimensions TAG PULLUP */
            register PE p4;

            if ((p4 = prim2set (p3)) == NULLPE) {
                advise (NULLCP, "picture-dimensions bad picture-dimensions: %s",
                        pe_error (p3 -> pe_errno));
                return NOTOK;
            }
            if (p4 -> pe_cardinal != 1) {
                advise (NULLCP, "picture-dimensions too many elements for tagged picture-dimensions: %d",
                        p4 -> pe_cardinal);
                return NOTOK;
            }
            p3 = first_member (p4);
        }
        {
            vname ("picture-dimensions");
            if (print_ISPR15_Picture__Dimensions (p3, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p0_count ++;
    }
    if (p0_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Encoding__Announcer (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p5;
    int p5_len;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV || pe -> pe_id != PE_PRIM_OCTS) {
            advise (NULLCP, "Encoding-Announcer bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }

    if ((p5 = prim2str (pe, &p5_len)) == NULLCP) {
        advise (NULLCP, "Encoding-Announcer bad octetstring: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p5_len;
    if (buffer)
        *buffer = p5;
    else
        if (p5)
            free (p5);

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Line__Rendition (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p6;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Line-Rendition bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Line-Rendition bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p6 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Line-Rendition bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p6;

    vpush ();
    {
        register PE p7;

        if ((p7 = first_member (pe)) != NULLPE
                && PE_ID (p7 -> pe_class, p7 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p7 = NULLPE;
        if (p7 != NULLPE) {
            p6 = p7;

            {	/* individual-part */
                vname ("individual-part");
                vstring (p7);
            }
        }
    }

    {
        register PE p8;

        if ((p8 = (pe != p6 ? next_member (pe, p6) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p8 -> pe_class, p8 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 1))
            p8 = NULLPE;
        if (p8 != NULLPE) {
            p6 = p8;

            {	/* asf-part */
                register PE p9;

                vname ("asf-part");
                if ((p9 = prim2seq (p8)) == NULLPE) {
                    advise (NULLCP, "asf-part bad sequence: %s",
                            pe_error (p8 -> pe_errno));
                    return NOTOK;
                }
                p8 = p9;

                vpush ();
                {
                    register PE p10;

                    if ((p10 = first_member (p8)) != NULLPE) {
                        p9 = p10;

                        {	/* line-type-asf */
                            vname ("line-type-asf");
                            if (print_ISPR15_ASF__Type (p10, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing line-type-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p11;

                    if ((p11 = (p8 != p9 ? next_member (p8, p9) : first_member (p8))) != NULLPE) {
                        p9 = p11;

                        {	/* line-width-asf */
                            vname ("line-width-asf");
                            if (print_ISPR15_ASF__Type (p11, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing line-width-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p12;

                    if ((p12 = (p8 != p9 ? next_member (p8, p9) : first_member (p8))) != NULLPE) {
                        p9 = p12;

                        {	/* line-colour-asf */
                            vname ("line-colour-asf");
                            if (print_ISPR15_ASF__Type (p12, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing line-colour-asf element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (p8 -> pe_cardinal > 3) {
                    advise (NULLCP, "asf-part has too many elements(3): %d",
                            p8 -> pe_cardinal);
                    return NOTOK;
                }
            }
        }
    }

    {
        register PE p13;

        if ((p13 = (pe != p6 ? next_member (pe, p6) : first_member (pe))) != NULLPE) {
            p6 = p13;

            {	/* bundle-part */
                register PE p14;

                vname ("bundle-part");
                if ((p14 = prim2seq (p13)) == NULLPE) {
                    advise (NULLCP, "bundle-part bad sequence: %s",
                            pe_error (p13 -> pe_errno));
                    return NOTOK;
                }
                p13 = p14;

                vpush ();
                for (p14 = first_member (p13); p14; p14 = next_member (p13, p14)) {
                    register PE p15;

                    if (p14 -> pe_class != PE_CLASS_UNIV
                            || p14 -> pe_form != PE_FORM_CONS
                            || p14 -> pe_id != PE_CONS_SEQ) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p14 -> pe_class], p14 -> pe_form, p14 -> pe_id);
                        return NOTOK;
                    }

                    if ((p15 = prim2seq (p14)) == NULLPE) {
                        advise (NULLCP, "element bad sequence: %s",
                                pe_error (p14 -> pe_errno));
                        return NOTOK;
                    }
                    p14 = p15;

                    vpush ();
                    {
                        register PE p16;

                        if ((p16 = first_member (p14)) != NULLPE) {
                            p15 = p16;

                            {	/* bundle-index */
                                register int p17;

                                if (p16 -> pe_class != PE_CLASS_UNIV
                                        || p16 -> pe_form != PE_FORM_PRIM
                                        || p16 -> pe_id != PE_PRIM_INT) {
                                    advise (NULLCP, "bundle-index bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p16 -> pe_class], p16 -> pe_form, p16 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-index");
                                if ((p17 = prim2num (p16)) == NOTOK
                                        && p16 -> pe_errno != PE_ERR_NONE) {
                                    advise (NULLCP, "bundle-index bad integer: %s",
                                            pe_error (p16 -> pe_errno));
                                    return NOTOK;
                                }
                                vprint ("%d", p17);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-index element");
                            return NOTOK;
                        }

                    }

                    {
                        register PE p18;

                        if ((p18 = (p14 != p15 ? next_member (p14, p15) : first_member (p14))) != NULLPE) {
                            p15 = p18;

                            {	/* bundle-representation */
                                if (p18 -> pe_class != PE_CLASS_UNIV || p18 -> pe_id != PE_PRIM_OCTS) {
                                    advise (NULLCP, "bundle-representation bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p18 -> pe_class], p18 -> pe_form, p18 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-representation");
                                vstring (p18);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-representation element");
                            return NOTOK;
                        }

                    }

                    vpop ();

                    if (p14 -> pe_cardinal > 2) {
                        advise (NULLCP, "element has too many elements(2): %d",
                                p14 -> pe_cardinal);
                        return NOTOK;
                    }
                }
                vpop ();
            }
        }
    }

    vpop ();

    if (pe -> pe_cardinal > 3) {
        advise (NULLCP, "Line-Rendition has too many elements(3): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Marker__Rendition (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p19;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Marker-Rendition bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Marker-Rendition bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p19 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Marker-Rendition bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p19;

    vpush ();
    {
        register PE p20;

        if ((p20 = first_member (pe)) != NULLPE
                && PE_ID (p20 -> pe_class, p20 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p20 = NULLPE;
        if (p20 != NULLPE) {
            p19 = p20;

            {	/* individual-part */
                vname ("individual-part");
                vstring (p20);
            }
        }
    }

    {
        register PE p21;

        if ((p21 = (pe != p19 ? next_member (pe, p19) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p21 -> pe_class, p21 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 1))
            p21 = NULLPE;
        if (p21 != NULLPE) {
            p19 = p21;

            {	/* asf-part */
                register PE p22;

                vname ("asf-part");
                if ((p22 = prim2seq (p21)) == NULLPE) {
                    advise (NULLCP, "asf-part bad sequence: %s",
                            pe_error (p21 -> pe_errno));
                    return NOTOK;
                }
                p21 = p22;

                vpush ();
                {
                    register PE p23;

                    if ((p23 = first_member (p21)) != NULLPE) {
                        p22 = p23;

                        {	/* marker-type-asf */
                            vname ("marker-type-asf");
                            if (print_ISPR15_ASF__Type (p23, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing marker-type-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p24;

                    if ((p24 = (p21 != p22 ? next_member (p21, p22) : first_member (p21))) != NULLPE) {
                        p22 = p24;

                        {	/* marker-width-asf */
                            vname ("marker-width-asf");
                            if (print_ISPR15_ASF__Type (p24, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing marker-width-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p25;

                    if ((p25 = (p21 != p22 ? next_member (p21, p22) : first_member (p21))) != NULLPE) {
                        p22 = p25;

                        {	/* marker-colour-asf */
                            vname ("marker-colour-asf");
                            if (print_ISPR15_ASF__Type (p25, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing marker-colour-asf element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (p21 -> pe_cardinal > 3) {
                    advise (NULLCP, "asf-part has too many elements(3): %d",
                            p21 -> pe_cardinal);
                    return NOTOK;
                }
            }
        }
    }

    {
        register PE p26;

        if ((p26 = (pe != p19 ? next_member (pe, p19) : first_member (pe))) != NULLPE) {
            p19 = p26;

            {	/* bundle-part */
                register PE p27;

                vname ("bundle-part");
                if ((p27 = prim2seq (p26)) == NULLPE) {
                    advise (NULLCP, "bundle-part bad sequence: %s",
                            pe_error (p26 -> pe_errno));
                    return NOTOK;
                }
                p26 = p27;

                vpush ();
                for (p27 = first_member (p26); p27; p27 = next_member (p26, p27)) {
                    register PE p28;

                    if (p27 -> pe_class != PE_CLASS_UNIV
                            || p27 -> pe_form != PE_FORM_CONS
                            || p27 -> pe_id != PE_CONS_SEQ) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p27 -> pe_class], p27 -> pe_form, p27 -> pe_id);
                        return NOTOK;
                    }

                    if ((p28 = prim2seq (p27)) == NULLPE) {
                        advise (NULLCP, "element bad sequence: %s",
                                pe_error (p27 -> pe_errno));
                        return NOTOK;
                    }
                    p27 = p28;

                    vpush ();
                    {
                        register PE p29;

                        if ((p29 = first_member (p27)) != NULLPE) {
                            p28 = p29;

                            {	/* bundle-index */
                                register int p30;

                                if (p29 -> pe_class != PE_CLASS_UNIV
                                        || p29 -> pe_form != PE_FORM_PRIM
                                        || p29 -> pe_id != PE_PRIM_INT) {
                                    advise (NULLCP, "bundle-index bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p29 -> pe_class], p29 -> pe_form, p29 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-index");
                                if ((p30 = prim2num (p29)) == NOTOK
                                        && p29 -> pe_errno != PE_ERR_NONE) {
                                    advise (NULLCP, "bundle-index bad integer: %s",
                                            pe_error (p29 -> pe_errno));
                                    return NOTOK;
                                }
                                vprint ("%d", p30);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-index element");
                            return NOTOK;
                        }

                    }

                    {
                        register PE p31;

                        if ((p31 = (p27 != p28 ? next_member (p27, p28) : first_member (p27))) != NULLPE) {
                            p28 = p31;

                            {	/* bundle-representation */
                                if (p31 -> pe_class != PE_CLASS_UNIV || p31 -> pe_id != PE_PRIM_OCTS) {
                                    advise (NULLCP, "bundle-representation bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p31 -> pe_class], p31 -> pe_form, p31 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-representation");
                                vstring (p31);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-representation element");
                            return NOTOK;
                        }

                    }

                    vpop ();

                    if (p27 -> pe_cardinal > 2) {
                        advise (NULLCP, "element has too many elements(2): %d",
                                p27 -> pe_cardinal);
                        return NOTOK;
                    }
                }
                vpop ();
            }
        }
    }

    vpop ();

    if (pe -> pe_cardinal > 3) {
        advise (NULLCP, "Marker-Rendition has too many elements(3): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Text__Rendition (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p32;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Text-Rendition bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Text-Rendition bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p32 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Text-Rendition bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p32;

    vpush ();
    {
        register PE p33;

        if ((p33 = first_member (pe)) != NULLPE
                && PE_ID (p33 -> pe_class, p33 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p33 = NULLPE;
        if (p33 != NULLPE) {
            p32 = p33;

            {	/* individual-part */
                vname ("individual-part");
                vstring (p33);
            }
        }
    }

    {
        register PE p34;

        if ((p34 = (pe != p32 ? next_member (pe, p32) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p34 -> pe_class, p34 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 1))
            p34 = NULLPE;
        if (p34 != NULLPE) {
            p32 = p34;

            {	/* asf-part */
                register PE p35;

                vname ("asf-part");
                if ((p35 = prim2seq (p34)) == NULLPE) {
                    advise (NULLCP, "asf-part bad sequence: %s",
                            pe_error (p34 -> pe_errno));
                    return NOTOK;
                }
                p34 = p35;

                vpush ();
                {
                    register PE p36;

                    if ((p36 = first_member (p34)) != NULLPE) {
                        p35 = p36;

                        {	/* text-type-asf */
                            vname ("text-type-asf");
                            if (print_ISPR15_ASF__Type (p36, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing text-type-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p37;

                    if ((p37 = (p34 != p35 ? next_member (p34, p35) : first_member (p34))) != NULLPE) {
                        p35 = p37;

                        {	/* text-precision-asf */
                            vname ("text-precision-asf");
                            if (print_ISPR15_ASF__Type (p37, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing text-precision-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p38;

                    if ((p38 = (p34 != p35 ? next_member (p34, p35) : first_member (p34))) != NULLPE) {
                        p35 = p38;

                        {	/* character-expansion-factor-asf */
                            vname ("character-expansion-factor-asf");
                            if (print_ISPR15_ASF__Type (p38, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing character-expansion-factor-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p39;

                    if ((p39 = (p34 != p35 ? next_member (p34, p35) : first_member (p34))) != NULLPE) {
                        p35 = p39;

                        {	/* character-spacing-asf */
                            vname ("character-spacing-asf");
                            if (print_ISPR15_ASF__Type (p39, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing character-spacing-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p40;

                    if ((p40 = (p34 != p35 ? next_member (p34, p35) : first_member (p34))) != NULLPE) {
                        p35 = p40;

                        {	/* text-colour-asf */
                            vname ("text-colour-asf");
                            if (print_ISPR15_ASF__Type (p40, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing text-colour-asf element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (p34 -> pe_cardinal > 5) {
                    advise (NULLCP, "asf-part has too many elements(5): %d",
                            p34 -> pe_cardinal);
                    return NOTOK;
                }
            }
        }
    }

    {
        register PE p41;

        if ((p41 = (pe != p32 ? next_member (pe, p32) : first_member (pe))) != NULLPE) {
            p32 = p41;

            {	/* bundle-part */
                register PE p42;

                vname ("bundle-part");
                if ((p42 = prim2seq (p41)) == NULLPE) {
                    advise (NULLCP, "bundle-part bad sequence: %s",
                            pe_error (p41 -> pe_errno));
                    return NOTOK;
                }
                p41 = p42;

                vpush ();
                for (p42 = first_member (p41); p42; p42 = next_member (p41, p42)) {
                    register PE p43;

                    if (p42 -> pe_class != PE_CLASS_UNIV
                            || p42 -> pe_form != PE_FORM_CONS
                            || p42 -> pe_id != PE_CONS_SEQ) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p42 -> pe_class], p42 -> pe_form, p42 -> pe_id);
                        return NOTOK;
                    }

                    if ((p43 = prim2seq (p42)) == NULLPE) {
                        advise (NULLCP, "element bad sequence: %s",
                                pe_error (p42 -> pe_errno));
                        return NOTOK;
                    }
                    p42 = p43;

                    vpush ();
                    {
                        register PE p44;

                        if ((p44 = first_member (p42)) != NULLPE) {
                            p43 = p44;

                            {	/* bundle-index */
                                register int p45;

                                if (p44 -> pe_class != PE_CLASS_UNIV
                                        || p44 -> pe_form != PE_FORM_PRIM
                                        || p44 -> pe_id != PE_PRIM_INT) {
                                    advise (NULLCP, "bundle-index bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p44 -> pe_class], p44 -> pe_form, p44 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-index");
                                if ((p45 = prim2num (p44)) == NOTOK
                                        && p44 -> pe_errno != PE_ERR_NONE) {
                                    advise (NULLCP, "bundle-index bad integer: %s",
                                            pe_error (p44 -> pe_errno));
                                    return NOTOK;
                                }
                                vprint ("%d", p45);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-index element");
                            return NOTOK;
                        }

                    }

                    {
                        register PE p46;

                        if ((p46 = (p42 != p43 ? next_member (p42, p43) : first_member (p42))) != NULLPE) {
                            p43 = p46;

                            {	/* bundle-representation */
                                if (p46 -> pe_class != PE_CLASS_UNIV || p46 -> pe_id != PE_PRIM_OCTS) {
                                    advise (NULLCP, "bundle-representation bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p46 -> pe_class], p46 -> pe_form, p46 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-representation");
                                vstring (p46);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-representation element");
                            return NOTOK;
                        }

                    }

                    vpop ();

                    if (p42 -> pe_cardinal > 2) {
                        advise (NULLCP, "element has too many elements(2): %d",
                                p42 -> pe_cardinal);
                        return NOTOK;
                    }
                }
                vpop ();
            }
        }
    }

    vpop ();

    if (pe -> pe_cardinal > 3) {
        advise (NULLCP, "Text-Rendition has too many elements(3): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Filled__Area__Rendition (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p47;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Filled-Area-Rendition bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Filled-Area-Rendition bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p47 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Filled-Area-Rendition bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p47;

    vpush ();
    {
        register PE p48;

        if ((p48 = first_member (pe)) != NULLPE
                && PE_ID (p48 -> pe_class, p48 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p48 = NULLPE;
        if (p48 != NULLPE) {
            p47 = p48;

            {	/* individual-part */
                vname ("individual-part");
                vstring (p48);
            }
        }
    }

    {
        register PE p49;

        if ((p49 = (pe != p47 ? next_member (pe, p47) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p49 -> pe_class, p49 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 1))
            p49 = NULLPE;
        if (p49 != NULLPE) {
            p47 = p49;

            {	/* pattern-table-part */
                register PE p50;

                vname ("pattern-table-part");
                if ((p50 = prim2seq (p49)) == NULLPE) {
                    advise (NULLCP, "pattern-table-part bad sequence: %s",
                            pe_error (p49 -> pe_errno));
                    return NOTOK;
                }
                p49 = p50;

                vpush ();
                for (p50 = first_member (p49); p50; p50 = next_member (p49, p50)) {
                    if (p50 -> pe_class != PE_CLASS_UNIV || p50 -> pe_id != PE_PRIM_OCTS) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p50 -> pe_class], p50 -> pe_form, p50 -> pe_id);
                        return NOTOK;
                    }

                    vstring (p50);
                }
                vpop ();
            }
        }
    }

    {
        register PE p51;

        if ((p51 = (pe != p47 ? next_member (pe, p47) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p51 -> pe_class, p51 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 2))
            p51 = NULLPE;
        if (p51 != NULLPE) {
            p47 = p51;

            {	/* asf-part */
                register PE p52;

                vname ("asf-part");
                if ((p52 = prim2seq (p51)) == NULLPE) {
                    advise (NULLCP, "asf-part bad sequence: %s",
                            pe_error (p51 -> pe_errno));
                    return NOTOK;
                }
                p51 = p52;

                vpush ();
                {
                    register PE p53;

                    if ((p53 = first_member (p51)) != NULLPE) {
                        p52 = p53;

                        {	/* interior-style-asf */
                            vname ("interior-style-asf");
                            if (print_ISPR15_ASF__Type (p53, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing interior-style-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p54;

                    if ((p54 = (p51 != p52 ? next_member (p51, p52) : first_member (p51))) != NULLPE) {
                        p52 = p54;

                        {	/* fill-colour-asf */
                            vname ("fill-colour-asf");
                            if (print_ISPR15_ASF__Type (p54, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing fill-colour-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p55;

                    if ((p55 = (p51 != p52 ? next_member (p51, p52) : first_member (p51))) != NULLPE) {
                        p52 = p55;

                        {	/* hatch-index-asf */
                            vname ("hatch-index-asf");
                            if (print_ISPR15_ASF__Type (p55, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing hatch-index-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p56;

                    if ((p56 = (p51 != p52 ? next_member (p51, p52) : first_member (p51))) != NULLPE) {
                        p52 = p56;

                        {	/* pattern-index-asf */
                            vname ("pattern-index-asf");
                            if (print_ISPR15_ASF__Type (p56, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing pattern-index-asf element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (p51 -> pe_cardinal > 4) {
                    advise (NULLCP, "asf-part has too many elements(4): %d",
                            p51 -> pe_cardinal);
                    return NOTOK;
                }
            }
        }
    }

    {
        register PE p57;

        if ((p57 = (pe != p47 ? next_member (pe, p47) : first_member (pe))) != NULLPE) {
            p47 = p57;

            {	/* bundle-part */
                register PE p58;

                vname ("bundle-part");
                if ((p58 = prim2seq (p57)) == NULLPE) {
                    advise (NULLCP, "bundle-part bad sequence: %s",
                            pe_error (p57 -> pe_errno));
                    return NOTOK;
                }
                p57 = p58;

                vpush ();
                for (p58 = first_member (p57); p58; p58 = next_member (p57, p58)) {
                    register PE p59;

                    if (p58 -> pe_class != PE_CLASS_UNIV
                            || p58 -> pe_form != PE_FORM_CONS
                            || p58 -> pe_id != PE_CONS_SEQ) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p58 -> pe_class], p58 -> pe_form, p58 -> pe_id);
                        return NOTOK;
                    }

                    if ((p59 = prim2seq (p58)) == NULLPE) {
                        advise (NULLCP, "element bad sequence: %s",
                                pe_error (p58 -> pe_errno));
                        return NOTOK;
                    }
                    p58 = p59;

                    vpush ();
                    {
                        register PE p60;

                        if ((p60 = first_member (p58)) != NULLPE) {
                            p59 = p60;

                            {	/* bundle-index */
                                register int p61;

                                if (p60 -> pe_class != PE_CLASS_UNIV
                                        || p60 -> pe_form != PE_FORM_PRIM
                                        || p60 -> pe_id != PE_PRIM_INT) {
                                    advise (NULLCP, "bundle-index bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p60 -> pe_class], p60 -> pe_form, p60 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-index");
                                if ((p61 = prim2num (p60)) == NOTOK
                                        && p60 -> pe_errno != PE_ERR_NONE) {
                                    advise (NULLCP, "bundle-index bad integer: %s",
                                            pe_error (p60 -> pe_errno));
                                    return NOTOK;
                                }
                                vprint ("%d", p61);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-index element");
                            return NOTOK;
                        }

                    }

                    {
                        register PE p62;

                        if ((p62 = (p58 != p59 ? next_member (p58, p59) : first_member (p58))) != NULLPE) {
                            p59 = p62;

                            {	/* bundle-representation */
                                if (p62 -> pe_class != PE_CLASS_UNIV || p62 -> pe_id != PE_PRIM_OCTS) {
                                    advise (NULLCP, "bundle-representation bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p62 -> pe_class], p62 -> pe_form, p62 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-representation");
                                vstring (p62);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-representation element");
                            return NOTOK;
                        }

                    }

                    vpop ();

                    if (p58 -> pe_cardinal > 2) {
                        advise (NULLCP, "element has too many elements(2): %d",
                                p58 -> pe_cardinal);
                        return NOTOK;
                    }
                }
                vpop ();
            }
        }
    }

    vpop ();

    if (pe -> pe_cardinal > 4) {
        advise (NULLCP, "Filled-Area-Rendition has too many elements(4): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Edge__Rendition (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p63;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Edge-Rendition bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Edge-Rendition bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p63 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Edge-Rendition bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p63;

    vpush ();
    {
        register PE p64;

        if ((p64 = first_member (pe)) != NULLPE
                && PE_ID (p64 -> pe_class, p64 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p64 = NULLPE;
        if (p64 != NULLPE) {
            p63 = p64;

            {	/* individual-part */
                vname ("individual-part");
                vstring (p64);
            }
        }
    }

    {
        register PE p65;

        if ((p65 = (pe != p63 ? next_member (pe, p63) : first_member (pe))) 
                    != NULLPE
                && PE_ID (p65 -> pe_class, p65 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 1))
            p65 = NULLPE;
        if (p65 != NULLPE) {
            p63 = p65;

            {	/* asf-part */
                register PE p66;

                vname ("asf-part");
                if ((p66 = prim2seq (p65)) == NULLPE) {
                    advise (NULLCP, "asf-part bad sequence: %s",
                            pe_error (p65 -> pe_errno));
                    return NOTOK;
                }
                p65 = p66;

                vpush ();
                {
                    register PE p67;

                    if ((p67 = first_member (p65)) != NULLPE) {
                        p66 = p67;

                        {	/* edge-type-asf */
                            vname ("edge-type-asf");
                            if (print_ISPR15_ASF__Type (p67, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing edge-type-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p68;

                    if ((p68 = (p65 != p66 ? next_member (p65, p66) : first_member (p65))) != NULLPE) {
                        p66 = p68;

                        {	/* edge-width-asf */
                            vname ("edge-width-asf");
                            if (print_ISPR15_ASF__Type (p68, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing edge-width-asf element");
                        return NOTOK;
                    }

                }

                {
                    register PE p69;

                    if ((p69 = (p65 != p66 ? next_member (p65, p66) : first_member (p65))) != NULLPE) {
                        p66 = p69;

                        {	/* edge-colour-asf */
                            vname ("edge-colour-asf");
                            if (print_ISPR15_ASF__Type (p69, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "asf-part missing edge-colour-asf element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (p65 -> pe_cardinal > 3) {
                    advise (NULLCP, "asf-part has too many elements(3): %d",
                            p65 -> pe_cardinal);
                    return NOTOK;
                }
            }
        }
    }

    {
        register PE p70;

        if ((p70 = (pe != p63 ? next_member (pe, p63) : first_member (pe))) != NULLPE) {
            p63 = p70;

            {	/* bundle-part */
                register PE p71;

                vname ("bundle-part");
                if ((p71 = prim2seq (p70)) == NULLPE) {
                    advise (NULLCP, "bundle-part bad sequence: %s",
                            pe_error (p70 -> pe_errno));
                    return NOTOK;
                }
                p70 = p71;

                vpush ();
                for (p71 = first_member (p70); p71; p71 = next_member (p70, p71)) {
                    register PE p72;

                    if (p71 -> pe_class != PE_CLASS_UNIV
                            || p71 -> pe_form != PE_FORM_CONS
                            || p71 -> pe_id != PE_CONS_SEQ) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p71 -> pe_class], p71 -> pe_form, p71 -> pe_id);
                        return NOTOK;
                    }

                    if ((p72 = prim2seq (p71)) == NULLPE) {
                        advise (NULLCP, "element bad sequence: %s",
                                pe_error (p71 -> pe_errno));
                        return NOTOK;
                    }
                    p71 = p72;

                    vpush ();
                    {
                        register PE p73;

                        if ((p73 = first_member (p71)) != NULLPE) {
                            p72 = p73;

                            {	/* bundle-index */
                                register int p74;

                                if (p73 -> pe_class != PE_CLASS_UNIV
                                        || p73 -> pe_form != PE_FORM_PRIM
                                        || p73 -> pe_id != PE_PRIM_INT) {
                                    advise (NULLCP, "bundle-index bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p73 -> pe_class], p73 -> pe_form, p73 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-index");
                                if ((p74 = prim2num (p73)) == NOTOK
                                        && p73 -> pe_errno != PE_ERR_NONE) {
                                    advise (NULLCP, "bundle-index bad integer: %s",
                                            pe_error (p73 -> pe_errno));
                                    return NOTOK;
                                }
                                vprint ("%d", p74);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-index element");
                            return NOTOK;
                        }

                    }

                    {
                        register PE p75;

                        if ((p75 = (p71 != p72 ? next_member (p71, p72) : first_member (p71))) != NULLPE) {
                            p72 = p75;

                            {	/* bundle-representation */
                                if (p75 -> pe_class != PE_CLASS_UNIV || p75 -> pe_id != PE_PRIM_OCTS) {
                                    advise (NULLCP, "bundle-representation bad class/form/id: %s/%d/0x%x",
                                            pe_classlist[p75 -> pe_class], p75 -> pe_form, p75 -> pe_id);
                                    return NOTOK;
                                }

                                vname ("bundle-representation");
                                vstring (p75);
                            }
                        }
                        else {
                            advise (NULLCP, "element missing bundle-representation element");
                            return NOTOK;
                        }

                    }

                    vpop ();

                    if (p71 -> pe_cardinal > 2) {
                        advise (NULLCP, "element has too many elements(2): %d",
                                p71 -> pe_cardinal);
                        return NOTOK;
                    }
                }
                vpop ();
            }
        }
    }

    vpop ();

    if (pe -> pe_cardinal > 3) {
        advise (NULLCP, "Edge-Rendition has too many elements(3): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_ASF__Type (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p76;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "ASF-Type bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "ASF-Type bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p76 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "ASF-Type bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p76;
    switch (p76) {
        case 0:	/* bundled */
            vprint ("bundled");
            break;
        case 1:	/* individual */
            vprint ("individual");
            break;
        default:
            advise (NULLCP, "ASF-Type has unknown component: %d", p76);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Colour__Representations (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p77;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Colour-Representations bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Colour-Representations bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p77 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Colour-Representations bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p77;

    vpush ();
    {
        register PE p78;

        if ((p78 = first_member (pe)) != NULLPE
                && PE_ID (p78 -> pe_class, p78 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p78 = NULLPE;
        if (p78 != NULLPE) {
            p77 = p78;

            {	/* background-colour */
                vname ("background-colour");
                vstring (p78);
            }
        }
    }

    {
        register PE p79;

        if ((p79 = (pe != p77 ? next_member (pe, p77) : first_member (pe))) != NULLPE) {
            p77 = p79;

            {	/* colour-table-part */
                register PE p80;

                vname ("colour-table-part");
                if ((p80 = prim2seq (p79)) == NULLPE) {
                    advise (NULLCP, "colour-table-part bad sequence: %s",
                            pe_error (p79 -> pe_errno));
                    return NOTOK;
                }
                p79 = p80;

                vpush ();
                for (p80 = first_member (p79); p80; p80 = next_member (p79, p80)) {
                    if (p80 -> pe_class != PE_CLASS_UNIV || p80 -> pe_id != PE_PRIM_OCTS) {
                        advise (NULLCP, "element bad class/form/id: %s/%d/0x%x",
                                pe_classlist[p80 -> pe_class], p80 -> pe_form, p80 -> pe_id);
                        return NOTOK;
                    }

                    vstring (p80);
                }
                vpop ();
            }
        }
    }

    vpop ();

    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Colour-Representations has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Transparency__Specification (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p81;
    int p81_len;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV || pe -> pe_id != PE_PRIM_OCTS) {
            advise (NULLCP, "Transparency-Specification bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }

    if ((p81 = prim2str (pe, &p81_len)) == NULLCP) {
        advise (NULLCP, "Transparency-Specification bad octetstring: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p81_len;
    if (buffer)
        *buffer = p81;
    else
        if (p81)
            free (p81);

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Transformation__Specification (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p82;
    int p82_len;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV || pe -> pe_id != PE_PRIM_OCTS) {
            advise (NULLCP, "Transformation-Specification bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }

    if ((p82 = prim2str (pe, &p82_len)) == NULLCP) {
        advise (NULLCP, "Transformation-Specification bad octetstring: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p82_len;
    if (buffer)
        *buffer = p82;
    else
        if (p82)
            free (p82);

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Region__Of__Interest (pe, explicit, len, buffer, parm)
PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    vpush ();
    switch (PE_ID (pe -> pe_class, pe -> pe_id)) {
        case PE_ID (PE_CLASS_CONT, 0):	/* automatic */
            {
                vname ("automatic");
                vprint ("NULL");
            }
            break;
        case PE_ID (PE_CLASS_CONT, 1):	/* rectangle */
            {
                register PE p83;

                vname ("rectangle");
                if ((p83 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "rectangle bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p83;

                vpush ();
                {
                    register PE p84;

                    if ((p84 = first_member (pe)) != NULLPE) {
                        p83 = p84;

                        {
                            if (print_ISPR15_VDC__Pair (p84, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "rectangle missing element");
                        return NOTOK;
                    }

                }

                {
                    register PE p85;

                    if ((p85 = (pe != p83 ? next_member (pe, p83) : first_member (pe))) != NULLPE) {
                        p83 = p85;

                        {
                            if (print_ISPR15_VDC__Pair (p85, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                                return NOTOK;
                        }
                    }
                    else {
                        advise (NULLCP, "rectangle missing element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "rectangle has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;

        default:
            advise (NULLCP, "Region-Of-Interest has unknown choice: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
    }
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_VDC__Pair (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register char *p86;
    int p86_len;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV || pe -> pe_id != PE_PRIM_OCTS) {
            advise (NULLCP, "VDC-Pair bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }

    if ((p86 = prim2str (pe, &p86_len)) == NULLCP) {
        advise (NULLCP, "VDC-Pair bad octetstring: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    vstring (pe);
    if (len)
        *len = p86_len;
    if (buffer)
        *buffer = p86;
    else
        if (p86)
            free (p86);

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Picture__Orientation (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    if (print_ISPR9_One__Of__Four__Angles (pe, explicit, len, buffer, NullParm) == NOTOK)
        return NOTOK;

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_One__Of__Four__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p87;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Four-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Four-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p87 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Four-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p87;
    switch (p87) {
        case 0:	/* d0 */
            vprint ("d0");
            break;
        case 1:	/* d90 */
            vprint ("d90");
            break;
        case 2:	/* d180 */
            vprint ("d180");
            break;
        case 3:	/* d270 */
            vprint ("d270");
            break;
        default:
            advise (NULLCP, "One-Of-Four-Angles has unknown component: %d", p87);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Picture__Dimensions (pe, explicit, len, buffer, parm)
PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    vpush ();
    switch (PE_ID (pe -> pe_class, pe -> pe_id)) {
        case PE_ID (PE_CLASS_CONT, 0):	/* picture-width */
            {
                register PE p88;

                vname ("picture-width");
                if ((p88 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "picture-width bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p88;

                vpush ();
                {
                    register PE p89;

                    if ((p89 = first_member (pe)) != NULLPE) {
                        p88 = p89;

                        {	/* w-mimimum-width */
                            register int p90;

                            if (p89 -> pe_class != PE_CLASS_UNIV
                                    || p89 -> pe_form != PE_FORM_PRIM
                                    || p89 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "w-mimimum-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p89 -> pe_class], p89 -> pe_form, p89 -> pe_id);
                                return NOTOK;
                            }

                            vname ("w-mimimum-width");
                            if ((p90 = prim2num (p89)) == NOTOK
                                    && p89 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "w-mimimum-width bad integer: %s",
                                        pe_error (p89 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p90);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-width missing w-mimimum-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p91;

                    if ((p91 = (pe != p88 ? next_member (pe, p88) : first_member (pe))) != NULLPE) {
                        p88 = p91;

                        {	/* w-preferred-width */
                            register int p92;

                            if (p91 -> pe_class != PE_CLASS_UNIV
                                    || p91 -> pe_form != PE_FORM_PRIM
                                    || p91 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "w-preferred-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p91 -> pe_class], p91 -> pe_form, p91 -> pe_id);
                                return NOTOK;
                            }

                            vname ("w-preferred-width");
                            if ((p92 = prim2num (p91)) == NOTOK
                                    && p91 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "w-preferred-width bad integer: %s",
                                        pe_error (p91 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p92);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-width missing w-preferred-width element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "picture-width has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 1):	/* picture-height */
            {
                register PE p93;

                vname ("picture-height");
                if ((p93 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "picture-height bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p93;

                vpush ();
                {
                    register PE p94;

                    if ((p94 = first_member (pe)) != NULLPE) {
                        p93 = p94;

                        {	/* h-mimimum-height */
                            register int p95;

                            if (p94 -> pe_class != PE_CLASS_UNIV
                                    || p94 -> pe_form != PE_FORM_PRIM
                                    || p94 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "h-mimimum-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p94 -> pe_class], p94 -> pe_form, p94 -> pe_id);
                                return NOTOK;
                            }

                            vname ("h-mimimum-height");
                            if ((p95 = prim2num (p94)) == NOTOK
                                    && p94 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "h-mimimum-height bad integer: %s",
                                        pe_error (p94 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p95);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-height missing h-mimimum-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p96;

                    if ((p96 = (pe != p93 ? next_member (pe, p93) : first_member (pe))) != NULLPE) {
                        p93 = p96;

                        {	/* h-preferred-height */
                            register int p97;

                            if (p96 -> pe_class != PE_CLASS_UNIV
                                    || p96 -> pe_form != PE_FORM_PRIM
                                    || p96 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "h-preferred-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p96 -> pe_class], p96 -> pe_form, p96 -> pe_id);
                                return NOTOK;
                            }

                            vname ("h-preferred-height");
                            if ((p97 = prim2num (p96)) == NOTOK
                                    && p96 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "h-preferred-height bad integer: %s",
                                        pe_error (p96 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p97);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-height missing h-preferred-height element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "picture-height has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 2):	/* picture-size */
            {
                register PE p98;

                vname ("picture-size");
                if ((p98 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "picture-size bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p98;

                vpush ();
                {
                    register PE p99;

                    if ((p99 = first_member (pe)) != NULLPE) {
                        p98 = p99;

                        {	/* s-mimimum-width */
                            register int p100;

                            if (p99 -> pe_class != PE_CLASS_UNIV
                                    || p99 -> pe_form != PE_FORM_PRIM
                                    || p99 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "s-mimimum-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p99 -> pe_class], p99 -> pe_form, p99 -> pe_id);
                                return NOTOK;
                            }

                            vname ("s-mimimum-width");
                            if ((p100 = prim2num (p99)) == NOTOK
                                    && p99 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "s-mimimum-width bad integer: %s",
                                        pe_error (p99 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p100);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-size missing s-mimimum-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p101;

                    if ((p101 = (pe != p98 ? next_member (pe, p98) : first_member (pe))) != NULLPE) {
                        p98 = p101;

                        {	/* s-preferred-width */
                            register int p102;

                            if (p101 -> pe_class != PE_CLASS_UNIV
                                    || p101 -> pe_form != PE_FORM_PRIM
                                    || p101 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "s-preferred-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p101 -> pe_class], p101 -> pe_form, p101 -> pe_id);
                                return NOTOK;
                            }

                            vname ("s-preferred-width");
                            if ((p102 = prim2num (p101)) == NOTOK
                                    && p101 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "s-preferred-width bad integer: %s",
                                        pe_error (p101 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p102);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-size missing s-preferred-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p103;

                    if ((p103 = (pe != p98 ? next_member (pe, p98) : first_member (pe))) != NULLPE) {
                        p98 = p103;

                        {	/* s-mimimum-height */
                            register int p104;

                            if (p103 -> pe_class != PE_CLASS_UNIV
                                    || p103 -> pe_form != PE_FORM_PRIM
                                    || p103 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "s-mimimum-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p103 -> pe_class], p103 -> pe_form, p103 -> pe_id);
                                return NOTOK;
                            }

                            vname ("s-mimimum-height");
                            if ((p104 = prim2num (p103)) == NOTOK
                                    && p103 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "s-mimimum-height bad integer: %s",
                                        pe_error (p103 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p104);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-size missing s-mimimum-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p105;

                    if ((p105 = (pe != p98 ? next_member (pe, p98) : first_member (pe))) != NULLPE) {
                        p98 = p105;

                        {	/* s-preferred-height */
                            register int p106;

                            if (p105 -> pe_class != PE_CLASS_UNIV
                                    || p105 -> pe_form != PE_FORM_PRIM
                                    || p105 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "s-preferred-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p105 -> pe_class], p105 -> pe_form, p105 -> pe_id);
                                return NOTOK;
                            }

                            vname ("s-preferred-height");
                            if ((p106 = prim2num (p105)) == NOTOK
                                    && p105 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "s-preferred-height bad integer: %s",
                                        pe_error (p105 -> pe_errno));
                                return NOTOK;
                            }
                            vprint ("%d", p106);
                        }
                    }
                    else {
                        advise (NULLCP, "picture-size missing s-preferred-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p107;

                    if ((p107 = (pe != p98 ? next_member (pe, p98) : first_member (pe))) != NULLPE) {
                        p98 = p107;

                        {	/* s-aspect-ratio-flag */
                            register int p108;

                            if (p107 -> pe_class != PE_CLASS_UNIV
                                    || p107 -> pe_form != PE_FORM_PRIM
                                    || p107 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "s-aspect-ratio-flag bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p107 -> pe_class], p107 -> pe_form, p107 -> pe_id);
                                return NOTOK;
                            }

                            vname ("s-aspect-ratio-flag");
                            if ((p108 = prim2num (p107)) == NOTOK
                                    && p107 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "s-aspect-ratio-flag bad integer: %s",
                                        pe_error (p107 -> pe_errno));
                                return NOTOK;
                            }
                            switch (p108) {
                                case 0:	/* fixed */
                                    vprint ("fixed");
                                    break;
                                case 1:	/* variable */
                                    vprint ("variable");
                                    break;
                                default:
                                    advise (NULLCP, "s-aspect-ratio-flag has unknown component: %d", p108);
                                    return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "picture-size missing s-aspect-ratio-flag element");
                        return NOTOK;
                    }

                }

                vpop ();

                if (pe -> pe_cardinal > 5) {
                    advise (NULLCP, "picture-size has too many elements(5): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 3):	/* automatic */
            {
                vname ("automatic");
                vprint ("NULL");
            }
            break;

        default:
            advise (NULLCP, "Picture-Dimensions has unknown choice: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
    }
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR15_Geo__Gr__Content__Defaults (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p109_count = 0;
    register PE p109;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p109 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p109;

    vpush ();
    if (p109 = set_find (pe, PE_CLASS_CONT, 0)) {
        vname ("encoding-announcer");
        if (print_ISPR15_Encoding__Announcer (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 1)) {
        vname ("line-rendition");
        if (print_ISPR15_Line__Rendition (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 2)) {
        vname ("marker-rendition");
        if (print_ISPR15_Marker__Rendition (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 3)) {
        vname ("text-rendition");
        if (print_ISPR15_Text__Rendition (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 4)) {
        vname ("filled-area-rendition");
        if (print_ISPR15_Filled__Area__Rendition (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 5)) {
        vname ("edge-rendition");
        if (print_ISPR15_Edge__Rendition (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 6)) {
        vname ("colour-representations");
        if (print_ISPR15_Colour__Representations (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 7)) {
        vname ("transparency-specification");
        if (print_ISPR15_Transparency__Specification (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 8)) {
        vname ("transformation-specification");
        if (print_ISPR15_Transformation__Specification (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 9)) {
        register PE p110 = p109;

        {	/* region-of-interest TAG PULLUP */
            register PE p111;

            if ((p111 = prim2set (p110)) == NULLPE) {
                advise (NULLCP, "region-of-interest bad region-of-interest: %s",
                        pe_error (p110 -> pe_errno));
                return NOTOK;
            }
            if (p111 -> pe_cardinal != 1) {
                advise (NULLCP, "region-of-interest too many elements for tagged region-of-interest: %d",
                        p111 -> pe_cardinal);
                return NOTOK;
            }
            p110 = first_member (p111);
        }
        {
            vname ("region-of-interest");
            if (print_ISPR15_Region__Of__Interest (p110, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 10)) {
        vname ("picture-orientation");
        if (print_ISPR15_Picture__Orientation (p109, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p109_count ++;
    }
    if (p109 = set_find (pe, PE_CLASS_CONT, 11)) {
        register PE p112 = p109;

        {	/* picture-dimensions TAG PULLUP */
            register PE p113;

            if ((p113 = prim2set (p112)) == NULLPE) {
                advise (NULLCP, "picture-dimensions bad picture-dimensions: %s",
                        pe_error (p112 -> pe_errno));
                return NOTOK;
            }
            if (p113 -> pe_cardinal != 1) {
                advise (NULLCP, "picture-dimensions too many elements for tagged picture-dimensions: %d",
                        p113 -> pe_cardinal);
                return NOTOK;
            }
            p112 = first_member (p113);
        }
        {
            vname ("picture-dimensions");
            if (print_ISPR15_Picture__Dimensions (p112, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p109_count ++;
    }
    if (p109_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}
