/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISPR9 */
# line 5 "ispr9.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	print_ISPR9_Character__Attributes (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p0_count = 0;
    register PE p0;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Character-Attributes bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Character-Attributes bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p0 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Character-Attributes bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p0;

    vpush ();
    if (p0 = set_find (pe, PE_CLASS_CONT, 0)) {
        vname ("character-path");
        if (print_ISPR9_One__Of__Four__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 1)) {
        vname ("line-progression");
        if (print_ISPR9_One__Of__Two__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 2)) {
        vname ("character-orientation");
        if (print_ISPR9_One__Of__Four__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 3)) {
        vname ("initial-offset");
        if (print_ISPR4_Measure__Pair (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 6)) {
        register int p1;

        vname ("character-spacing");
        if ((p1 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "character-spacing bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p1);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 7)) {
        register int p2;

        vname ("line-spacing");
        if ((p2 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "line-spacing bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p2);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 8)) {
        vname ("alignment");
        if (print_ISPR9_Alignment (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 9)) {
        vname ("line-layout-table");
        if (print_ISPR9_Layout__Table (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 10)) {
        vname ("graphic-rendition");
        if (print_ISPR9_Graphic__Rendition (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 11)) {
        vname ("formatting-indicator");
        if (print_ISPR9_Formatting__Indicator (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 12)) {
        vname ("charcter-fonts");
        if (print_ISPR9_Character__Fonts (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 13)) {
        register int p3;

        vname ("graphic-char-subrepertoire");
        if ((p3 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "graphic-char-subrepertoire bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p3);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 14)) {
        vname ("itemisation");
        if (print_ISPR9_Itemisation (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 15)) {
        register int p4;

        vname ("widow-size");
        if ((p4 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "widow-size bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p4);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 16)) {
        register int p5;

        vname ("orphan-size");
        if ((p5 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "orphan-size bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p5);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 17)) {
        vname ("graphic-character-sets");
        vstring (p0);
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 19)) {
        register int p6;

        vname ("indentation");
        if ((p6 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "indentation bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p6);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 20)) {
        vname ("kerning-offset");
        if (print_ISPR9_Kerning__Offset (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 21)) {
        vname ("proportional-line-spacing");
        if (print_ISPR9_Proportional__Line__Spacing (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 22)) {
        vname ("pairwise-kerning");
        if (print_ISPR9_Pairwise__Kerning (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 23)) {
        register int p7;

        vname ("first-line-offset");
        if ((p7 = prim2num (p0)) == NOTOK
                && p0 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "first-line-offset bad integer: %s",
                    pe_error (p0 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p7);
        p0_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p0 = set_find (pe, PE_CLASS_CONT, 24)) {
        vname ("code-extension-announcers");
        vstring (p0);
        p0_count ++;
    }
    if (p0_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_One__Of__Four__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p8;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Four-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Four-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p8 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Four-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p8;
    switch (p8) {
        case 0:	/* d0 */
            vprint ("d0");
            break;
        case 1:	/* d90 */
            vprint ("d90");
            break;
        case 2:	/* d180 */
            vprint ("d180");
            break;
        case 3:	/* d270 */
            vprint ("d270");
            break;
        default:
            advise (NULLCP, "One-Of-Four-Angles has unknown component: %d", p8);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_One__Of__Two__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p9;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Two-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Two-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p9 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Two-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p9;
    switch (p9) {
        case 1:	/* d90 */
            vprint ("d90");
            break;
        case 3:	/* d270 */
            vprint ("d270");
            break;
        default:
            advise (NULLCP, "One-Of-Two-Angles has unknown component: %d", p9);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Alignment (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p10;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Alignment bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Alignment bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p10 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Alignment bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p10;
    switch (p10) {
        case 0:	/* start-aligned */
            vprint ("start-aligned");
            break;
        case 1:	/* end-aligned */
            vprint ("end-aligned");
            break;
        case 2:	/* centred */
            vprint ("centred");
            break;
        case 3:	/* justified */
            vprint ("justified");
            break;
        default:
            advise (NULLCP, "Alignment has unknown component: %d", p10);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Layout__Table (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p11;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Layout-Table bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Layout-Table bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p11 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Layout-Table bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p11;

    vpush ();
    for (p11 = first_member (pe); p11; p11 = next_member (pe, p11)) {
        if (print_ISPR9_Tabulation__Stop (p11, 1, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
    }
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Tabulation__Stop (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p12_count = 0;
    register PE p12;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Tabulation-Stop bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Tabulation-Stop bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p12 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Tabulation-Stop bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p12;

    vpush ();
    if (p12 = set_find (pe, PE_CLASS_CONT, 0)) {
        vname ("tabulation-reference");
        if (print_UNIV_NumericString (p12, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p12_count ++;
    }
    else {
        advise (NULLCP, "tabulation-reference missing tabulation-reference member");
        return NOTOK;
    }

    if (p12 = set_find (pe, PE_CLASS_CONT, 1)) {
        register int p13;

        vname ("tabulation-position");
        if ((p13 = prim2num (p12)) == NOTOK
                && p12 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "tabulation-position bad integer: %s",
                    pe_error (p12 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p13);
        p12_count ++;
    }
    else {
        advise (NULLCP, "tabulation-position missing tabulation-position member");
        return NOTOK;
    }

    if (p12 = set_find (pe, PE_CLASS_CONT, 2)) {
        register int p14;

        vname ("alignment");
        if ((p14 = prim2num (p12)) == NOTOK
                && p12 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "alignment bad integer: %s",
                    pe_error (p12 -> pe_errno));
            return NOTOK;
        }
        switch (p14) {
            case 0:	/* start-aligned */
                vprint ("start-aligned");
                break;
            case 1:	/* end-aligned */
                vprint ("end-aligned");
                break;
            case 2:	/* centred-1 */
                vprint ("centred-1");
                break;
            case 3:	/* round-aligned */
                vprint ("round-aligned");
                break;
            default:
                advise (NULLCP, "alignment has unknown component: %d", p14);
                return NOTOK;
        }
        p12_count ++;
    }
    else {
        advise (NULLCP, "alignment missing alignment member");
        return NOTOK;
    }

    if (p12 = set_find (pe, PE_CLASS_CONT, 3)) {
        vname ("alignment-character-string");
        vstring (p12);
        p12_count ++;
    }
    if (p12_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Graphic__Rendition (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p15;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Graphic-Rendition bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Graphic-Rendition bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p15 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Graphic-Rendition bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p15;

    vpush ();
    for (p15 = first_member (pe); p15; p15 = next_member (pe, p15)) {
        if (print_ISPR9_Graphic__Rendition__Aspect (p15, 1, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
    }
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Character__Fonts (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p16_count = 0;
    register PE p16;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Character-Fonts bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Character-Fonts bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p16 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Character-Fonts bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p16;

    vpush ();
    if (p16 = set_find (pe, PE_CLASS_CONT, 0)) {
        vname ("primary-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 1)) {
        vname ("first-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 2)) {
        vname ("second-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 3)) {
        vname ("third-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 4)) {
        vname ("fourth-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 5)) {
        vname ("fifth-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 6)) {
        vname ("sixth-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 7)) {
        vname ("seventh-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 8)) {
        vname ("eighth-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16 = set_find (pe, PE_CLASS_CONT, 9)) {
        vname ("ninth-alternative-font");
        if (print_ISPR9_Font__Type (p16, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p16_count ++;
    }
    if (p16_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Font__Type (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p17_count = 0;
    register PE p17;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Font-Type bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Font-Type bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p17 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Font-Type bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p17;

    vpush ();
    if (p17 = set_find (pe, PE_CLASS_CONT, 0)) {
        register int p18;

        vname ("font-size");
        if ((p18 = prim2num (p17)) == NOTOK
                && p17 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "font-size bad integer: %s",
                    pe_error (p17 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p18);
        p17_count ++;
    }
    else {
        advise (NULLCP, "font-size missing font-size member");
        return NOTOK;
    }

    if (p17 = set_find (pe, PE_CLASS_CONT, 1)) {
        register int p19;

        vname ("font-identifier");
        if ((p19 = prim2num (p17)) == NOTOK
                && p17 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "font-identifier bad integer: %s",
                    pe_error (p17 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p19);
        p17_count ++;
    }
    else {
        advise (NULLCP, "font-identifier missing font-identifier member");
        return NOTOK;
    }

    if (p17_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Graphic__Rendition__Aspect (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p20;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Graphic-Rendition-Aspect bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Graphic-Rendition-Aspect bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p20 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Graphic-Rendition-Aspect bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p20;
    switch (p20) {
        case 0:	/* cancel */
            vprint ("cancel");
            break;
        case 1:	/* increased-intensity */
            vprint ("increased-intensity");
            break;
        case 2:	/* decreased-intensity */
            vprint ("decreased-intensity");
            break;
        case 3:	/* italicized */
            vprint ("italicized");
            break;
        case 4:	/* underlined */
            vprint ("underlined");
            break;
        case 5:	/* slowly-blinking */
            vprint ("slowly-blinking");
            break;
        case 6:	/* rapidly-blinking */
            vprint ("rapidly-blinking");
            break;
        case 7:	/* negative-image */
            vprint ("negative-image");
            break;
        case 9:	/* crossed-out */
            vprint ("crossed-out");
            break;
        case 10:	/* primary-font */
            vprint ("primary-font");
            break;
        case 11:	/* first-alternative-font */
            vprint ("first-alternative-font");
            break;
        case 12:	/* second-alternative-font */
            vprint ("second-alternative-font");
            break;
        case 13:	/* third-alternative-font */
            vprint ("third-alternative-font");
            break;
        case 14:	/* fourth-alternative-font */
            vprint ("fourth-alternative-font");
            break;
        case 15:	/* fifth-alternative-font */
            vprint ("fifth-alternative-font");
            break;
        case 16:	/* sixth-alternative-font */
            vprint ("sixth-alternative-font");
            break;
        case 17:	/* seventh-alternative-font */
            vprint ("seventh-alternative-font");
            break;
        case 18:	/* eighth-alternative-font */
            vprint ("eighth-alternative-font");
            break;
        case 19:	/* ninth-alternative-font */
            vprint ("ninth-alternative-font");
            break;
        case 21:	/* doubly-underlined */
            vprint ("doubly-underlined");
            break;
        case 22:	/* normal-intensity */
            vprint ("normal-intensity");
            break;
        case 23:	/* not-italicized */
            vprint ("not-italicized");
            break;
        case 24:	/* not-underlined */
            vprint ("not-underlined");
            break;
        case 25:	/* steady */
            vprint ("steady");
            break;
        case 26:	/* variable-spacing */
            vprint ("variable-spacing");
            break;
        case 27:	/* positive-image */
            vprint ("positive-image");
            break;
        case 29:	/* not-crossed-out */
            vprint ("not-crossed-out");
            break;
        default:
            advise (NULLCP, "Graphic-Rendition-Aspect has unknown component: %d", p20);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Formatting__Indicator (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p21;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Formatting-Indicator bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Formatting-Indicator bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p21 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Formatting-Indicator bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p21;
    switch (p21) {
        case 0:	/* no */
            vprint ("no");
            break;
        case 1:	/* yes */
            vprint ("yes");
            break;
        default:
            advise (NULLCP, "Formatting-Indicator has unknown component: %d", p21);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Itemisation (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p22_count = 0;
    register PE p22;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Itemisation bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Itemisation bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p22 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Itemisation bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p22;

    vpush ();
    if (p22 = set_find (pe, PE_CLASS_CONT, 0)) {
        register int p23;

        vname ("identifier-alignment");
        if ((p23 = prim2num (p22)) == NOTOK
                && p22 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "identifier-alignment bad integer: %s",
                    pe_error (p22 -> pe_errno));
            return NOTOK;
        }
        switch (p23) {
            case 0:	/* no-itemisation */
                vprint ("no-itemisation");
                break;
            case 1:	/* start-aligned */
                vprint ("start-aligned");
                break;
            case 2:	/* end-aligned */
                vprint ("end-aligned");
                break;
            default:
                advise (NULLCP, "identifier-alignment has unknown component: %d", p23);
                return NOTOK;
        }
        p22_count ++;
    }
    else {
        advise (NULLCP, "identifier-alignment missing identifier-alignment member");
        return NOTOK;
    }

    if (p22 = set_find (pe, PE_CLASS_CONT, 1)) {
        register int p24;

        vname ("identifier-start-offset");
        if ((p24 = prim2num (p22)) == NOTOK
                && p22 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "identifier-start-offset bad integer: %s",
                    pe_error (p22 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p24);
        p22_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p22 = set_find (pe, PE_CLASS_CONT, 2)) {
        register int p25;

        vname ("identifier-end-offset");
        if ((p25 = prim2num (p22)) == NOTOK
                && p22 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "identifier-end-offset bad integer: %s",
                    pe_error (p22 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p25);
        p22_count ++;
    }
    else {
        /* set default here using yp -> yp_default */
    }

    if (p22_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Kerning__Offset (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p26_count = 0;
    register PE p26;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Kerning-Offset bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Kerning-Offset bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p26 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Kerning-Offset bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p26;

    vpush ();
    if (p26 = set_find (pe, PE_CLASS_CONT, 0)) {
        register int p27;

        vname ("start-offset");
        if ((p27 = prim2num (p26)) == NOTOK
                && p26 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "start-offset bad integer: %s",
                    pe_error (p26 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p27);
        p26_count ++;
    }
    else {
        advise (NULLCP, "start-offset missing start-offset member");
        return NOTOK;
    }

    if (p26 = set_find (pe, PE_CLASS_CONT, 1)) {
        register int p28;

        vname ("end-offset");
        if ((p28 = prim2num (p26)) == NOTOK
                && p26 -> pe_errno != PE_ERR_NONE) {
            advise (NULLCP, "end-offset bad integer: %s",
                    pe_error (p26 -> pe_errno));
            return NOTOK;
        }
        vprint ("%d", p28);
        p26_count ++;
    }
    else {
        advise (NULLCP, "end-offset missing end-offset member");
        return NOTOK;
    }

    if (p26_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");
    vpop ();

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Proportional__Line__Spacing (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p29;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Proportional-Line-Spacing bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Proportional-Line-Spacing bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p29 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Proportional-Line-Spacing bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p29;
    switch (p29) {
        case 0:	/* no */
            vprint ("no");
            break;
        case 1:	/* yes */
            vprint ("yes");
            break;
        default:
            advise (NULLCP, "Proportional-Line-Spacing has unknown component: %d", p29);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	print_ISPR9_Pairwise__Kerning (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p30;

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Pairwise-Kerning bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Pairwise-Kerning bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p30 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Pairwise-Kerning bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p30;
    switch (p30) {
        case 0:	/* no */
            vprint ("no");
            break;
        case 1:	/* yes */
            vprint ("yes");
            break;
        default:
            advise (NULLCP, "Pairwise-Kerning has unknown component: %d", p30);
            return NOTOK;
    }

    return OK;
}
