/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISRD12 */
# line 5 "isrd12.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */

#include <odatk.h>

#define TK_IMPL_ISRD

#include <isrd.h>

#undef TK_IMPL_ISRD

#define PEPYPARM struct isode2toolkit_t *


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	parse_ISRD12_Raster__Graphics__Attributes (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    int p0_count = 0;
    register PE p0;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Raster-Graphics-Attributes");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SET) {
            advise (NULLCP, "Raster-Graphics-Attributes bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Raster-Graphics-Attributes bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p0 = prim2set (pe)) == NULLPE) {
        advise (NULLCP, "Raster-Graphics-Attributes bad set: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p0;

    if (p0 = set_find (pe, PE_CLASS_CONT, 0)) {
#ifdef DEBUG
        (void) testdebug (p0, "pel-path");
#endif

        if (parse_ISRD12_One__Of__Four__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 1)) {
#ifdef DEBUG
        (void) testdebug (p0, "line-progression");
#endif

        if (parse_ISRD12_One__Of__Two__Angles (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 2)) {
#ifdef DEBUG
        (void) testdebug (p0, "pel-transmission-density");
#endif

        if (parse_ISRD12_Pel__Transmission__Density (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 3)) {
#ifdef DEBUG
        (void) testdebug (p0, "initial-offset");
#endif

        if (parse_ISRD4_Measure__Pair (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 4)) {
#ifdef DEBUG
        (void) testdebug (p0, "clipping");
#endif

        if (parse_ISRD12_Clipping (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 5)) {
        register PE p1 = p0;

        {	/* pel-spacing TAG PULLUP */
            register PE p2;

            if ((p2 = prim2set (p1)) == NULLPE) {
                advise (NULLCP, "pel-spacing bad pel-spacing: %s",
                        pe_error (p1 -> pe_errno));
                return NOTOK;
            }
            if (p2 -> pe_cardinal != 1) {
                advise (NULLCP, "pel-spacing too many elements for tagged pel-spacing: %d",
                        p2 -> pe_cardinal);
                return NOTOK;
            }
            p1 = first_member (p2);
        }
        {
#ifdef DEBUG
            (void) testdebug (p1, "pel-spacing");
#endif

            if (parse_ISRD12_Pel__Spacing (p1, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 6)) {
#ifdef DEBUG
        (void) testdebug (p0, "spacing-ratio");
#endif

        if (parse_ISRD12_Spacing__Ratio (p0, 0, NULLIP, NULLVP, NullParm) == NOTOK)
            return NOTOK;
        p0_count ++;
    }
    if (p0 = set_find (pe, PE_CLASS_CONT, 7)) {
        register PE p3 = p0;

        {	/* image-dimensions TAG PULLUP */
            register PE p4;

            if ((p4 = prim2set (p3)) == NULLPE) {
                advise (NULLCP, "image-dimensions bad image-dimensions: %s",
                        pe_error (p3 -> pe_errno));
                return NOTOK;
            }
            if (p4 -> pe_cardinal != 1) {
                advise (NULLCP, "image-dimensions too many elements for tagged image-dimensions: %d",
                        p4 -> pe_cardinal);
                return NOTOK;
            }
            p3 = first_member (p4);
        }
        {
#ifdef DEBUG
            (void) testdebug (p3, "image-dimensions");
#endif

            if (parse_ISRD12_Image__Dimensions (p3, 1, NULLIP, NULLVP, NullParm) == NOTOK)
                return NOTOK;
        }
        p0_count ++;
    }
    if (p0_count != pe -> pe_cardinal)
        advise (NULLCP, "warning: extra or duplicate members present in SET");

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_One__Of__Four__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p5;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.One-Of-Four-Angles");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Four-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Four-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p5 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Four-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p5;
    switch (p5) {
        case 0:	/* d0 */
            break;
        case 1:	/* d90 */
            break;
        case 2:	/* d180 */
            break;
        case 3:	/* d270 */
            break;
        default:
            advise (NULLCP, "One-Of-Four-Angles has unknown component: %d", p5);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_One__Of__Two__Angles (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p6;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.One-Of-Two-Angles");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "One-Of-Two-Angles bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "One-Of-Two-Angles bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p6 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "One-Of-Two-Angles bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p6;
    switch (p6) {
        case 1:	/* d90 */
            break;
        case 3:	/* d270 */
            break;
        default:
            advise (NULLCP, "One-Of-Two-Angles has unknown component: %d", p6);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_Pel__Transmission__Density (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register int p7;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Pel-Transmission-Density");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_PRIM
                || pe -> pe_id != PE_PRIM_INT) {
            advise (NULLCP, "Pel-Transmission-Density bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_PRIM) {
            advise (NULLCP, "Pel-Transmission-Density bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p7 = prim2num (pe)) == NOTOK
            && pe -> pe_errno != PE_ERR_NONE) {
        advise (NULLCP, "Pel-Transmission-Density bad integer: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    if (len)
        *len = p7;
    switch (p7) {
        case 1:	/* p6 */
            break;
        case 2:	/* p5 */
            break;
        case 3:	/* p4 */
            break;
        case 4:	/* p3 */
            break;
        case 5:	/* p2 */
            break;
        case 6:	/* p1 */
            break;
        default:
            advise (NULLCP, "Pel-Transmission-Density has unknown component: %d", p7);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_Clipping (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p8;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Clipping");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Clipping bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Clipping bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p8 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Clipping bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p8;

    {
        register PE p9;

        if ((p9 = first_member (pe)) != NULLPE
                && PE_ID (p9 -> pe_class, p9 -> pe_id)
                        != PE_ID (PE_CLASS_CONT, 0))
            p9 = NULLPE;
        if (p9 != NULLPE) {
            p8 = p9;

            {	/* first-coordinate-pair */
#ifdef DEBUG
                (void) testdebug (p9, "first-coordinate-pair");
#endif

                if (parse_ISRD12_Coordinate__Pair (p9, 0, NULLIP, NULLVP, NullParm) == NOTOK)
                    return NOTOK;
            }
        }
    }

    {
        register PE p10;

        if ((p10 = (pe != p8 ? next_member (pe, p8) : first_member (pe))) != NULLPE) {
            p8 = p10;

            {	/* second-coordinate-pair */
#ifdef DEBUG
                (void) testdebug (p10, "second-coordinate-pair");
#endif

                if (parse_ISRD12_Coordinate__Pair (p10, 0, NULLIP, NULLVP, NullParm) == NOTOK)
                    return NOTOK;
            }
        }
        else {
            advise (NULLCP, "Clipping missing second-coordinate-pair element");
            return NOTOK;
        }

    }


    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Clipping has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_Coordinate__Pair (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p11;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Coordinate-Pair");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Coordinate-Pair bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Coordinate-Pair bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p11 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Coordinate-Pair bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p11;

    {
        register PE p12;

        if ((p12 = first_member (pe)) != NULLPE) {
            p11 = p12;

            {	/* x-coordinate */
#ifdef DEBUG
                (void) testdebug (p12, "x-coordinate");
#endif

                if (p12 -> pe_class != PE_CLASS_UNIV
                        || p12 -> pe_form != PE_FORM_PRIM
                        || p12 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "x-coordinate bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p12 -> pe_class], p12 -> pe_form, p12 -> pe_id);
                    return NOTOK;
                }

                if (prim2num (p12) == NOTOK
                        && p12 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "x-coordinate bad integer: %s",
                            pe_error (p12 -> pe_errno));
                    return NOTOK;
                }
            }
        }
        else {
            advise (NULLCP, "Coordinate-Pair missing x-coordinate element");
            return NOTOK;
        }

    }

    {
        register PE p13;

        if ((p13 = (pe != p11 ? next_member (pe, p11) : first_member (pe))) != NULLPE) {
            p11 = p13;

            {	/* y-coordinate */
#ifdef DEBUG
                (void) testdebug (p13, "y-coordinate");
#endif

                if (p13 -> pe_class != PE_CLASS_UNIV
                        || p13 -> pe_form != PE_FORM_PRIM
                        || p13 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "y-coordinate bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p13 -> pe_class], p13 -> pe_form, p13 -> pe_id);
                    return NOTOK;
                }

                if (prim2num (p13) == NOTOK
                        && p13 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "y-coordinate bad integer: %s",
                            pe_error (p13 -> pe_errno));
                    return NOTOK;
                }
            }
        }
        else {
            advise (NULLCP, "Coordinate-Pair missing y-coordinate element");
            return NOTOK;
        }

    }


    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Coordinate-Pair has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_Pel__Spacing (pe, explicit, len, buffer, parm)
PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Pel-Spacing");
#endif

    switch (PE_ID (pe -> pe_class, pe -> pe_id)) {
        case PE_ID (PE_CLASS_CONT, 0):	/* spacing */
            {
                register PE p14;

#ifdef DEBUG
                (void) testdebug (pe, "spacing");
#endif

                if ((p14 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "spacing bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p14;

                {
                    register PE p15;

                    if ((p15 = first_member (pe)) != NULLPE) {
                        p14 = p15;

                        {	/* length */
#ifdef DEBUG
                            (void) testdebug (p15, "length");
#endif

                            if (p15 -> pe_class != PE_CLASS_UNIV
                                    || p15 -> pe_form != PE_FORM_PRIM
                                    || p15 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "length bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p15 -> pe_class], p15 -> pe_form, p15 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p15) == NOTOK
                                    && p15 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "length bad integer: %s",
                                        pe_error (p15 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "spacing missing length element");
                        return NOTOK;
                    }

                }

                {
                    register PE p16;

                    if ((p16 = (pe != p14 ? next_member (pe, p14) : first_member (pe))) != NULLPE) {
                        p14 = p16;

                        {	/* pel-spaces */
#ifdef DEBUG
                            (void) testdebug (p16, "pel-spaces");
#endif

                            if (p16 -> pe_class != PE_CLASS_UNIV
                                    || p16 -> pe_form != PE_FORM_PRIM
                                    || p16 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "pel-spaces bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p16 -> pe_class], p16 -> pe_form, p16 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p16) == NOTOK
                                    && p16 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "pel-spaces bad integer: %s",
                                        pe_error (p16 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "spacing missing pel-spaces element");
                        return NOTOK;
                    }

                }


                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "spacing has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 1):	/* null */
            {
#ifdef DEBUG
                (void) testdebug (pe, "null");
#endif

            }
            break;

        default:
            advise (NULLCP, "Pel-Spacing has unknown choice: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_Spacing__Ratio (pe, explicit, len, buffer, parm)
register PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
    register PE p17;

#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Spacing-Ratio");
#endif

    if (explicit) {
        if (pe -> pe_class != PE_CLASS_UNIV
                || pe -> pe_form != PE_FORM_CONS
                || pe -> pe_id != PE_CONS_SEQ) {
            advise (NULLCP, "Spacing-Ratio bad class/form/id: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
        }
    }
    else
        if (pe -> pe_form != PE_FORM_CONS) {
            advise (NULLCP, "Spacing-Ratio bad form: %d", pe -> pe_form);
            return NOTOK;
        }

    if ((p17 = prim2seq (pe)) == NULLPE) {
        advise (NULLCP, "Spacing-Ratio bad sequence: %s",
                pe_error (pe -> pe_errno));
        return NOTOK;
    }
    pe = p17;

    {
        register PE p18;

        if ((p18 = first_member (pe)) != NULLPE) {
            p17 = p18;

            {	/* line-spacing-value */
#ifdef DEBUG
                (void) testdebug (p18, "line-spacing-value");
#endif

                if (p18 -> pe_class != PE_CLASS_UNIV
                        || p18 -> pe_form != PE_FORM_PRIM
                        || p18 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "line-spacing-value bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p18 -> pe_class], p18 -> pe_form, p18 -> pe_id);
                    return NOTOK;
                }

                if (prim2num (p18) == NOTOK
                        && p18 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "line-spacing-value bad integer: %s",
                            pe_error (p18 -> pe_errno));
                    return NOTOK;
                }
            }
        }
        else {
            advise (NULLCP, "Spacing-Ratio missing line-spacing-value element");
            return NOTOK;
        }

    }

    {
        register PE p19;

        if ((p19 = (pe != p17 ? next_member (pe, p17) : first_member (pe))) != NULLPE) {
            p17 = p19;

            {	/* pel-spacing-value */
#ifdef DEBUG
                (void) testdebug (p19, "pel-spacing-value");
#endif

                if (p19 -> pe_class != PE_CLASS_UNIV
                        || p19 -> pe_form != PE_FORM_PRIM
                        || p19 -> pe_id != PE_PRIM_INT) {
                    advise (NULLCP, "pel-spacing-value bad class/form/id: %s/%d/0x%x",
                            pe_classlist[p19 -> pe_class], p19 -> pe_form, p19 -> pe_id);
                    return NOTOK;
                }

                if (prim2num (p19) == NOTOK
                        && p19 -> pe_errno != PE_ERR_NONE) {
                    advise (NULLCP, "pel-spacing-value bad integer: %s",
                            pe_error (p19 -> pe_errno));
                    return NOTOK;
                }
            }
        }
        else {
            advise (NULLCP, "Spacing-Ratio missing pel-spacing-value element");
            return NOTOK;
        }

    }


    if (pe -> pe_cardinal > 2) {
        advise (NULLCP, "Spacing-Ratio has too many elements(2): %d",
                pe -> pe_cardinal);
        return NOTOK;
    }

    return OK;
}

/* ARGSUSED */

int	parse_ISRD12_Image__Dimensions (pe, explicit, len, buffer, parm)
PE	pe;
int	explicit;
int    *len;
char  **buffer;
PEPYPARM parm;
{
#ifdef DEBUG
    (void) testdebug (pe, "ISRD12.Image-Dimensions");
#endif

    switch (PE_ID (pe -> pe_class, pe -> pe_id)) {
        case PE_ID (PE_CLASS_CONT, 0):	/* width-controlled */
            {
                register PE p20;

#ifdef DEBUG
                (void) testdebug (pe, "width-controlled");
#endif

                if ((p20 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "width-controlled bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p20;

                {
                    register PE p21;

                    if ((p21 = first_member (pe)) != NULLPE) {
                        p20 = p21;

                        {	/* minimum-width */
#ifdef DEBUG
                            (void) testdebug (p21, "minimum-width");
#endif

                            if (p21 -> pe_class != PE_CLASS_UNIV
                                    || p21 -> pe_form != PE_FORM_PRIM
                                    || p21 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "minimum-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p21 -> pe_class], p21 -> pe_form, p21 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p21) == NOTOK
                                    && p21 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "minimum-width bad integer: %s",
                                        pe_error (p21 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "width-controlled missing minimum-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p22;

                    if ((p22 = (pe != p20 ? next_member (pe, p20) : first_member (pe))) != NULLPE) {
                        p20 = p22;

                        {	/* preferred-width */
#ifdef DEBUG
                            (void) testdebug (p22, "preferred-width");
#endif

                            if (p22 -> pe_class != PE_CLASS_UNIV
                                    || p22 -> pe_form != PE_FORM_PRIM
                                    || p22 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "preferred-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p22 -> pe_class], p22 -> pe_form, p22 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p22) == NOTOK
                                    && p22 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "preferred-width bad integer: %s",
                                        pe_error (p22 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "width-controlled missing preferred-width element");
                        return NOTOK;
                    }

                }


                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "width-controlled has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 1):	/* height-controlled */
            {
                register PE p23;

#ifdef DEBUG
                (void) testdebug (pe, "height-controlled");
#endif

                if ((p23 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "height-controlled bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p23;

                {
                    register PE p24;

                    if ((p24 = first_member (pe)) != NULLPE) {
                        p23 = p24;

                        {	/* minimum-height */
#ifdef DEBUG
                            (void) testdebug (p24, "minimum-height");
#endif

                            if (p24 -> pe_class != PE_CLASS_UNIV
                                    || p24 -> pe_form != PE_FORM_PRIM
                                    || p24 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "minimum-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p24 -> pe_class], p24 -> pe_form, p24 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p24) == NOTOK
                                    && p24 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "minimum-height bad integer: %s",
                                        pe_error (p24 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "height-controlled missing minimum-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p25;

                    if ((p25 = (pe != p23 ? next_member (pe, p23) : first_member (pe))) != NULLPE) {
                        p23 = p25;

                        {	/* preferred-height */
#ifdef DEBUG
                            (void) testdebug (p25, "preferred-height");
#endif

                            if (p25 -> pe_class != PE_CLASS_UNIV
                                    || p25 -> pe_form != PE_FORM_PRIM
                                    || p25 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "preferred-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p25 -> pe_class], p25 -> pe_form, p25 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p25) == NOTOK
                                    && p25 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "preferred-height bad integer: %s",
                                        pe_error (p25 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "height-controlled missing preferred-height element");
                        return NOTOK;
                    }

                }


                if (pe -> pe_cardinal > 2) {
                    advise (NULLCP, "height-controlled has too many elements(2): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 2):	/* area-controlled */
            {
                register PE p26;

#ifdef DEBUG
                (void) testdebug (pe, "area-controlled");
#endif

                if ((p26 = prim2seq (pe)) == NULLPE) {
                    advise (NULLCP, "area-controlled bad sequence: %s",
                            pe_error (pe -> pe_errno));
                    return NOTOK;
                }
                pe = p26;

                {
                    register PE p27;

                    if ((p27 = first_member (pe)) != NULLPE) {
                        p26 = p27;

                        {	/* a-minimum-width */
#ifdef DEBUG
                            (void) testdebug (p27, "a-minimum-width");
#endif

                            if (p27 -> pe_class != PE_CLASS_UNIV
                                    || p27 -> pe_form != PE_FORM_PRIM
                                    || p27 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-minimum-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p27 -> pe_class], p27 -> pe_form, p27 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p27) == NOTOK
                                    && p27 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-minimum-width bad integer: %s",
                                        pe_error (p27 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-minimum-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p28;

                    if ((p28 = (pe != p26 ? next_member (pe, p26) : first_member (pe))) != NULLPE) {
                        p26 = p28;

                        {	/* a-preferred-width */
#ifdef DEBUG
                            (void) testdebug (p28, "a-preferred-width");
#endif

                            if (p28 -> pe_class != PE_CLASS_UNIV
                                    || p28 -> pe_form != PE_FORM_PRIM
                                    || p28 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-preferred-width bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p28 -> pe_class], p28 -> pe_form, p28 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p28) == NOTOK
                                    && p28 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-preferred-width bad integer: %s",
                                        pe_error (p28 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-preferred-width element");
                        return NOTOK;
                    }

                }

                {
                    register PE p29;

                    if ((p29 = (pe != p26 ? next_member (pe, p26) : first_member (pe))) != NULLPE) {
                        p26 = p29;

                        {	/* a-minimum-height */
#ifdef DEBUG
                            (void) testdebug (p29, "a-minimum-height");
#endif

                            if (p29 -> pe_class != PE_CLASS_UNIV
                                    || p29 -> pe_form != PE_FORM_PRIM
                                    || p29 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-minimum-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p29 -> pe_class], p29 -> pe_form, p29 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p29) == NOTOK
                                    && p29 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-minimum-height bad integer: %s",
                                        pe_error (p29 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-minimum-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p30;

                    if ((p30 = (pe != p26 ? next_member (pe, p26) : first_member (pe))) != NULLPE) {
                        p26 = p30;

                        {	/* a-preferred-height */
#ifdef DEBUG
                            (void) testdebug (p30, "a-preferred-height");
#endif

                            if (p30 -> pe_class != PE_CLASS_UNIV
                                    || p30 -> pe_form != PE_FORM_PRIM
                                    || p30 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "a-preferred-height bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p30 -> pe_class], p30 -> pe_form, p30 -> pe_id);
                                return NOTOK;
                            }

                            if (prim2num (p30) == NOTOK
                                    && p30 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "a-preferred-height bad integer: %s",
                                        pe_error (p30 -> pe_errno));
                                return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing a-preferred-height element");
                        return NOTOK;
                    }

                }

                {
                    register PE p31;

                    if ((p31 = (pe != p26 ? next_member (pe, p26) : first_member (pe))) != NULLPE) {
                        p26 = p31;

                        {	/* aspect-ratio-flag */
                            register int p32;

#ifdef DEBUG
                            (void) testdebug (p31, "aspect-ratio-flag");
#endif

                            if (p31 -> pe_class != PE_CLASS_UNIV
                                    || p31 -> pe_form != PE_FORM_PRIM
                                    || p31 -> pe_id != PE_PRIM_INT) {
                                advise (NULLCP, "aspect-ratio-flag bad class/form/id: %s/%d/0x%x",
                                        pe_classlist[p31 -> pe_class], p31 -> pe_form, p31 -> pe_id);
                                return NOTOK;
                            }

                            if ((p32 = prim2num (p31)) == NOTOK
                                    && p31 -> pe_errno != PE_ERR_NONE) {
                                advise (NULLCP, "aspect-ratio-flag bad integer: %s",
                                        pe_error (p31 -> pe_errno));
                                return NOTOK;
                            }
                            switch (p32) {
                                case 0:	/* fixed */
                                    break;
                                case 1:	/* variable */
                                    break;
                                default:
                                    advise (NULLCP, "aspect-ratio-flag has unknown component: %d", p32);
                                    return NOTOK;
                            }
                        }
                    }
                    else {
                        advise (NULLCP, "area-controlled missing aspect-ratio-flag element");
                        return NOTOK;
                    }

                }


                if (pe -> pe_cardinal > 5) {
                    advise (NULLCP, "area-controlled has too many elements(5): %d",
                            pe -> pe_cardinal);
                    return NOTOK;
                }
            }
            break;
        case PE_ID (PE_CLASS_CONT, 3):	/* automatic */
            {
#ifdef DEBUG
                (void) testdebug (pe, "automatic");
#endif

            }
            break;

        default:
            advise (NULLCP, "Image-Dimensions has unknown choice: %s/%d/0x%x",
                    pe_classlist[pe -> pe_class], pe -> pe_form, pe -> pe_id);
            return NOTOK;
    }

    return OK;
}
