/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISWR8 */
# line 5 "iswr8.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */

#define TK_TKI_TKERR
#define TK_TKI_APIRT

#include <odatk.h>

#undef TK_TKI_TKERR
#undef TK_TKI_APIRT

#define TK_IMPL_ISWR

#include <iswr.h>

#undef TK_IMPL_ISWR

#define PEPYPARM struct isode2toolkit_t *

INT_type dummy;


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_ISWR8_Text__Unit (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct isode2toolkit_t *  parm;
{
# line 73 "iswr8.py"
    
    SEQUENCE_BYTE_type ContentInfoBytes;
    CHAR_type *ContentInfoChars;
    INT_type ContentInfoLength;

    PE	p0_z = NULLPE;
    register PE *p0 = &p0_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Text-Unit: out of memory");
        return NOTOK;
    }
    (*p0) = NULLPE;

    {	/* content-portion-attributes */
        if (build_ISWR8_Content__Portion__Attributes (p0, 0, 0, NULLCP, parm ) == NOTOK)
            return NOTOK;

#ifdef DEBUG
        (void) testdebug ((*p0), "content-portion-attributes");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Text-Unit bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    {	/* content-information */
        {
# line 93 "iswr8.py"

	    if ( GetAttr( parm->constituent,
			  at_CONTENT_INFORMATION,
			  (POINTER_type) &ContentInfoBytes,
			  /* default */ BOOL_false,
			  /* mask */ (PARM_MASK_type *) 0
			) == ERROR_INT ) {
		dummy = TKERR_StartErrMsg();
		dummy = TKERR_Format("[build_ISWR8_Text__Unit]: can not get attribute at_CONTENT_INFORMATION" );
		dummy = TKERR_EndErrMsg();
		return ( NOTOK );
	    }
	    if ( Bytes2Chars( ContentInfoBytes,
			      &ContentInfoChars,
			      &ContentInfoLength
			    ) == ERROR_INT ) {
		dummy = TKERR_StartErrMsg();
		dummy = TKERR_Format("[build_ISWR8_Text__Unit]: can not convert bytes to chars" );
		dummy = TKERR_EndErrMsg();
		return ( NOTOK );
	    }
	
        }
        if (build_ISWR8_Content__Information (p0, 0,  ContentInfoLength , ContentInfoChars , NullParm) == NOTOK)
            return NOTOK;

#ifdef DEBUG
        (void) testdebug ((*p0), "content-information");
#endif

    }

    if ((*p0) != NULLPE)
        if (seq_add ((*pe), (*p0), -1) == NOTOK) {
            advise (NULLCP, "Text-Unit bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR8.Text-Unit");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR8_Content__Portion__Attributes (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct isode2toolkit_t *  parm;
{
# line 124 "iswr8.py"
    
    STRING_type ContentLogicalIDString;
    CHAR_type *ContentLogicalIDChars;

    STRING_type ContentLayoutIDString;
    CHAR_type *ContentLayoutIDChars;

    SEQUENCE_INT_type TypeOfCoding;
    struct OIDentifier *TypeOfCodingObjectID;
    INT_type TypeOfCodingSelection;

    STRING_type AltRepString;
    CHAR_type *AltRepChars;
    INT_type AltRepLength;

    PE	p1_z = NULLPE;
    register PE *p1 = &p1_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SET)) == NULLPE) {
        advise (NULLCP, "Content-Portion-Attributes: out of memory");
        return NOTOK;
    }
    (*p1) = NULLPE;

    if ( GetAttr( parm->constituent,
			at_CONTENT_ID_LAYOUT,
			(POINTER_type) &ContentLayoutIDString,
			/* default */ BOOL_false,
			/* mask */ (PARM_MASK_type *) 0
		      ) != ERROR_INT ) {
        {
# line 144 "iswr8.py"

	    ContentLayoutIDChars = String2Chars(ContentLayoutIDString);
	    if ( ContentLayoutIDChars == ERROR_CHARS ) {
		dummy = TKERR_StartErrMsg();
		dummy = TKERR_Format("[build_ISWR8_Content__Portion__Attributes]: can not convert string to content-layout-id chars" );
		dummy = TKERR_EndErrMsg();
		return( NOTOK );
	    }
	
        }
        if (build_ISWR3_Content__Portion__Identifier (p1, 0, 0, ContentLayoutIDChars , NullParm) == NOTOK)
            return NOTOK;
        (*p1) -> pe_class = PE_CLASS_APPL;
        (*p1) -> pe_id = 0;

#ifdef DEBUG
        (void) testdebug ((*p1), "content-identifier-layout");
#endif

    }
    if ((*p1) != NULLPE)
        if (set_add ((*pe), (*p1)) == NOTOK) {
            advise (NULLCP, "Content-Portion-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p1) = NULLPE;

    if ( GetAttr( parm->constituent,
			at_CONTENT_ID_LOGICAL,
			(POINTER_type) &ContentLogicalIDString,
			/* default */ BOOL_false,
			/* mask */ (PARM_MASK_type *) 0
		      ) != ERROR_INT ) {
        {
# line 166 "iswr8.py"

	    ContentLogicalIDChars = String2Chars(ContentLogicalIDString);
	    if ( ContentLogicalIDChars == ERROR_CHARS ) {
		dummy = TKERR_StartErrMsg();
		dummy = TKERR_Format("[build_ISWR8_Content__Portion__Attributes]: can not convert string to content-logical-identifier chars" );
		dummy = TKERR_EndErrMsg();
		return( NOTOK );
	    }
	
        }
        if (build_ISWR3_Content__Portion__Identifier (p1, 0, 0, ContentLogicalIDChars , NullParm) == NOTOK)
            return NOTOK;
        (*p1) -> pe_class = PE_CLASS_CONT;
        (*p1) -> pe_id = 4;

#ifdef DEBUG
        (void) testdebug ((*p1), "content-identifier-logical");
#endif

    }
    if ((*p1) != NULLPE)
        if (set_add ((*pe), (*p1)) == NOTOK) {
            advise (NULLCP, "Content-Portion-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p1) = NULLPE;

    if ( GetAttr( parm->constituent,
			at_TYPE_OF_CODING,
			(POINTER_type) &TypeOfCoding,
			/* default */ BOOL_false,
			/* mask */ (PARM_MASK_type *) 0
		      ) != ERROR_INT ) {
        int	p2;

        {
# line 188 "iswr8.py"

	    /* support only object identifier format for type of coding */
	    TypeOfCodingSelection = (INT_type) 2;
	    TypeOfCodingObjectID = Ints2OID(TypeOfCoding);
	    if ( TypeOfCodingObjectID == NULLOID ) {
		dummy = TKERR_StartErrMsg();
		dummy = TKERR_Format("[build_ISWR8_Content__Portion__Attributes]: can not convert integer sequence to an object identifier" );
		dummy = TKERR_EndErrMsg();
		return( NOTOK );
	    }
	
        }
        switch (p2 = ( TypeOfCodingSelection )) {
            case 1:
                {
                    register int p3 = 0;

                    if (((*p1) = num2prim (p3, PE_CLASS_CONT, 0)) == NULLPE) {
                        advise (NULLCP, "member: out of memory");
                        return NOTOK;
                    }
                    switch (p3) {
                        case 0:	/* iso2022 */
                            break;
                        case 1:	/* t6 */
                            break;
                        default:
                            advise (NULLCP, "member has unknown component: %d", p3);
                            return NOTOK;
                    }

#ifdef DEBUG
                    (void) testdebug ((*p1), "member");
#endif

                }
                break;
            case 2:
                {
                    register OID p4;

                    p4 = TypeOfCodingObjectID ;
                    if (p4 == NULLOID) {
                        advise (NULLCP, "member initialization fails");
                        return NOTOK;
                    }
                    if (((*p1) = obj2prim (p4, PE_CLASS_CONT, 6)) == NULLPE) {
                        advise (NULLCP, "member: out of memory");
                        return NOTOK;
                    }

#ifdef DEBUG
                    (void) testdebug ((*p1), "member");
#endif

                    {
# line 211 "iswr8.py"

		    if ( oid_free(TypeOfCodingObjectID) == NOTOK ) {
			dummy = TKERR_StartErrMsg();
			dummy = TKERR_Format("[build_ISWR8_Content__Portion__Attributes]: can not free object identifier");
			dummy = TKERR_EndErrMsg();
			return( NOTOK );
		    }
		
                    }
                }
                break;

            default:
                advise (NULLCP, "type-of-coding invalid choice selected: %d",
                        p2);
                return NOTOK;
        }

#ifdef DEBUG
        (void) testdebug ((*p1), "type-of-coding");
#endif

    }
    if ((*p1) != NULLPE)
        if (set_add ((*pe), (*p1)) == NOTOK) {
            advise (NULLCP, "Content-Portion-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p1) = NULLPE;

    if ((*p1) != NULLPE)
        if (set_add ((*pe), (*p1)) == NOTOK) {
            advise (NULLCP, "Content-Portion-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p1) = NULLPE;

    if ( GetAttr( parm->constituent,
			at_ALT_REP,
			(POINTER_type) &AltRepString,
			/* default */ BOOL_false,
			/* mask */ (PARM_MASK_type *) 0
		      ) != ERROR_INT ) {
        {
# line 263 "iswr8.py"

	    AltRepLength = AltRepString->length;
	    AltRepChars = AltRepString->sequence_value.chars;
	
        }
        if (build_ISWR8_Alternative__Representation (p1, 0,  AltRepLength , AltRepChars , NullParm) == NOTOK)
            return NOTOK;
        (*p1) -> pe_class = PE_CLASS_CONT;
        (*p1) -> pe_id = 3;

#ifdef DEBUG
        (void) testdebug ((*p1), "alternative-representation");
#endif

    }
    if ((*p1) != NULLPE)
        if (set_add ((*pe), (*p1)) == NOTOK) {
            advise (NULLCP, "Content-Portion-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR8.Content-Portion-Attributes");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR8_Content__Information (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p5;
    int p5_len;

    p5 = buffer;
    if ((p5_len = len) == 0)
        p5_len = strlen (p5);
    if (p5 == NULLCP) {
        advise (NULLCP, "Content-Information initialization fails");
        return NOTOK;
    }
    if (((*pe) = str2prim (p5, p5_len, PE_CLASS_UNIV, PE_PRIM_OCTS)) == NULLPE) {
        advise (NULLCP, "Content-Information: out of memory");
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR8.Content-Information");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR8_Type__of__Coding (pe, explicit, len, buffer, parm)
PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR8.Type-of-Coding");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR8_Alternative__Representation (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p6;
    int p6_len;

    p6 = buffer;
    if ((p6_len = len) == 0)
        p6_len = strlen (p6);
    if (p6 == NULLCP) {
        advise (NULLCP, "Alternative-Representation initialization fails");
        return NOTOK;
    }
    if (((*pe) = str2prim (p6, p6_len, PE_CLASS_UNIV, PE_PRIM_OCTS)) == NULLPE) {
        advise (NULLCP, "Alternative-Representation: out of memory");
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR8.Alternative-Representation");
#endif


    return OK;
}
