/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISWR1 */
# line 5 "iswr1.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */

#include <odatk.h>

#define TK_IMPL_ISWR

#include <iswr.h>

#undef TK_IMPL_ISWR

#define PEPYPARM struct isode2toolkit_t *


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_ISWR1_Interchange__Data__Element (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
struct isode2toolkit_t *  parm;
{
    int	p0;

    switch (p0 = ( parm->what_kind_constituent )) {
        case 1:	/* document-profile */
            {
                if (build_ISWR2_Document__Profile__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 0;

#ifdef DEBUG
                (void) testdebug ((*pe), "document-profile");
#endif

            }
            break;
        case 2:	/* layout-object-class */
            {
                if (build_ISWR4_Layout__Class__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 1;

#ifdef DEBUG
                (void) testdebug ((*pe), "layout-object-class");
#endif

            }
            break;
        case 3:	/* layout-object */
            {
                if (build_ISWR4_Layout__Object__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 2;

#ifdef DEBUG
                (void) testdebug ((*pe), "layout-object");
#endif

            }
            break;
        case 4:	/* content-portion */
            {
                if (build_ISWR8_Text__Unit (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 3;

#ifdef DEBUG
                (void) testdebug ((*pe), "content-portion");
#endif

            }
            break;
        case 5:	/* logical-object-class */
            {
                if (build_ISWR5_Logical__Class__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 5;

#ifdef DEBUG
                (void) testdebug ((*pe), "logical-object-class");
#endif

            }
            break;
        case 6:	/* logical-object */
            {
                if (build_ISWR5_Logical__Object__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 6;

#ifdef DEBUG
                (void) testdebug ((*pe), "logical-object");
#endif

            }
            break;
        case 7:	/* presentation-style */
            {
                if (build_ISWR6_Presentation__Style__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 7;

#ifdef DEBUG
                (void) testdebug ((*pe), "presentation-style");
#endif

            }
            break;
        case 8:	/* layout-style */
            {
                if (build_ISWR6_Layout__Style__Descriptor (pe, 0, 0, NULLCP, parm ) == NOTOK)
                    return NOTOK;
                (*pe) -> pe_class = PE_CLASS_CONT;
                (*pe) -> pe_id = 8;

#ifdef DEBUG
                (void) testdebug ((*pe), "layout-style");
#endif

            }
            break;

        default:
            advise (NULLCP, "Interchange-Data-Element invalid choice selected: %d",
                    p0);
            return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR1.Interchange-Data-Element");
#endif


    return OK;
}
