/* automatically generated by pepy 5.0 #1 (mss.andrew.cmu.edu), do not edit! */

#include <psap.h>

static char *pepyid = "pepy 5.0 #1 (mss.andrew.cmu.edu) of Mon May 22 20:44:32 EDT 1989";

#define	advise	PY_advise

void	advise ();

/* Generated from module ISWR15 */
# line 5 "iswr15.py"


/*
 *
 * (C) Copyright 1989 by Carnegie Mellon University
 *
 * Permission to use, copy, modify, and distribute these programs
 * and their documentation for any purpose and without fee is
 * hereby granted, provided that this copyright and permission
 * notice appear on all copies and supporting documentation, and
 * that the name of Carnegie Mellon University not be used in
 * advertising or publicity pertaining to distribution of the
 * programs without specific prior permission and notice be given
 * in supporting documentation that copying and distribution is
 * by permission of Carnegie Mellon University.
 *
 * Carnegie Mellon University makes no representations about the
 * suitability of this software for any purpose.  It is provided
 * as is, without express or implied warranty.
 *
 * Software by Ann Marks and James T. Lui,
 * Information Technology Center, Carnegie Mellon University,
 * except where noted.
 *
 */

#include <odatk.h>

#define TK_IMPL_ISWR

#include <iswr.h>

#undef TK_IMPL_ISWR

#define PEPYPARM struct isode2toolkit_t *


#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_ISWR15_Geometric__Graphics__Attributes (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p0_z = NULLPE;
    register PE *p0 = &p0_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SET)) == NULLPE) {
        advise (NULLCP, "Geometric-Graphics-Attributes: out of memory");
        return NOTOK;
    }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p0) = NULLPE;

    if ((*p0) != NULLPE)
        if (set_add ((*pe), (*p0)) == NOTOK) {
            advise (NULLCP, "Geometric-Graphics-Attributes bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Geometric-Graphics-Attributes");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Encoding__Announcer (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p1;
    int p1_len;

    p1 = buffer;
    if ((p1_len = len) == 0)
        p1_len = strlen (p1);
    if (p1 == NULLCP) {
        advise (NULLCP, "Encoding-Announcer initialization fails");
        return NOTOK;
    }
    if (((*pe) = str2prim (p1, p1_len, PE_CLASS_UNIV, PE_PRIM_OCTS)) == NULLPE) {
        advise (NULLCP, "Encoding-Announcer: out of memory");
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Encoding-Announcer");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Line__Rendition (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p2_z = NULLPE;
    register PE *p2 = &p2_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Line-Rendition: out of memory");
        return NOTOK;
    }
    (*p2) = NULLPE;

    if ((*p2) != NULLPE)
        if (seq_add ((*pe), (*p2), -1) == NOTOK) {
            advise (NULLCP, "Line-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p2) = NULLPE;

    if ((*p2) != NULLPE)
        if (seq_add ((*pe), (*p2), -1) == NOTOK) {
            advise (NULLCP, "Line-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p2) = NULLPE;

    if ((*p2) != NULLPE)
        if (seq_add ((*pe), (*p2), -1) == NOTOK) {
            advise (NULLCP, "Line-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Line-Rendition");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Marker__Rendition (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p3_z = NULLPE;
    register PE *p3 = &p3_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Marker-Rendition: out of memory");
        return NOTOK;
    }
    (*p3) = NULLPE;

    if ((*p3) != NULLPE)
        if (seq_add ((*pe), (*p3), -1) == NOTOK) {
            advise (NULLCP, "Marker-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p3) = NULLPE;

    if ((*p3) != NULLPE)
        if (seq_add ((*pe), (*p3), -1) == NOTOK) {
            advise (NULLCP, "Marker-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p3) = NULLPE;

    if ((*p3) != NULLPE)
        if (seq_add ((*pe), (*p3), -1) == NOTOK) {
            advise (NULLCP, "Marker-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Marker-Rendition");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Text__Rendition (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p4_z = NULLPE;
    register PE *p4 = &p4_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Text-Rendition: out of memory");
        return NOTOK;
    }
    (*p4) = NULLPE;

    if ((*p4) != NULLPE)
        if (seq_add ((*pe), (*p4), -1) == NOTOK) {
            advise (NULLCP, "Text-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p4) = NULLPE;

    if ((*p4) != NULLPE)
        if (seq_add ((*pe), (*p4), -1) == NOTOK) {
            advise (NULLCP, "Text-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p4) = NULLPE;

    if ((*p4) != NULLPE)
        if (seq_add ((*pe), (*p4), -1) == NOTOK) {
            advise (NULLCP, "Text-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Text-Rendition");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Filled__Area__Rendition (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p5_z = NULLPE;
    register PE *p5 = &p5_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Filled-Area-Rendition: out of memory");
        return NOTOK;
    }
    (*p5) = NULLPE;

    if ((*p5) != NULLPE)
        if (seq_add ((*pe), (*p5), -1) == NOTOK) {
            advise (NULLCP, "Filled-Area-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p5) = NULLPE;

    if ((*p5) != NULLPE)
        if (seq_add ((*pe), (*p5), -1) == NOTOK) {
            advise (NULLCP, "Filled-Area-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p5) = NULLPE;

    if ((*p5) != NULLPE)
        if (seq_add ((*pe), (*p5), -1) == NOTOK) {
            advise (NULLCP, "Filled-Area-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p5) = NULLPE;

    if ((*p5) != NULLPE)
        if (seq_add ((*pe), (*p5), -1) == NOTOK) {
            advise (NULLCP, "Filled-Area-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Filled-Area-Rendition");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Edge__Rendition (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p6_z = NULLPE;
    register PE *p6 = &p6_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Edge-Rendition: out of memory");
        return NOTOK;
    }
    (*p6) = NULLPE;

    if ((*p6) != NULLPE)
        if (seq_add ((*pe), (*p6), -1) == NOTOK) {
            advise (NULLCP, "Edge-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p6) = NULLPE;

    if ((*p6) != NULLPE)
        if (seq_add ((*pe), (*p6), -1) == NOTOK) {
            advise (NULLCP, "Edge-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p6) = NULLPE;

    if ((*p6) != NULLPE)
        if (seq_add ((*pe), (*p6), -1) == NOTOK) {
            advise (NULLCP, "Edge-Rendition bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Edge-Rendition");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_ASF__Type (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register int p7 = len;

    if (((*pe) = num2prim (p7, PE_CLASS_UNIV, PE_PRIM_INT)) == NULLPE) {
        advise (NULLCP, "ASF-Type: out of memory");
        return NOTOK;
    }
    switch (p7) {
        case 0:	/* bundled */
            break;
        case 1:	/* individual */
            break;
        default:
            advise (NULLCP, "ASF-Type has unknown component: %d", p7);
            return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.ASF-Type");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Colour__Representations (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p8_z = NULLPE;
    register PE *p8 = &p8_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SEQ)) == NULLPE) {
        advise (NULLCP, "Colour-Representations: out of memory");
        return NOTOK;
    }
    (*p8) = NULLPE;

    if ((*p8) != NULLPE)
        if (seq_add ((*pe), (*p8), -1) == NOTOK) {
            advise (NULLCP, "Colour-Representations bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p8) = NULLPE;

    if ((*p8) != NULLPE)
        if (seq_add ((*pe), (*p8), -1) == NOTOK) {
            advise (NULLCP, "Colour-Representations bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Colour-Representations");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Transparency__Specification (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p9;
    int p9_len;

    p9 = buffer;
    if ((p9_len = len) == 0)
        p9_len = strlen (p9);
    if (p9 == NULLCP) {
        advise (NULLCP, "Transparency-Specification initialization fails");
        return NOTOK;
    }
    if (((*pe) = str2prim (p9, p9_len, PE_CLASS_UNIV, PE_PRIM_OCTS)) == NULLPE) {
        advise (NULLCP, "Transparency-Specification: out of memory");
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Transparency-Specification");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Transformation__Specification (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p10;
    int p10_len;

    p10 = buffer;
    if ((p10_len = len) == 0)
        p10_len = strlen (p10);
    if (p10 == NULLCP) {
        advise (NULLCP, "Transformation-Specification initialization fails");
        return NOTOK;
    }
    if (((*pe) = str2prim (p10, p10_len, PE_CLASS_UNIV, PE_PRIM_OCTS)) == NULLPE) {
        advise (NULLCP, "Transformation-Specification: out of memory");
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Transformation-Specification");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Region__Of__Interest (pe, explicit, len, buffer, parm)
PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Region-Of-Interest");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_VDC__Pair (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register char *p11;
    int p11_len;

    p11 = buffer;
    if ((p11_len = len) == 0)
        p11_len = strlen (p11);
    if (p11 == NULLCP) {
        advise (NULLCP, "VDC-Pair initialization fails");
        return NOTOK;
    }
    if (((*pe) = str2prim (p11, p11_len, PE_CLASS_UNIV, PE_PRIM_OCTS)) == NULLPE) {
        advise (NULLCP, "VDC-Pair: out of memory");
        return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.VDC-Pair");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Picture__Orientation (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    if (build_ISWR9_One__Of__Four__Angles (pe, 0, len, buffer, NullParm) == NOTOK)
        return NOTOK;

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Picture-Orientation");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_One__Of__Four__Angles (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    register int p12 = len;

    if (((*pe) = num2prim (p12, PE_CLASS_UNIV, PE_PRIM_INT)) == NULLPE) {
        advise (NULLCP, "One-Of-Four-Angles: out of memory");
        return NOTOK;
    }
    switch (p12) {
        case 0:	/* d0 */
            break;
        case 1:	/* d90 */
            break;
        case 2:	/* d180 */
            break;
        case 3:	/* d270 */
            break;
        default:
            advise (NULLCP, "One-Of-Four-Angles has unknown component: %d", p12);
            return NOTOK;
    }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.One-Of-Four-Angles");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Picture__Dimensions (pe, explicit, len, buffer, parm)
PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Picture-Dimensions");
#endif


    return OK;
}

/* ARGSUSED */

int	build_ISWR15_Geo__Gr__Content__Defaults (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p13_z = NULLPE;
    register PE *p13 = &p13_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, PE_CONS_SET)) == NULLPE) {
        advise (NULLCP, "Geo-Gr-Content-Defaults: out of memory");
        return NOTOK;
    }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p13) = NULLPE;

    if ((*p13) != NULLPE)
        if (set_add ((*pe), (*p13)) == NOTOK) {
            advise (NULLCP, "Geo-Gr-Content-Defaults bad set: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "ISWR15.Geo-Gr-Content-Defaults");
#endif


    return OK;
}
