/*
Copyright 1988, 1989 Marshall T. Rose

The ISODE is openly available but is NOT in the public domain. You are
allowed and encouraged to take this software and build commercial
products. However, as a condition of use, you are required to "hold
harmless" all contributors.
Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted,
provided that this notice and the reference to this notice appearing
in each software module be retained unaltered, and that the name of
any contributors shall not be used in advertising or publicity pertaining
to distribution of the software without specific written prior permission.
No contributor makes any representations about the suitability of this
software for any purpose. It is provided "as is" without express or
implied warranty.

ALL CONTRIBUTORS DISCLAIM ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED
WARRANTIES OR MERCHANTIBILITY AND FITNESS. IN
NO EVENT SHALL ANY CONTRIBUTOR BE LIABLE FOR
ANY SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN ACTION OF
CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFWTARE.

As used above, "contributor" includes, but is not limited to:

	The MITRE Corporation
	The Northrop Corporation
	University College London
	The University of Nottingham
	The Wollongong Group, Inc.
	Marshall T. Rose

In particular, the Northrop Coporation provided the initial
sponsorship for the ISODE and teh Wollongong Group, Inc.,
continued supporting this effort.
*/
/* automatically generated by pepy 5.0 #2 (mss.andrew.cmu.edu), do not edit! */

#include "psap.h"

#define	advise	PY_advise

void	advise ();

/* Generated from module UNIV */

#ifndef	lint
static char *rcsid = "$Header: /afs/andrew.cmu.edu/itc/sm/releases/X.V11R4/andrew/oda/isode/RCS/UPEPY-46.c,v 1.1 89/09/21 05:19:38 mss Exp $";
#endif

#ifndef PEPYPARM
#define PEPYPARM char *
#endif /* PEPYPARM */
extern PEPYPARM NullParm;

/* ARGSUSED */

int	build_UNIV_EXTERNAL (pe, explicit, len, buffer, parm)
register PE     *pe;
int	explicit;
int	len;
char   *buffer;
PEPYPARM parm;
{
    PE	p21_z = NULLPE;
    register PE *p21 = &p21_z;

    if (((*pe) = pe_alloc (PE_CLASS_UNIV, PE_FORM_CONS, 8)) == NULLPE) {
        advise (NULLCP, "EXTERNAL: out of memory");
        return NOTOK;
    }
    (*p21) = NULLPE;

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p21) = NULLPE;

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p21) = NULLPE;

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }
    (*p21) = NULLPE;

    {	/* encoding */

#ifdef DEBUG
        (void) testdebug ((*p21), "encoding");
#endif

    }

    if ((*p21) != NULLPE)
        if (seq_add ((*pe), (*p21), -1) == NOTOK) {
            advise (NULLCP, "EXTERNAL bad sequence: %s",
                    pe_error ((*pe) -> pe_errno));
            return NOTOK;
        }

#ifdef DEBUG
    (void) testdebug ((*pe), "UNIV.EXTERNAL");
#endif


    return OK;
}
