all:
	cd ximage; make 
	cd xds; make 
noImake:
	cd ximage; make -f Make.noImake
	cd xds; make -f Make.noImake

install:
	cd ximage; make install
	cd xds; make install
clean:
	cd ximage; make clean
	cd xds; make clean
