.TH pcxtopbm 1 "11 December 1988"
.SH NAME
pcxtopbm - convert a PC paintbrush (.pcx) file into a portable bitmap
.SH SYNOPSIS
pcxtopbm [pcxfile]
.SH DESCRIPTION
Reads a PC paintbrush (.pcx) file as input.
Produces a portable bitmap as output.
.PP
Note that there is currently no pbmtopcx tool.
.SH "SEE ALSO"
pbm(5)
.SH AUTHOR
Copyright (C) 1988 by Jef Poskanzer.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted, provided
that the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.  This software is provided "as is" without express or
implied warranty.

This program is based on the pcx2rf program by:
Mike Macgirvin, Stanford Relativity Gyro Program GP-B,
Stanford, CA 94503; ARPA: mike@relgyro.stanford.edu
