/*
 *		Copyright IBM Corporation 1989
 *
 *                      All Rights Reserved
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose and without fee is hereby granted,
 * provided that the above copyright notice appear in all copies and that
 * both that copyright notice and this permission notice appear in
 * supporting documentation, and that the name of IBM not be
 * used in advertising or publicity pertaining to distribution of the
 * software without specific, written prior permission.
 *
 * IBM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
 * ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
 * IBM BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
 * ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
 * WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
 * SOFTWARE.
 *
 *
 * University of Illinois at Urbana-Champaign
 * Department of Computer Science
 * 1304 W. Springfield Ave.
 * Urbana, IL	61801
 *
 * (C) Copyright 1987, 1988 by The University of Illinois Board of Trustees.
 * All rights reserved.
 *
 * Tool: X 11 Graphical Kernel System
 * Author: Gregory Scott Rogers
 * Author: Sung Hsien Ching Kelvin
 * Author: Yu Pan
 * 
 * make error message header file  from gks_errors.h file
 *
 * usage:mkerrmsg < gks_errors.h > gkserrmsg.h 
 * 
 * $Header: mkerrmsg.c,v 4.0 89/08/31 16:23:08 amy Exp $
 *
 * $Source: /andrew/Xgks/source/xgks.bld/src/RCS/mkerrmsg.c,v $
 *
 * $Log:	mkerrmsg.c,v $
 * Revision 4.0  89/08/31  16:23:08  amy
 * Changed IBM copyright for MIT distribution.
 * 
 * Revision 3.8  89/06/05  09:52:39  bruce
 * DCR# d1:	Added a return statement so mkerrmsg wouldn't screw up make.
 * 
 * Revision 3.7  89/03/15  18:10:31  amy
 * PTR c1130	Increased max. messages to 2004 to accomodate FORTRAN-
 * 		specific errors.
 * 
 * Revision 3.6  89/02/04  15:26:57  amy
 * PTR c1147	Make global vars. and functions private, and static where possible.
 * 
 * Revision 3.5  88/12/14  16:38:03  amy
 * New 4.3 Compiler--
 * 	Initialize cnt to 0 and max to 201.
 * 
 * Revision 3.4  88/08/17  13:48:31  amy
 * No change.
 * 
 * Revision 1.2  88/07/26  17:53:08  owens
 * renamed/replaced VALID_WSID macro for PTR c1012 (DWO)
 * 
 * Revision 1.1  88/07/21  10:49:41  david
 * Initial revision
 *  
 *
 */

static char *rcsid ="$Header: mkerrmsg.c,v 4.0 89/08/31 16:23:08 amy Exp $";

#include <stdio.h>
#include <strings.h>

main()
{
	char line[1024], dstr[30], estr[30];
	char *cp;
	int cnt=0, num, max=201;			/* New 4.3 Compiler */
	int first=1;

	printf("/*\n");
	printf(" * Do not edit this file, it is generated automatically from\n");
	printf(" * the gks_errors.h file via mkerrmsg.c.\n");
	printf(" */\n");
	printf("\n#ifndef GKSERRMSG_H\n#define GKSERRMSG_H\n");

/* c1147: the following line no longer needed, as gks_err_file is now part */
/* of the gks state list.                                                */
/*	printf("\nextern Gfile *gks_err_file;\n\n");                       */

	printf("#ifdef GKS_ERROR_C\n");
	while(gets(line) != NULL) {
		if (strncmp( "#define", line, 7) != 0)
			puts(line);
		else {
			if (first) {
				printf("char *GKSErrorMessages0to200[] = {\n");
				first = 0;
				cnt = 0;
				max = 201;
			}
			sscanf( line, "%s %s %d", dstr, estr, &num);
			if (num>max) {
				if (max == 201) {
					for( ; cnt<max; cnt++)
						printf("/* %d */	(char *)NULL,\n",cnt);
					printf("};\n");
					printf("char *GKSErrorMessages300to309[] = {\n");
					cnt = 300;
					max = 310;
				}
				else if (max == 310) {
					for( ; cnt<max; cnt++)
						printf("/* %d */	(char *)NULL,\n",cnt);
					printf("};\n");
					printf("char *GKSErrorMessages2000to2000[] = {\n");
					cnt = 2000;
					max = 2004; /* c1130 */
				}
				else
					printf("};\n");
			}
			for( ; cnt<num; cnt++)
				printf("/* %d */	(char *)NULL,\n",cnt);
			cnt++;
			printf("/* %s %d */	", estr, num);
			cp = rindex( line, '*'); cp--;
			*cp = '\0';
			cp = rindex( line, '*'); cp += 2;
			printf("\"%s\",\n", cp);
		}
	}
	printf("};\n");
	printf("\n#else GKS_ERROR_C\n");
	printf("extern char *GKSErrorMessages0to200[];\n");
	printf("extern char *GKSErrorMessages300to309[];\n");
	printf("extern char *GKSErrorMessages2000to2000[];\n");
	printf("\n#endif\n");
	printf("\n#endif\n");
	return(0);	/* d1 */
}
