*** Makefile.orig	Fri Oct 27 12:58:09 1989
--- Makefile	Fri Oct 27 15:39:17 1989
***************
*** 167,176 ****
  
          DEFINES = -DMODEMENU -DUTMP -DBcopy=bcopy
            SRCS1 = button.c charproc.c cursor.c data.c input.c \
! 		  main.c menu.c misc.c screen.c scrollbar.c tabs.c \
  		  TekPrsTbl.c Tekproc.c util.c VTPrsTbl.c
            OBJS1 = main.o input.o charproc.o cursor.o util.o tabs.o \
! 		  screen.o scrollbar.o button.o Tekproc.o misc.o \
  		  VTPrsTbl.o TekPrsTbl.o data.o menu.o
            SRCS2 = resize.c
            OBJS2 = resize.o
--- 167,176 ----
  
          DEFINES = -DMODEMENU -DUTMP -DBcopy=bcopy
            SRCS1 = button.c charproc.c cursor.c data.c input.c \
! 		  macrostr.c main.c menu.c misc.c screen.c scrollbar.c tabs.c \
  		  TekPrsTbl.c Tekproc.c util.c VTPrsTbl.c
            OBJS1 = main.o input.o charproc.o cursor.o util.o tabs.o \
! 		  screen.o scrollbar.o button.o Tekproc.o misc.o macrostr.o \
  		  VTPrsTbl.o TekPrsTbl.o data.o menu.o
            SRCS2 = resize.c
            OBJS2 = resize.o
