
/*
		(c) Copyright 1988 Carnegie Mellon University

 See "The CMU ODA Tool Kit" (available as CMU/ITC tech report
 CMU-ITC-071) for full text & permitted uses.


	Include file defining attribute identifier values

    WARNING: this file is generated from the API.
    WARNING: modifications to this file will disappear
    WARNING: when the file is next generated.

*/

#ifndef TK_INCLUDED_ATTRID
#define TK_INCLUDED_ATTRID

#define at_ALT_REP	((INT_type) 1)
#define at_APPLICATION_COMMENTS	((INT_type) 2)
#define at_BALANCE	((INT_type) 3)
#define at_BINDINGS	((INT_type) 4)
#define at_BLK_ALGNM	((INT_type) 5)
#define at_BORDER	((INT_type) 6)
#define at_COLOUR	((INT_type) 7)
#define at_CONCATENATION	((INT_type) 8)
#define at_CONTENT_ARCH_CLASS	((INT_type) 9)
#define at_CONTENT_GENERATOR	((INT_type) 10)
#define at_CONTENT_ID_LAYOUT	((INT_type) 11)
#define at_CONTENT_ID_LOGICAL	((INT_type) 12)
#define at_CONTENT_INFORMATION	((INT_type) 13)
#define at_CONTENT_PORTIONS	((INT_type) 14)
#define at_CONTENT_TYPE	((INT_type) 15)
#define at_DEFAULT_VALUE_LISTS	((INT_type) 16)
#define at_DIMENSIONS	((INT_type) 17)
#define at_FILL_ORDER	((INT_type) 18)
#define at_GEN_FOR_SUBORDINATES	((INT_type) 19)
#define at_IMAGING_ORDER	((INT_type) 20)
#define at_INDIVISIBILITY	((INT_type) 21)
#define at_LAYOUT_CATEGORY	((INT_type) 22)
#define at_LAYOUT_OBJECT_CLASS	((INT_type) 23)
#define at_LAYOUT_PATH	((INT_type) 24)
#define at_LAYOUT_STYLE	((INT_type) 25)
#define at_LAYOUT_STYLE_IDENTIFIER	((INT_type) 26)
#define at_LOGICAL_SOURCE	((INT_type) 27)
#define at_MEDIUM_TYPE	((INT_type) 28)
#define at_NEW_LAYOUT_OBJECT	((INT_type) 29)
#define at_OBJECT_CLASS	((INT_type) 30)
#define at_OBJECT_CLASS_IDENTIFIER	((INT_type) 31)
#define at_OBJECT_IDENTIFIER	((INT_type) 32)
#define at_OBJECT_TYPE	((INT_type) 33)
#define at_OFFSET	((INT_type) 34)
#define at_PAGE_POSITION	((INT_type) 35)
#define at_PERMITTED_CATEGORIES	((INT_type) 36)
#define at_POSITION	((INT_type) 37)
#define at_PRESENTATION_STYLE	((INT_type) 38)
#define at_PRESENTATION_STYLE_ID	((INT_type) 39)
#define at_PROTECTION	((INT_type) 40)
#define at_RESOURCE	((INT_type) 41)
#define at_SAME_LAYOUT_OBJECT	((INT_type) 42)
#define at_SEPARATION	((INT_type) 43)
#define at_SUBORDINATES	((INT_type) 44)
#define at_SYNCHRONIZATION	((INT_type) 45)
#define at_TRANSPARENCY	((INT_type) 46)
#define at_TYPE_OF_CODING	((INT_type) 47)
#define at_USER_READABLE_COMMENTS	((INT_type) 48)
#define at_USER_VISIBLE_NAME	((INT_type) 49)
#define cc_1ST_LINE_OFFSET	((INT_type) 50)
#define cc_ALIGNMENT	((INT_type) 51)
#define cc_CHAR_ORIENTATION	((INT_type) 52)
#define cc_CHARACTER_FONTS	((INT_type) 53)
#define cc_CHARACTER_PATH	((INT_type) 54)
#define cc_CHARACTER_SPACING	((INT_type) 55)
#define cc_CODE_EXT_ANNOUNCERS	((INT_type) 56)
#define cc_FORMATTING_INDICATOR	((INT_type) 57)
#define cc_GRAPHIC_CHAR_SUBREP	((INT_type) 58)
#define cc_GRAPHIC_CHARACTER_SETS	((INT_type) 59)
#define cc_GRAPHIC_RENDITION	((INT_type) 60)
#define cc_INDENTATION	((INT_type) 61)
#define cc_INITIAL_OFFSET	((INT_type) 62)
#define cc_ITEMISATION	((INT_type) 63)
#define cc_KERNING_OFFSET	((INT_type) 64)
#define cc_LINE_LAYOUT_TABLE	((INT_type) 65)
#define cc_LINE_PROGRESSION	((INT_type) 66)
#define cc_LINE_SPACING	((INT_type) 67)
#define cc_ORPHAN_SIZE	((INT_type) 68)
#define cc_PAIRWISE_KERNING	((INT_type) 69)
#define cc_PROP_LINE_SPACING	((INT_type) 70)
#define cc_WIDOW_SIZE	((INT_type) 71)
#define dp_ABSTRACT	((INT_type) 72)
#define dp_ACCESS_RIGHTS	((INT_type) 73)
#define dp_ADDITIONAL_INFORMATION	((INT_type) 74)
#define dp_ALT_REP_CHARACTER_SETS	((INT_type) 75)
#define dp_AUTHORIZATION	((INT_type) 76)
#define dp_AUTHORS	((INT_type) 77)
#define dp_BLOCK_ALIGNMENTS	((INT_type) 78)
#define dp_CODING_ATTRIBUTES	((INT_type) 79)
#define dp_COLOURS	((INT_type) 80)
#define dp_COMMENTS_CHARACTER_SETS	((INT_type) 81)
#define dp_CONTENT_ARCH_CLASSES	((INT_type) 82)
#define dp_COPYRIGHT	((INT_type) 83)
#define dp_CREATION_DATE_AND_TIME	((INT_type) 84)
#define dp_DISTRIBUTION_LIST	((INT_type) 85)
#define dp_DOC_APP_PROF_DEFAULTS	((INT_type) 86)
#define dp_DOC_APP_PROFILE	((INT_type) 87)
#define dp_DOC_ARCH_CLASS	((INT_type) 88)
#define dp_DOCUMENT_DATE_AND_TIME	((INT_type) 89)
#define dp_DOCUMENT_REFERENCE	((INT_type) 90)
#define dp_DOCUMENT_SIZE	((INT_type) 91)
#define dp_DOCUMENT_TYPE	((INT_type) 92)
#define dp_EXPIRY_DATE_AND_TIME	((INT_type) 93)
#define dp_EXTERNAL_DOCUMENT_CLASS	((INT_type) 94)
#define dp_FILL_ORDERS	((INT_type) 95)
#define dp_FONTS_LIST	((INT_type) 96)
#define dp_GENERIC_LAY_STRUCT	((INT_type) 97)
#define dp_GENERIC_LOG_STRUCT	((INT_type) 98)
#define dp_INTERCHANGE_FMT_CLASS	((INT_type) 99)
#define dp_LANGUAGES	((INT_type) 100)
#define dp_LAYOUT_PATHS	((INT_type) 101)
#define dp_LAYOUT_STYLES	((INT_type) 102)
#define dp_LOCAL_FILE_REFERENCE	((INT_type) 103)
#define dp_LOCAL_FILING_DATE_TIME	((INT_type) 104)
#define dp_MEDIUM_TYPES	((INT_type) 105)
#define dp_NUMBER_OBJECTS_PER_PAGE	((INT_type) 106)
#define dp_NUMBER_OF_PAGES	((INT_type) 107)
#define dp_ODA_VERSION	((INT_type) 108)
#define dp_ORGANIZATIONS	((INT_type) 109)
#define dp_OWNERS	((INT_type) 110)
#define dp_PAGE_DIMENSIONS	((INT_type) 111)
#define dp_PAGE_POSITIONS	((INT_type) 112)
#define dp_PREPARERS	((INT_type) 113)
#define dp_PRESENTATION_FEATURES	((INT_type) 114)
#define dp_PRESENTATION_STYLES	((INT_type) 115)
#define dp_PROFILE_CHARACTER_SETS	((INT_type) 116)
#define dp_PROTECTIONS	((INT_type) 117)
#define dp_PURGE_DATE_AND_TIME	((INT_type) 118)
#define dp_REFS_TO_OTHER_DOCS	((INT_type) 119)
#define dp_RELEASE_DATE_AND_TIME	((INT_type) 120)
#define dp_RESOURCE_DOCUMENT	((INT_type) 121)
#define dp_RESOURCES	((INT_type) 122)
#define dp_REVISION_HISTORY	((INT_type) 123)
#define dp_SECURITY_CLASSIFICATION	((INT_type) 124)
#define dp_SPECIFIC_LAY_STRUCT	((INT_type) 125)
#define dp_SPECIFIC_LOG_STRUCT	((INT_type) 126)
#define dp_START_DATE_AND_TIME	((INT_type) 127)
#define dp_STATUS	((INT_type) 128)
#define dp_SUBJECT	((INT_type) 129)
#define dp_SUPERSEDED_DOCUMENTS	((INT_type) 130)
#define dp_TITLE	((INT_type) 131)
#define dp_TRANSPARENCIES	((INT_type) 132)
#define dp_TYPES_OF_CODING	((INT_type) 133)
#define dp_UNIT_SCALING	((INT_type) 134)
#define dp_USER_SPECIFIC_CODES	((INT_type) 135)
#define gg_COLOUR_REPS	((INT_type) 136)
#define gg_EDGE_RENDITION	((INT_type) 137)
#define gg_ENCODING_ANNOUNCER	((INT_type) 138)
#define gg_FILLED_AREA_REND	((INT_type) 139)
#define gg_LINE_RENDITION	((INT_type) 140)
#define gg_MARKER_RENDITION	((INT_type) 141)
#define gg_PICTURE_DIMENSIONS	((INT_type) 142)
#define gg_PICTURE_ORIENTATION	((INT_type) 143)
#define gg_REGION_INTEREST_SPEC	((INT_type) 144)
#define gg_TEXT_RENDITION	((INT_type) 145)
#define gg_TRANSFORMATION_SPEC	((INT_type) 146)
#define gg_TRANSPARENCY_SPEC	((INT_type) 147)
#define rg_CLIPPING	((INT_type) 148)
#define rg_COMPRESSION	((INT_type) 149)
#define rg_IMAGE_DIMENSIONS	((INT_type) 150)
#define rg_INITIAL_OFFSET	((INT_type) 151)
#define rg_LINE_PROGRESSION	((INT_type) 152)
#define rg_NUMBER_DISCARDED_PELS	((INT_type) 153)
#define rg_NUMBER_OF_LINES	((INT_type) 154)
#define rg_NUMBER_OF_PELS_PER_LINE	((INT_type) 155)
#define rg_PEL_PATH	((INT_type) 156)
#define rg_PEL_SPACING	((INT_type) 157)
#define rg_PEL_TRANS_DENSITY	((INT_type) 158)
#define rg_SPACING_RATIO	((INT_type) 159)

/* Note: these can't be casted because of a VMS restriction
   on casted integers in array bounds */
#define MIN_ATTR	(1)
#define MAX_ATTR	(159)

#endif
