
/*
		(c) Copyright 1988 Carnegie Mellon University

 See "The CMU ODA Tool Kit" (available as CMU/ITC tech report
 CMU-ITC-071) for full text & permitted uses.
    WARNING: this file is generated from the API.
    WARNING: modifications to this file will disappear
    WARNING: when the file is next generated.



It includes the real/alias names for the canonical
procedures for performing operations on the
aunion.h types.



*/

/*
	Next come the real/alias names for all the
	procedures for performing canonical operations
	on the aunion.h types.
*/


#ifndef USE_LONG_NAMES

#define at_BORDER_WDbug gzabcd
#define at_BORDER_Copy gzabce
#define at_BORDER_CkVal gzabcf
#define at_BORDER_Alloc gzabcg
#define at_BORDER_Free gzabch
#define at_BORDER_Set gzabci
#define at_BORDER_Get gzabcj
#define at_BORDER_Deflt gzabck
#define at_DEFAULT_VALUE_LISTS_WDbug gzabcl
#define at_DEFAULT_VALUE_LISTS_Copy gzabcm
#define at_DEFAULT_VALUE_LISTS_CkVal gzabcn
#define at_DEFAULT_VALUE_LISTS_Alloc gzabco
#define at_DEFAULT_VALUE_LISTS_Free gzabcp
#define at_DEFAULT_VALUE_LISTS_Set gzabcq
#define at_DEFAULT_VALUE_LISTS_Get gzabcr
#define at_DEFAULT_VALUE_LISTS_Deflt gzabcs
#define at_DIMENSIONS_WDbug gzabct
#define at_DIMENSIONS_Copy gzabcu
#define at_DIMENSIONS_CkVal gzabcv
#define at_DIMENSIONS_Alloc gzabcw
#define at_DIMENSIONS_Free gzabcx
#define at_DIMENSIONS_Set gzabcy
#define at_DIMENSIONS_Get gzabcz
#define at_DIMENSIONS_Deflt gzabda
#define at_MEDIUM_TYPE_WDbug gzabdb
#define at_MEDIUM_TYPE_Copy gzabdc
#define at_MEDIUM_TYPE_CkVal gzabdd
#define at_MEDIUM_TYPE_Alloc gzabde
#define at_MEDIUM_TYPE_Free gzabdf
#define at_MEDIUM_TYPE_Set gzabdg
#define at_MEDIUM_TYPE_Get gzabdh
#define at_MEDIUM_TYPE_Deflt gzabdi
#define at_OFFSET_WDbug gzabdj
#define at_OFFSET_Copy gzabdk
#define at_OFFSET_CkVal gzabdl
#define at_OFFSET_Alloc gzabdm
#define at_OFFSET_Free gzabdn
#define at_OFFSET_Set gzabdo
#define at_OFFSET_Get gzabdp
#define at_OFFSET_Deflt gzabdq
#define at_POSITION_WDbug gzabdr
#define at_POSITION_Copy gzabds
#define at_POSITION_CkVal gzabdt
#define at_POSITION_Alloc gzabdu
#define at_POSITION_Free gzabdv
#define at_POSITION_Set gzabdw
#define at_POSITION_Get gzabdx
#define at_POSITION_Deflt gzabdy
#define at_SAME_LAYOUT_OBJECT_WDbug gzabdz
#define at_SAME_LAYOUT_OBJECT_Copy gzabea
#define at_SAME_LAYOUT_OBJECT_CkVal gzabeb
#define at_SAME_LAYOUT_OBJECT_Alloc gzabec
#define at_SAME_LAYOUT_OBJECT_Free gzabed
#define at_SAME_LAYOUT_OBJECT_Set gzabee
#define at_SAME_LAYOUT_OBJECT_Get gzabef
#define at_SAME_LAYOUT_OBJECT_Deflt gzabeg
#define at_SEPARATION_WDbug gzabeh
#define at_SEPARATION_Copy gzabei
#define at_SEPARATION_CkVal gzabej
#define at_SEPARATION_Alloc gzabek
#define at_SEPARATION_Free gzabel
#define at_SEPARATION_Set gzabem
#define at_SEPARATION_Get gzaben
#define at_SEPARATION_Deflt gzabeo
#define cc_ITEMISATION_WDbug gzabep
#define cc_ITEMISATION_Copy gzabeq
#define cc_ITEMISATION_CkVal gzaber
#define cc_ITEMISATION_Alloc gzabes
#define cc_ITEMISATION_Free gzabet
#define cc_ITEMISATION_Set gzabeu
#define cc_ITEMISATION_Get gzabev
#define cc_ITEMISATION_Deflt gzabew
#define CONSTITUENT_WDbug gzabex
#define CONSTITUENT_Copy gzabey
#define CONSTITUENT_CkVal gzabez
#define CONSTITUENT_Alloc gzabfa
#define CONSTITUENT_Free gzabfb
#define CONSTITUENT_Set gzabfc
#define CONSTITUENT_Get gzabfd
#define CONSTITUENT_Deflt gzabfe
#define CONSTRUCTION_EXPR_WDbug gzabff
#define CONSTRUCTION_EXPR_Copy gzabfg
#define CONSTRUCTION_EXPR_CkVal gzabfh
#define CONSTRUCTION_EXPR_Alloc gzabfi
#define CONSTRUCTION_EXPR_Free gzabfj
#define CONSTRUCTION_EXPR_Set gzabfk
#define CONSTRUCTION_EXPR_Get gzabfl
#define CONSTRUCTION_EXPR_Deflt gzabfm
#define dp_DOC_APP_PROF_DEFAULTS_WDbug gzabfn
#define dp_DOC_APP_PROF_DEFAULTS_Copy gzabfo
#define dp_DOC_APP_PROF_DEFAULTS_CkVal gzabfp
#define dp_DOC_APP_PROF_DEFAULTS_Alloc gzabfq
#define dp_DOC_APP_PROF_DEFAULTS_Free gzabfr
#define dp_DOC_APP_PROF_DEFAULTS_Set gzabfs
#define dp_DOC_APP_PROF_DEFAULTS_Get gzabft
#define dp_DOC_APP_PROF_DEFAULTS_Deflt gzabfu
#define dp_LOCAL_FILE_REFERENCE_WDbug gzabfv
#define dp_LOCAL_FILE_REFERENCE_Copy gzabfw
#define dp_LOCAL_FILE_REFERENCE_CkVal gzabfx
#define dp_LOCAL_FILE_REFERENCE_Alloc gzabfy
#define dp_LOCAL_FILE_REFERENCE_Free gzabfz
#define dp_LOCAL_FILE_REFERENCE_Set gzabga
#define dp_LOCAL_FILE_REFERENCE_Get gzabgb
#define dp_LOCAL_FILE_REFERENCE_Deflt gzabgc
#define dp_ODA_VERSION_WDbug gzabgd
#define dp_ODA_VERSION_Copy gzabge
#define dp_ODA_VERSION_CkVal gzabgf
#define dp_ODA_VERSION_Alloc gzabgg
#define dp_ODA_VERSION_Free gzabgh
#define dp_ODA_VERSION_Set gzabgi
#define dp_ODA_VERSION_Get gzabgj
#define dp_ODA_VERSION_Deflt gzabgk
#define gg_COLOUR_REPS_WDbug gzabgl
#define gg_COLOUR_REPS_Copy gzabgm
#define gg_COLOUR_REPS_CkVal gzabgn
#define gg_COLOUR_REPS_Alloc gzabgo
#define gg_COLOUR_REPS_Free gzabgp
#define gg_COLOUR_REPS_Set gzabgq
#define gg_COLOUR_REPS_Get gzabgr
#define gg_COLOUR_REPS_Deflt gzabgs
#define gg_EDGE_RENDITION_WDbug gzabgt
#define gg_EDGE_RENDITION_Copy gzabgu
#define gg_EDGE_RENDITION_CkVal gzabgv
#define gg_EDGE_RENDITION_Alloc gzabgw
#define gg_EDGE_RENDITION_Free gzabgx
#define gg_EDGE_RENDITION_Set gzabgy
#define gg_EDGE_RENDITION_Get gzabgz
#define gg_EDGE_RENDITION_Deflt gzabha
#define gg_ENCODING_ANNOUNCER_WDbug gzabhb
#define gg_ENCODING_ANNOUNCER_Copy gzabhc
#define gg_ENCODING_ANNOUNCER_CkVal gzabhd
#define gg_ENCODING_ANNOUNCER_Alloc gzabhe
#define gg_ENCODING_ANNOUNCER_Free gzabhf
#define gg_ENCODING_ANNOUNCER_Set gzabhg
#define gg_ENCODING_ANNOUNCER_Get gzabhh
#define gg_ENCODING_ANNOUNCER_Deflt gzabhi
#define gg_FILLED_AREA_REND_WDbug gzabhj
#define gg_FILLED_AREA_REND_Copy gzabhk
#define gg_FILLED_AREA_REND_CkVal gzabhl
#define gg_FILLED_AREA_REND_Alloc gzabhm
#define gg_FILLED_AREA_REND_Free gzabhn
#define gg_FILLED_AREA_REND_Set gzabho
#define gg_FILLED_AREA_REND_Get gzabhp
#define gg_FILLED_AREA_REND_Deflt gzabhq
#define gg_LINE_RENDITION_WDbug gzabhr
#define gg_LINE_RENDITION_Copy gzabhs
#define gg_LINE_RENDITION_CkVal gzabht
#define gg_LINE_RENDITION_Alloc gzabhu
#define gg_LINE_RENDITION_Free gzabhv
#define gg_LINE_RENDITION_Set gzabhw
#define gg_LINE_RENDITION_Get gzabhx
#define gg_LINE_RENDITION_Deflt gzabhy
#define gg_MARKER_RENDITION_WDbug gzabhz
#define gg_MARKER_RENDITION_Copy gzabia
#define gg_MARKER_RENDITION_CkVal gzabib
#define gg_MARKER_RENDITION_Alloc gzabic
#define gg_MARKER_RENDITION_Free gzabid
#define gg_MARKER_RENDITION_Set gzabie
#define gg_MARKER_RENDITION_Get gzabif
#define gg_MARKER_RENDITION_Deflt gzabig
#define gg_PICTURE_DIMENSIONS_WDbug gzabih
#define gg_PICTURE_DIMENSIONS_Copy gzabii
#define gg_PICTURE_DIMENSIONS_CkVal gzabij
#define gg_PICTURE_DIMENSIONS_Alloc gzabik
#define gg_PICTURE_DIMENSIONS_Free gzabil
#define gg_PICTURE_DIMENSIONS_Set gzabim
#define gg_PICTURE_DIMENSIONS_Get gzabin
#define gg_PICTURE_DIMENSIONS_Deflt gzabio
#define gg_REGION_INTEREST_SPEC_WDbug gzabip
#define gg_REGION_INTEREST_SPEC_Copy gzabiq
#define gg_REGION_INTEREST_SPEC_CkVal gzabir
#define gg_REGION_INTEREST_SPEC_Alloc gzabis
#define gg_REGION_INTEREST_SPEC_Free gzabit
#define gg_REGION_INTEREST_SPEC_Set gzabiu
#define gg_REGION_INTEREST_SPEC_Get gzabiv
#define gg_REGION_INTEREST_SPEC_Deflt gzabiw
#define gg_TEXT_RENDITION_WDbug gzabix
#define gg_TEXT_RENDITION_Copy gzabiy
#define gg_TEXT_RENDITION_CkVal gzabiz
#define gg_TEXT_RENDITION_Alloc gzabja
#define gg_TEXT_RENDITION_Free gzabjb
#define gg_TEXT_RENDITION_Set gzabjc
#define gg_TEXT_RENDITION_Get gzabjd
#define gg_TEXT_RENDITION_Deflt gzabje
#define gg_TRANSFORMATION_SPEC_WDbug gzabjf
#define gg_TRANSFORMATION_SPEC_Copy gzabjg
#define gg_TRANSFORMATION_SPEC_CkVal gzabjh
#define gg_TRANSFORMATION_SPEC_Alloc gzabji
#define gg_TRANSFORMATION_SPEC_Free gzabjj
#define gg_TRANSFORMATION_SPEC_Set gzabjk
#define gg_TRANSFORMATION_SPEC_Get gzabjl
#define gg_TRANSFORMATION_SPEC_Deflt gzabjm
#define gg_TRANSPARENCY_SPEC_WDbug gzabjn
#define gg_TRANSPARENCY_SPEC_Copy gzabjo
#define gg_TRANSPARENCY_SPEC_CkVal gzabjp
#define gg_TRANSPARENCY_SPEC_Alloc gzabjq
#define gg_TRANSPARENCY_SPEC_Free gzabjr
#define gg_TRANSPARENCY_SPEC_Set gzabjs
#define gg_TRANSPARENCY_SPEC_Get gzabjt
#define gg_TRANSPARENCY_SPEC_Deflt gzabju
#define INT_WDbug gzabjv
#define INT_Copy gzabjw
#define INT_CkVal gzabjx
#define INT_Alloc gzabjy
#define INT_Free gzabjz
#define INT_Set gzabka
#define INT_Get gzabkb
#define INT_Deflt gzabkc
#define INT_PAIR_WDbug gzabkd
#define INT_PAIR_Copy gzabke
#define INT_PAIR_CkVal gzabkf
#define INT_PAIR_Alloc gzabkg
#define INT_PAIR_Free gzabkh
#define INT_PAIR_Set gzabki
#define INT_PAIR_Get gzabkj
#define INT_PAIR_Deflt gzabkk
#define LAYOUT_OBJECT_WDbug gzabkl
#define LAYOUT_OBJECT_Copy gzabkm
#define LAYOUT_OBJECT_CkVal gzabkn
#define LAYOUT_OBJECT_Alloc gzabko
#define LAYOUT_OBJECT_Free gzabkp
#define LAYOUT_OBJECT_Set gzabkq
#define LAYOUT_OBJECT_Get gzabkr
#define LAYOUT_OBJECT_Deflt gzabks
#define rg_CLIPPING_WDbug gzabkt
#define rg_CLIPPING_Copy gzabku
#define rg_CLIPPING_CkVal gzabkv
#define rg_CLIPPING_Alloc gzabkw
#define rg_CLIPPING_Free gzabkx
#define rg_CLIPPING_Set gzabky
#define rg_CLIPPING_Get gzabkz
#define rg_CLIPPING_Deflt gzabla
#define rg_IMAGE_DIMENSIONS_WDbug gzablb
#define rg_IMAGE_DIMENSIONS_Copy gzablc
#define rg_IMAGE_DIMENSIONS_CkVal gzabld
#define rg_IMAGE_DIMENSIONS_Alloc gzable
#define rg_IMAGE_DIMENSIONS_Free gzablf
#define rg_IMAGE_DIMENSIONS_Set gzablg
#define rg_IMAGE_DIMENSIONS_Get gzablh
#define rg_IMAGE_DIMENSIONS_Deflt gzabli
#define rg_PEL_SPACING_WDbug gzablj
#define rg_PEL_SPACING_Copy gzablk
#define rg_PEL_SPACING_CkVal gzabll
#define rg_PEL_SPACING_Alloc gzablm
#define rg_PEL_SPACING_Free gzabln
#define rg_PEL_SPACING_Set gzablo
#define rg_PEL_SPACING_Get gzablp
#define rg_PEL_SPACING_Deflt gzablq
#define SEQUENCE_ASN1_OBJECT_ID_WDbug gzablr
#define SEQUENCE_ASN1_OBJECT_ID_Copy gzabls
#define SEQUENCE_ASN1_OBJECT_ID_CkVal gzablt
#define SEQUENCE_ASN1_OBJECT_ID_Alloc gzablu
#define SEQUENCE_ASN1_OBJECT_ID_Free gzablv
#define SEQUENCE_ASN1_OBJECT_ID_Set gzablw
#define SEQUENCE_ASN1_OBJECT_ID_Get gzablx
#define SEQUENCE_ASN1_OBJECT_ID_Deflt gzably
#define SEQUENCE_at_MEDIUM_TYPE_WDbug gzablz
#define SEQUENCE_at_MEDIUM_TYPE_Copy gzabma
#define SEQUENCE_at_MEDIUM_TYPE_CkVal gzabmb
#define SEQUENCE_at_MEDIUM_TYPE_Alloc gzabmc
#define SEQUENCE_at_MEDIUM_TYPE_Free gzabmd
#define SEQUENCE_at_MEDIUM_TYPE_Set gzabme
#define SEQUENCE_at_MEDIUM_TYPE_Get gzabmf
#define SEQUENCE_at_MEDIUM_TYPE_Deflt gzabmg
#define SEQUENCE_BINDING_PAIR_WDbug gzabmh
#define SEQUENCE_BINDING_PAIR_Copy gzabmi
#define SEQUENCE_BINDING_PAIR_CkVal gzabmj
#define SEQUENCE_BINDING_PAIR_Alloc gzabmk
#define SEQUENCE_BINDING_PAIR_Free gzabml
#define SEQUENCE_BINDING_PAIR_Set gzabmm
#define SEQUENCE_BINDING_PAIR_Get gzabmn
#define SEQUENCE_BINDING_PAIR_Deflt gzabmo
#define SEQUENCE_BYTE_WDbug gzabmp
#define SEQUENCE_BYTE_Copy gzabmq
#define SEQUENCE_BYTE_CkVal gzabmr
#define SEQUENCE_BYTE_Alloc gzabms
#define SEQUENCE_BYTE_Free gzabmt
#define SEQUENCE_BYTE_Set gzabmu
#define SEQUENCE_BYTE_Get gzabmv
#define SEQUENCE_BYTE_Deflt gzabmw
#define SEQUENCE_CONSTITUENT_WDbug gzabmx
#define SEQUENCE_CONSTITUENT_Copy gzabmy
#define SEQUENCE_CONSTITUENT_CkVal gzabmz
#define SEQUENCE_CONSTITUENT_Alloc gzabna
#define SEQUENCE_CONSTITUENT_Free gzabnb
#define SEQUENCE_CONSTITUENT_Set gzabnc
#define SEQUENCE_CONSTITUENT_Get gzabnd
#define SEQUENCE_CONSTITUENT_Deflt gzabne
#define SEQUENCE_COPYRIGHT_INFO_WDbug gzabnf
#define SEQUENCE_COPYRIGHT_INFO_Copy gzabng
#define SEQUENCE_COPYRIGHT_INFO_CkVal gzabnh
#define SEQUENCE_COPYRIGHT_INFO_Alloc gzabni
#define SEQUENCE_COPYRIGHT_INFO_Free gzabnj
#define SEQUENCE_COPYRIGHT_INFO_Set gzabnk
#define SEQUENCE_COPYRIGHT_INFO_Get gzabnl
#define SEQUENCE_COPYRIGHT_INFO_Deflt gzabnm
#define SEQUENCE_FONT_PAIR_WDbug gzabnn
#define SEQUENCE_FONT_PAIR_Copy gzabno
#define SEQUENCE_FONT_PAIR_CkVal gzabnp
#define SEQUENCE_FONT_PAIR_Alloc gzabnq
#define SEQUENCE_FONT_PAIR_Free gzabnr
#define SEQUENCE_FONT_PAIR_Set gzabns
#define SEQUENCE_FONT_PAIR_Get gzabnt
#define SEQUENCE_FONT_PAIR_Deflt gzabnu
#define SEQUENCE_INT_WDbug gzabnv
#define SEQUENCE_INT_Copy gzabnw
#define SEQUENCE_INT_CkVal gzabnx
#define SEQUENCE_INT_Alloc gzabny
#define SEQUENCE_INT_Free gzabnz
#define SEQUENCE_INT_Set gzaboa
#define SEQUENCE_INT_Get gzabob
#define SEQUENCE_INT_Deflt gzaboc
#define SEQUENCE_INT_PAIR_WDbug gzabod
#define SEQUENCE_INT_PAIR_Copy gzaboe
#define SEQUENCE_INT_PAIR_CkVal gzabof
#define SEQUENCE_INT_PAIR_Alloc gzabog
#define SEQUENCE_INT_PAIR_Free gzaboh
#define SEQUENCE_INT_PAIR_Set gzaboi
#define SEQUENCE_INT_PAIR_Get gzaboj
#define SEQUENCE_INT_PAIR_Deflt gzabok
#define SEQUENCE_NAME_ORG_WDbug gzabol
#define SEQUENCE_NAME_ORG_Copy gzabom
#define SEQUENCE_NAME_ORG_CkVal gzabon
#define SEQUENCE_NAME_ORG_Alloc gzaboo
#define SEQUENCE_NAME_ORG_Free gzabop
#define SEQUENCE_NAME_ORG_Set gzaboq
#define SEQUENCE_NAME_ORG_Get gzabor
#define SEQUENCE_NAME_ORG_Deflt gzabos
#define SEQUENCE_RESOURCE_MAP_WDbug gzabot
#define SEQUENCE_RESOURCE_MAP_Copy gzabou
#define SEQUENCE_RESOURCE_MAP_CkVal gzabov
#define SEQUENCE_RESOURCE_MAP_Alloc gzabow
#define SEQUENCE_RESOURCE_MAP_Free gzabox
#define SEQUENCE_RESOURCE_MAP_Set gzaboy
#define SEQUENCE_RESOURCE_MAP_Get gzaboz
#define SEQUENCE_RESOURCE_MAP_Deflt gzabpa
#define SEQUENCE_REVISION_HISTORY_WDbug gzabpb
#define SEQUENCE_REVISION_HISTORY_Copy gzabpc
#define SEQUENCE_REVISION_HISTORY_CkVal gzabpd
#define SEQUENCE_REVISION_HISTORY_Alloc gzabpe
#define SEQUENCE_REVISION_HISTORY_Free gzabpf
#define SEQUENCE_REVISION_HISTORY_Set gzabpg
#define SEQUENCE_REVISION_HISTORY_Get gzabph
#define SEQUENCE_REVISION_HISTORY_Deflt gzabpi
#define SEQUENCE_STRING_WDbug gzabpj
#define SEQUENCE_STRING_Copy gzabpk
#define SEQUENCE_STRING_CkVal gzabpl
#define SEQUENCE_STRING_Alloc gzabpm
#define SEQUENCE_STRING_Free gzabpn
#define SEQUENCE_STRING_Set gzabpo
#define SEQUENCE_STRING_Get gzabpp
#define SEQUENCE_STRING_Deflt gzabpq
#define SEQUENCE_STRING_OR_ID_WDbug gzabpr
#define SEQUENCE_STRING_OR_ID_Copy gzabps
#define SEQUENCE_STRING_OR_ID_CkVal gzabpt
#define SEQUENCE_STRING_OR_ID_Alloc gzabpu
#define SEQUENCE_STRING_OR_ID_Free gzabpv
#define SEQUENCE_STRING_OR_ID_Set gzabpw
#define SEQUENCE_STRING_OR_ID_Get gzabpx
#define SEQUENCE_STRING_OR_ID_Deflt gzabpy
#define SEQUENCE_TAB_STOP_WDbug gzabpz
#define SEQUENCE_TAB_STOP_Copy gzabqa
#define SEQUENCE_TAB_STOP_CkVal gzabqb
#define SEQUENCE_TAB_STOP_Alloc gzabqc
#define SEQUENCE_TAB_STOP_Free gzabqd
#define SEQUENCE_TAB_STOP_Set gzabqe
#define SEQUENCE_TAB_STOP_Get gzabqf
#define SEQUENCE_TAB_STOP_Deflt gzabqg
#define SEQUENCE_VALUE_WDbug gzabqh
#define SEQUENCE_VALUE_Copy gzabqi
#define SEQUENCE_VALUE_CkVal gzabqj
#define SEQUENCE_VALUE_Alloc gzabqk
#define SEQUENCE_VALUE_Free gzabql
#define SEQUENCE_VALUE_Set gzabqm
#define SEQUENCE_VALUE_Get gzabqn
#define SEQUENCE_VALUE_Deflt gzabqo
#define STRING_WDbug gzabqp
#define STRING_Copy gzabqq
#define STRING_CkVal gzabqr
#define STRING_Alloc gzabqs
#define STRING_Free gzabqt
#define STRING_Set gzabqu
#define STRING_Get gzabqv
#define STRING_Deflt gzabqw
#define STRING_EXPR_WDbug gzabqx
#define STRING_EXPR_Copy gzabqy
#define STRING_EXPR_CkVal gzabqz
#define STRING_EXPR_Alloc gzabra
#define STRING_EXPR_Free gzabrb
#define STRING_EXPR_Set gzabrc
#define STRING_EXPR_Get gzabrd
#define STRING_EXPR_Deflt gzabre
#define STRING_OR_ID_WDbug gzabrf
#define STRING_OR_ID_Copy gzabrg
#define STRING_OR_ID_CkVal gzabrh
#define STRING_OR_ID_Alloc gzabri
#define STRING_OR_ID_Free gzabrj
#define STRING_OR_ID_Set gzabrk
#define STRING_OR_ID_Get gzabrl
#define STRING_OR_ID_Deflt gzabrm
#define VALUE_WDbug gzabrn
#define VALUE_Copy gzabro
#define VALUE_CkVal gzabrp
#define VALUE_Alloc gzabrq
#define VALUE_Free gzabrr
#define VALUE_Set gzabrs
#define VALUE_Get gzabrt
#define VALUE_Deflt gzabru


#endif
/* Endif closes the ifndef USE_LONG_NAMES */


