#define    parent_cw_default "NULL"
#define    x_cw_default 0
#define    y_cw_default 0
#define    width_cw_default 50
#define    height_cw_default 20
#define    border_width_cw_default 1
#define    border_color_cw_default "black"
#define    background_color_cw_default "white"
#define    sensitive_cw_default TRUE
#define    mapped_when_managed_cw_default TRUE
#define    foreground_color_cw_default "black"
#define    label_text_cw_default "<label>"
#define    justify_cw_default CENTER
#define    internal_width_cw_default 4
#define    internal_height_cw_default 2
#define    parent_cw_pos 1
#define    x_cw_pos 2
#define    y_cw_pos 3
#define    width_cw_pos 4
#define    height_cw_pos 5
#define    border_width_cw_pos 6
#define    border_color_cw_pos 7
#define    background_color_cw_pos 8
#define    sensitive_cw_pos 9
#define    mapped_when_managed_cw_pos 10
#define    foreground_color_cw_pos 11
#define    label_text_cw_pos 12
#define    justify_cw_pos 13
#define    internal_width_cw_pos 14
#define    internal_height_cw_pos 15
