#define parent_attribute 0
#define label_text_attribute 1
#define x_attribute 2
#define y_attribute 3
#define width_attribute 4
#define height_attribute 5
#define foreground_color_attribute 6
#define background_color_attribute 7
#define border_width_attribute 8
#define border_color_attribute 9
#define vert_distance_attribute 10
#define from_vert_attribute 11
#define horiz_distance_attribute 12
#define from_horiz_attribute 13
#define sensitive_attribute 14
#define justify_attribute 15
#define internal_width_attribute 16
#define internal_height_attribute 17
#define min_height_attribute 18
#define max_height_attribute 19
#define skip_adjust_attribute 20
#define resizable_attribute 21
#define allow_resize_attribute 22
#define mapped_when_managed_attribute 23
