#!/bin/csh -f
if ($#argv == 0) then
	set OBJDIR=.
else
	set OBJDIR=$1
endif
cd ${OBJDIR}
if (! -e Imakefile) then
	echo "==>>> No Imakefile - Cannot Generate Makefile <<<=="
	exit(1)
endif
set DIR=`pwd | tr '/' ' '`
