#!/bin/csh -f

set IMAKE="$1"
set TOPLEVEL="$2"
set TOPPARTS=`echo $TOPLEVEL | tr '/' ' '`

cat gen1 > genmake
echo "set TOP=#echo $TOPLEVEL | tr '/' ' '#" | sed -e 's;#;`;g' >> genmake
echo "set IMAKE = $IMAKE" >> genmake
cat gen2 >> genmake

set COUNT="$#TOPPARTS"
set CASE=1
if ($COUNT > 0) then
	while ($CASE <= $COUNT)
		echo "	case ${CASE}:" >> genmake
echo -n '	    set REL=${REL}' >> genmake
echo "$TOPLEVEL" >> genmake
echo "	    breaksw" >> genmake
		set FOO=$CASE
		@ FOO++
		set TOPLEVEL=""
		while ($FOO <= $COUNT)
			set TOPLEVEL=${TOPLEVEL}/$TOPPARTS[$FOO]
			@ FOO++
		end
		@ CASE++
	end
endif
cat gen3 >> genmake


