.TH XcuCommand 3X "\fBCornell University Widget Set\fR"
.ad b
.de}F    
.ds)H Program of Computer Graphics
.ev1
.}E
.if\\n()s 'sp |\\n(.pu-1v-1p
.if\\n()t 'sp |\\n(.pu-3v
.ifn 'sp |\\n(.pu-4v
.tl\\*()H- % -\\*(]W
'bp
.ev
..
.SH NAME
XcuCommand \- Display labels in a set or unset state.
.ne 4
.SH CLASS HIERARCHY
\ 
.br
Core / XcuSimple / XcuLabel / XcuCommand
.ne 4
.SH NEW RESOURCES
\ 
.br
.TS
allbox tab(;);
c s s s.
XcuCommand Resources
.T&
lB lB lB lB.
Name;Type;Default;Description
_
.T&
lB l l l.
XtNcallback;Callback;;Btn1Down and Btn1Up events
XtNcursor;Cursor;"dot";Provides a default cursor
.TE
.ne 4
.SH DESCRIPTION
\ 
.br
Behaves pretty much the same as the X11R2 Xaw \fBCommand\fR widget.
.ne 4
.SH SEE ALSO
\ 
.br
XcuLabel(3X), XcuSimple(3X)
.ne 4
.SH AUTHOR
\ 
.br
Gene Dykes, \fIgwd@freedom.graphics.cornell.edu\fR
.br
Program of Computer Graphics, Cornell University

