PIXDATA = arrow.10 arrow.12 arrow.14 arrow.16 dbx.icon \
	hollow.10 hollow.12 hollow.14 hollow.16 \
	mk.32.by.16 solid.10 solid.12 solid.14 solid.16 \
	stoparrow.10 stoparrow.12 stoparrow.14 stoparrow.16 \
	stopsign.10 stopsign.12 stopsign.14 stopsign.16

all: ${PIXDATA}

include ../../../Makefile.master
