.TH pnmcat 1 "12 March 1989"
.SH NAME
pnmcat - concatenate portable anymaps
.SH SYNOPSIS
pnmcat [-white|-black] -leftright|-lr|-topbottom|-tb pnmfile pnmfile ...
.SH DESCRIPTION
Reads portable anymaps as input.
Concatenates them either left to right or top to bottom, and produces a
portable anymap as output.
If the anymaps are not all the same height (left-right) or width (top-bottom),
the smaller ones are centered with the edges filled in.
The -white and -black flags specify what color to use for this fill -- if
neither is specified, the program makes a guess.
.PP
All flags can be abbreviated to their shortest unique prefix.
.SH "SEE ALSO"
pnm(5)
.SH AUTHOR
Copyright (C) 1989 by Jef Poskanzer.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted, provided
that the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.  This software is provided "as is" without express or
implied warranty.
